### ISSUE TITLE
PDF: IEEE ICAP template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#10]
See https://github.com/metanorma/metanorma-ieee/issues/6

**Comment by ronaldtse** [comment]
[ICAP_White_Paper_Template.docx](https://github.com/metanorma/metanorma-ieee/files/8904460/ICAP_White_Paper_Template.docx)

Related to #6

**Comment by Intelligent2013** [comment]
The differences between 'ICAP Whitepaper' and 'Whitepaper' templates are:
- additional word on the cover page:
![image](https://user-images.githubusercontent.com/5559926/174484748-f83fc9fb-7979-4de5-94a6-e1994b12c201.png)

- fixed program title:
![image](https://user-images.githubusercontent.com/5559926/174484769-bed383c8-c1b9-4c9d-910b-fddc5973e606.png)
vs. variable title:
![image](https://user-images.githubusercontent.com/5559926/174484780-142d5149-c954-4e15-9353-6297de1569f5.png)

- text 'CONFORMITY ASSESSMENT PROGRAM (ICAP)' at the footer
![image](https://user-images.githubusercontent.com/5559926/174484812-46b512a6-43e8-4c87-873c-52e087e66438.png)
vs. 'SA':
![image](https://user-images.githubusercontent.com/5559926/174484838-6de54480-8f9b-4e24-9734-c4dcee3b9755.png)

- different text in the section 'NOTICE AND DISCLAIMER...'

**Comment by Intelligent2013** [comment]
There is discrepancy between the manual and word template.
 
From https://github.com/metanorma/metanorma-ieee/files/8901439/IEEE-SA-Non_Standard_Projects_Style_Manual.pdf:
```
14.2 Figure numbering and titles:
... 
“Figure” and the figure number, followed by an em dash and the figure title, centered below the figure, as follows: “Figure 1—Title”.
```
Note: _below_ the figure.

But Figure's title in the Word template - _above_ the figure:
![image](https://user-images.githubusercontent.com/5559926/174485073-95ba1ff8-accb-4c7f-b137-7e31d595159c.png)

**Comment by ronaldtse** [comment]
> Note: _below_ the figure.
> 
> But Figure's title in the Word template - _above_ the figure:

Great find. @Intelligent2013 what does the standard template / standard style guide say?

**Comment by Intelligent2013** [comment]
@ronaldtse from '2021 IEEE SA Standards Style Manual' (2021_IEEE SA_Style Manual.pdf):

below too:

```
17.2 Figure numbering and titles
...
“Figure” and the figure number, followed by an em dash and the figure title, centered below the figure, as follows: “Figure 1—Title”.
```

**Comment by ronaldtse** [comment]
Since the style manual dictates it, we should place the figure caption below the figure.

**Comment by ronaldtse** [comment]
Have you looked at the IEEE SA FrameMaker template? (https://mentor.ieee.org/myproject/Public/mytools/draft/frame_template.zip)

It might provide hints to what the Word templates don't, especially since the FrameMaker templates does not seem to distinguish between Standard vs Amendment/Corr.

**Comment by Intelligent2013** [comment]
> Have you looked at the IEEE SA FrameMaker template? (https://mentor.ieee.org/myproject/Public/mytools/draft/frame_template.zip)

@ronaldtse `framemaker_body.mif` contains 3 pages only, the content similar to Word template.

![image](https://user-images.githubusercontent.com/5559926/174665898-c973fc5a-4aca-437e-b9bb-b89430265ef9.png)

`framemaker_frontmatter.mif` contains cover and preface pages.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 for the investigation!

**Comment by Intelligent2013** [comment]
Just for memory, xslt currently choose IEEE ICAP template by `bibdata/ext/ doctype = 'icap-whitepaper'` (set in the text xml manually for development purpose). This condition should be changed to the real value of doctype after metanorma-ieee update for ICAP whitepaper.

**Comment by Intelligent2013** [comment]
IEEE ICAP template have realized in the XSLT https://github.com/metanorma/metanorma-ieee/blob/main/lib/isodoc/ieee/ieee.standard.xsl. No more actions in this ticket.
