### ISSUE TITLE
Enable multiple co-chair members

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#101]
From https://github.com/metanorma/mn-samples-ieee-private/pull/9

![capture1-1](https://user-images.githubusercontent.com/33627611/179237722-12367b88-c367-479e-835d-a4ef4dbdfe06.PNG)

In the meantime, I have encoded it like:
````
:wg-chair: Mark Kaufman; Timothy Wilmering
````

**Comment by manuelfuenmayor** [comment]
Also, I don't know which doctype correspond to the boilerplace show above.
This one:
"*At the time this standard was submitted to the IEEE-SA Standards Board for approval, the Diagnostics and
Maintenance Control subcommittee had the following membership:*"

The one that I get is:
"*At the time this draft Standard was completed, the Diagnostics and Maintenance Control Working Group had the following membership:*"
(With setting `:working-group: Diagnostics and Maintenance Control`)

**Comment by ronaldtse** [comment]
@manuelfuenmayor for the "At the time..." standard, can you compare the three IEEE master documents to see if we can settle the correct format? Thanks.

**Comment by manuelfuenmayor** [comment]
I have opened another ticket to discuss the "boilerplate" subject.

**Comment by opoudjis** [comment]
Obsolete: you can implement this now as:

````
item::
name::: Mark Kaufman
role::: Co-chair
item::
name::: Timothy Wilmering
role::: Co-chair
````

**Comment by opoudjis** [comment]
> "At the time this draft Standard was completed, the Diagnostics and Maintenance Control Working Group had the following membership:"

We are allowing all the text to be user-supplied other than the initial sentence of each participants subsection. @manuelfuenmayor @ronaldtse If we must make that be user-supplied as well, we will, but I'd really rather avoid that.

**Comment by opoudjis** [comment]
Closing this ticket in favour of https://github.com/metanorma/metanorma-ieee/issues/105
