### ISSUE TITLE
Some fetched references are rendering in full content

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#104]
There fetched references that are being rendered in their full content instead of the identifier.

Taking https://github.com/metanorma/mn-samples-ieee-private/pull/9 as an example:

Reference encoding:
```adoc
* [[[IEEE_Std_260-1-2004,IEEE Std 260.1-2004]]], IEEE Std 260.1-2004, IEEE Standard Letter Symbols for Units of Measurement (SI Units,
Customary Inch-Pound Units, and Certain Other Units).
````

Somewhere in content:
```adoc
...
standardUnit:: Attribute "`standardUnit`" provides units based on
<<IEEE_Std_260-1-2004>>.
nonStandardUnit:: Attribute "`nonStandardUnit`" provides the units
of the value that do not necessarily conform to <<IEEE_Std_260-1-2004>>.
````

Renders in DOC:

Somewhere in content:
![issue2-1](https://user-images.githubusercontent.com/33627611/179251098-6667567e-6e65-4e97-949c-854341799333.PNG)

**Comment by opoudjis** [comment]
Yeah, that's the title being used when a citation is not recognised as a standard.

... Ugh, which means that I need to add to the microformat the document type, so that you explicitly instruct Metanorma that this is a standard, and therefore uses identifier instead of Author-Date (or as is currently the case, Title).

**Comment by ronaldtse** [comment]
@opoudjis I'm not sure I understand. Why would `IEEE Std 260.1-2004` not be recognized as a standard?

**Comment by opoudjis** [comment]
Just tested, and it is. Will need to do this addition anyway for other cases.

**Comment by opoudjis** [comment]
Cannot replicate: IEEE Std 260.1-2004 is now recognised as a standard, and accordingly renders as `<eref type="inline" bibitemid="IEEE_Std_260-1-2004" citeas="IEEE 260.1™-2004">IEEE 260.1™-2004 [B1]</eref>`. I assume that the parsing of IEEE identifiers has since been debugged.
