### ISSUE TITLE
PDF: styling for published documents not according to reference docs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#108]
The PDF styling for published documents generally look like:

* https://github.com/metanorma/ieee-ref-docs/blob/main/standards/8021X-2020.pdf
* https://github.com/metanorma/ieee-ref-docs/blob/main/standards/18002-2020.pdf
* https://github.com/metanorma/ieee-stl/blob/main/master-1-standard/master-1-standard.pdf

The current generated PDF uses the styling from the White Paper templates (`IEEE-SA-Non_Standard_Projects_Style_Manual.pdf`), which is incorrect for standards (`2021_IEEE SA_Style Manual.pdf`).

**Comment by Intelligent2013** [comment]
I can't repeat, for 'master-1-standard' it renders so:

![image](https://user-images.githubusercontent.com/5559926/179348945-d90cbc7c-d8a0-49bd-bd49-b1214bac5eeb.png)

**Comment by Intelligent2013** [comment]
IEEE xslt updated.
