### ISSUE TITLE
PDF: Support "draft standard" layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#11]
Use this as template: https://github.com/metanorma/ieee-ref-docs/blob/main/standards/IEEE%20P802.1DF:D0.0.pdf

**Comment by ronaldtse** [comment]
Word templates:
* Standard: [IEEESTD-WORDTEMPLATE_v1_2022.docx](https://github.com/metanorma/metanorma-ieee/files/8904465/IEEESTD-WORDTEMPLATE_v1_2022.docx)

* Corrigenda/Amendment: [IEEESTD-WORDTEMPLATE_Amendments-Corri-v7-2022.docx](https://github.com/metanorma/metanorma-ieee/files/8904464/IEEESTD-WORDTEMPLATE_Amendments-Corri-v7-2022.docx)

**Comment by Intelligent2013** [comment]
Title in xml:
```xml
<title language="main-en" format="text/plain">Spatial Web Protocol, Architecture and Governance</title>
```
Note: `language="main-en"`.

**Comment by ronaldtse** [comment]
Related to #48

**Comment by ronaldtse** [comment]
I believe this is implemented. Closing.
