### ISSUE TITLE
XML (and Word): Unable to specify a published document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#112]
The 1127 document (master document 1):
https://github.com/metanorma/mn-samples-ieee-private/tree/main/sources/1127

Is a published document. However it is rendered as a draft with docnumber of "P1127":
<img width="882" alt="Screenshot 2022-07-17 at 1 47 42 PM" src="https://user-images.githubusercontent.com/11865/179384348-0b88ce0a-a40f-485c-9022-d112c06b23ca.png">

**Comment by opoudjis** [comment]
The Word template ONLY provides for drafts, and I have been provided with ZERO guidance for published documents. You haven't even bothered providing a PDF target document.

Find out whether the identifier in print documents is meant to be 1127, or IEEE 1127-2013, as it is in https://standards.ieee.org/ieee/1127/4780/

**Comment by opoudjis** [comment]
PDF samples had not been uploaded.

**Comment by ronaldtse** [comment]
> The Word template ONLY provides for drafts, and I have been provided with ZERO guidance for published documents. You haven't even bothered providing a PDF target document.

Finally uploaded in https://github.com/metanorma/mn-samples-ieee-private/commit/40dfa74e509193b795d703b839bfdddbbb4aab16 . It was a problem with gitignore ignoring all PDFs.

**Comment by ronaldtse** [comment]
> The Word template ONLY provides for drafts, and I have been provided with ZERO guidance for published documents. 

Published 2830 in Word is provided as https://github.com/metanorma/mn-samples-ieee-private/blob/main/reference-docs/2830/2830-2021.doc

**Comment by opoudjis** [comment]
Published identifier is indeed "IEEE Std 2830™-2021". When the "Std" gets inserted is not clear, it seems to be left out of the relaton-fetched records.

**Comment by ronaldtse** [comment]
> When the "Std" gets inserted is not clear, it seems to be left out of the relaton-fetched records.

That is an inconsistency in the IEEE bibliographic dataset, but Relaton is supposed to now use pubid-ieee which normalizes this.

**Comment by opoudjis** [comment]
pubid-ieee provides no useful guidance on how to use it to generate an identifier. pubid-iso has the same issue, and I have been waiting three months for this to be rectified.

**Comment by ronaldtse** [comment]
@opoudjis can you file a ticket?

**Comment by opoudjis** [comment]
Pending https://github.com/metanorma/pubid-ieee/issues/71

**Comment by opoudjis** [comment]
Unblocked: https://github.com/metanorma/pubid-ieee/pull/85

**Comment by opoudjis** [comment]
Now blocked by https://github.com/metanorma/pubid-ieee/issues/87
