### ISSUE TITLE
Add document attribute for ICS description

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#113]
Source ticket: https://github.com/metanorma/mnconvert/issues/161

As titled.

Purpose: for round-trip conversion IEEE XML -> adoc -> MN XML -> IEEE XML.

Source IEEE xml:
```xml
<ics>
	<ics-code>35.040</ics-code>
	<ics-desc>Character sets and information coding</ics-desc>
</ics>
```

Expected adoc example:
`:library-ics-desc: Character sets and information coding`

**Comment by opoudjis** [comment]
`:library-ics:`, was implemented years ago.

**Comment by Intelligent2013** [comment]
@opoudjis from https://www.metanorma.org/author/ref/document-attributes/:

`:library-ics:`

 `The ICS ,,, number for the standard.`,

but I've asked about the attribute for 'description'. Or do you propose encode it so:
`:library-ics: 35.040,Character sets and information coding`?

**Comment by ronaldtse** [comment]
@Intelligent2013 we have https://github.com/metanorma/isoics that allows us to have the description of an ICS code. Metanorma can technically provide that information in the Presentational XML, right?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 we have https://github.com/metanorma/isoics that allows us to have the description of an ICS code. Metanorma can technically provide that information in the Presentational XML, right?

@ronaldtse I didn't know about this feature. Ok, It seems, yes, Metanorma can _technically_ provide it. I'll investigate how to call it.
I'll omit 'ics description' from adoc.
