### ISSUE TITLE
PDF: wrong year in the document number

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#115]
Current PDF rendering:
![image](https://user-images.githubusercontent.com/5559926/179765998-e962c520-5cc0-403b-80f4-c5971c2dae21.png)

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/179766081-98936d99-142b-49fc-a70c-9e2143fcaa23.png)

`2013` doesn't mean copyright year. It means the year from the approval date.
Original IEEE xml fragment:
```xml
			<approval>
				<approval-date date-type="approved" iso-8601-date="2013-12-11">
					<day>11</day>
					<month>December</month>
					<year>2013</year>
				</approval-date>
				<stds-body>IEEE-SA Standards Board</stds-body>
			</approval>
```

Copyright's year is using in the footer:
![image](https://user-images.githubusercontent.com/5559926/179766456-c39de7b6-9357-45d7-8a20-770319486b89.png)

I.e. year in document's number and copyright number are different for the IEEE Std 1127.

**Comment by ronaldtse** [comment]
Great find @Intelligent2013 -- do you know if it applies to Word as well?

**Comment by Intelligent2013** [comment]
> do you know if it applies to Word as well?

@ronaldtse Cover page for Word document has another layout (like draft, without year):
![image](https://user-images.githubusercontent.com/5559926/179816778-54cb04bb-c653-4541-97af-24a97f37563f.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 indeed, MN Word does not do the published layout yet.

**Comment by Intelligent2013** [comment]
Done.
