### ISSUE TITLE
Legacy standard support: Word usage clause in Overview

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#117]
Source issue: https://github.com/metanorma/mnconvert/issues/161

Source adoc:
```
= the Design, Construction, and Operation of Electric Power Substations for Community Acceptance and Environmental Compatibility
:docnumber: 1127
:docstatus: active
:copyright-year: 2014
:copyright-holder: IEEE
:published-date: 2014-01-24
:issued-date: 2013-12-11
:date: reaffirm 2000-10-30
:updates: IEEE Std 1127-1998
:semantic-metadata-related-article-edition: 2012 Edition
:language: en
:doctype: guide
:library-ics: 35.040
:committee: Substations Committee
:society: Power and Energy Society
:semantic-metadata-partner-secretariat: "Institute of Electrical and Electronics Engineers, Inc."
:keywords: A-weighted sound level, commercial zone, community involvement, hazardous material, IEEE 1127™, industrial zone, noise, permitting process, residential zone, wetlands
:semantic-metadata-xplore-article-id: 6457401
:stdid-pdf: STD98512
:stdid-print: STDPD98512
:isbn-pdf: 978-0-7381-8880-5
:isbn-print: 978-0-7381-8881-2
:mn-output-extensions: xml,html,doc,pdf,rxl
:local-cache-only:
:data-uri-image:
:imagesdir: images



[[sec1]]
== Overview

[[sec1.1]]
=== Scope

This guide identifies ...

[[sec1.2]]
=== Purpose

This guide provides ...

[[sec1.3]]
=== Organization

The guide is generally organized ...
```

In the resulted metanorma xml I see 3 sections from adoc and additional fourth section 'Word usage':
```xml
<sections>
	<clause id="sec1" type="overview" inline-header="false" obligation="normative">
		<title>Overview</title>
		<clause id="sec1.1" type="scope" inline-header="false" obligation="normative">
			<title>Scope</title>
			<p id="_">This guide identifies …​</p>
		</clause>
		<clause id="sec1.2" type="purpose" inline-header="false" obligation="normative">
			<title>Purpose</title>
			<p id="_">This guide provides …​</p>
		</clause>
		<clause id="sec1.3" inline-header="false" obligation="normative">
			<title>Organization</title>
			<p id="_">The guide is generally organized …​</p>
		</clause>
		<clause id="boilerplate_word_usage">
			<title>Word usage</title>
			<p id="_">The word <em>shall</em> indicates mandatory requirements strictly to be followed in order to conform to the standard and from which no deviation is permitted (<em>shall</em> equals <em>is required to</em>).<fn>
					<p id="_">The use of the word <em>must</em> is deprecated and cannot be used when stating mandatory requirements; <em>must</em> is used only to describe unavoidable situations.</p>
				</fn>
				<fn>
					<p id="_">The use of <em>will</em> is deprecated and cannot be used when stating mandatory requirements; <em>will</em> is only used in statements of fact.</p>
				</fn>
			</p>
			<p id="_">The word <em>should</em> indicates that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others; or that a certain course of action is preferred but not necessarily required (<em>should</em> equals <em>is recommended that</em>).</p>
			<p id="_">The word <em>may</em> is used to indicate a course of action permissible within the limits of the standard (<em>may</em> equals <em>is permitted to</em>).</p>
			<p id="_">The word <em>can</em> is used for statements of possibility and capability, whether material, physical, or causal (<em>can</em> equals <em>is able to</em>).</p>
		</clause>
	</clause>
</sections>

```

Why it appears here?

**Comment by ronaldtse** [comment]
@Intelligent2013 the new IEEE Style Manual 2021 requires the last subclause of Clause 1 Overview to be "Word Usage". Metanorma currently automatically inserts it, but we can do something to stop that behavior for documents before a certain date or through a specified option.

**Comment by opoudjis** [comment]
> Metanorma currently automatically inserts it, but we can do something to stop that behavior for documents before a certain date or through a specified option.

That's an issue that's also come up with OGC, as I've said before. 

I'd rather we not do this, and not be in the business of retrofitting, but that's a business decision. Issue moves to On Hold, pending @ronaldtse getting information to the contrary from IEEE.

**Comment by ronaldtse** [comment]
If we are to support Metanorma for IEEE officially, changes are expected in requirements in the future. The Style Manual will change. The decision now is on whether we support earlier documents.

Ideally, we should just do what we did for ISO output templates -- identify the version of the Style Manual the document follows.

e.g.

```
:document-scheme: ieee-sa-2021
```

Or something like that.

**Comment by opoudjis** [comment]
In ITU, we currently have `:legacy-do-not-insert-missing-sections:`. We will do the equivalent behaviour here as an unrecognised `document-scheme`.

You may have used `document-scheme` for ISO templates, btw, but this is the first I've heard of them for Metanorma. Rollout of this feature will be incremental.

**Comment by ronaldtse** [comment]
I think for ITU the `:legacy-do-not-insert-missing-sections:` should be subsumed into the more proper `document-scheme` in the future. This is a good idea.

**Comment by opoudjis** [comment]
> `:document-scheme`:: The document scheme that this document aligns to: Metanorma will enforce alignment
as appropriate, including by supplying predefined sections. The default document scheme for Metanorma-IEEE
is "ieee-sa-2021"; unless a different document-scheme is nominated, Metanorma will supply a Word Usage
section at the end of the Overview, will supply the built-in boilerplate as defined in 2021, and
will overwrite the Participants clause in the built-in boilerplate with user-defined Participant clauses.
In order to prevent that behaviour in legacy documents, any other value can be nominated for the document attribute,
such as "legacy".
