### ISSUE TITLE
When no "Participants" segment is defined, do not show broken layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#119]
<img width="688" alt="Screen Shot 2022-07-24 at 5 14 22 PM" src="https://user-images.githubusercontent.com/11865/180638450-45b5989c-706f-4da7-be18-1c2ceca9e725.png">

There is no need to show a half-broken layout when the Participants segment is not provided.

Especially the role names "Chair", "Vice Chair" are all arbitrarily defined by the groups, there is technically no default.

**Comment by ronaldtse** [comment]
BTW, I confirm that with the proper Participants clause is entered, the output is correct.

From P2874:
<img width="701" alt="Screen Shot 2022-07-24 at 5 19 03 PM" src="https://user-images.githubusercontent.com/11865/180638576-1d31ea56-82cd-4137-8ff2-d9ff18d87f51.png">

**Comment by opoudjis** [comment]
Disagree. When there are no participants present, we should be showing the dummy participants: that is the behaviour of the Word template. The problem currently is that the participants are in `<...>`; even with that escaped to `&lt;...&gt;`, they are being mistreated as tags.

**Comment by opoudjis** [comment]
Once again, Nokogiri .text is converting "&lt;" to "<", and needs to be preempted with HTMLEntities.encode()
