### ISSUE TITLE
Affiliation tables, PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ieee#123]
Follow-on from https://github.com/metanorma/metanorma-ieee/issues/72

![image](https://user-images.githubusercontent.com/1911039/180982792-5df253e5-6721-42ff-92cd-a86bde4f524a.png)

is to be rendered based on:

````
<p type="officeorgrepmemberhdr"><em>Organization
Represented</em><tab/><em>Name of Representative</em></p>
<p type="officeorgrepmember">Apple<tab/>John Kulick</p>
````

i.e. the initial row of the tabular presentation has `p[@type = 'officeorgrepmemberhdr']`, and the following rows with dotted tabs have `p[@type = 'officeorgrepmember']`.

Let me know if it will be easier for you to do this based on a table in Presentation XML rather than paragraphs. I'm currently starting with paras (for Word compatibility), and converting the paras to tables for HTML; I can just as easily go in the reverse direction.

**Comment by Intelligent2013** [comment]
> Let me know if it will be easier for you to do this based on a table in Presentation XML rather than paragraphs.

@opoudjis  paragraphs are ok for me. I'll just change tab in <p type="officeorgrepmember"> into multi dots. Thanks.

**Comment by Intelligent2013** [comment]
IEEE xslt updated:
![image](https://user-images.githubusercontent.com/5559926/181037878-37bf7c39-3a67-4e2d-b70d-c1a6a9ef7589.png)

@opoudjis FYI, there isn't the sentence `The Working Group gratefully acknowledges the ...` before 2nd list (3-column list) in the presentation xml.

**Comment by ronaldtse** [comment]
> there isn't the sentence `The Working Group gratefully acknowledges the ...` before 2nd list (3-column list) in the presentation xml

It is possible that this line is an arbitrary line. Can you help check the ieee-ref-docs repo to see if the application of this line is consistent?

**Comment by opoudjis** [comment]
It is an arbitrary line, and it needs to be entered explicitly in Asciidoctor, in a Participants subclause. That kind of thing is why I switched to using Participants subclause. https://www.metanorma.org/author/ieee/topics/markup/#participants
