### ISSUE TITLE
Preceded paragraphs for explanation of symbols in the formula

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#127]
Source ticket: https://github.com/metanorma/mnconvert/issues/161

Currently, the explanation of symbols in the formula marks with “where” paragraph like this:
```asciidoc
[[case5]]
== Case study 5.

If a “where” list comes after an equation

[%unnumbered]
[latexmath]
++++
\[{\text ABC} \neq {\text DEF}\]
++++

where

ABC:: = Text one

DEF:: =Text two
```
and in the semantic xml, the definition list encoded inside the element `formula` - and it's ok:
```xml
<clause id="case5" inline-header="false" obligation="normative">
	<title>Case study 5.</title>
	<p id="_">If a “where” list comes after an equation</p>
	<formula id="_" unnumbered="true">
		<stem type="MathML">
			<math xmlns="http://www.w3.org/1998/Math/MathML">
...
			</math>
		</stem>
		<dl id="_" key="true">
			<dt>CIA</dt>
			<dd>
				<p id="_">=Text one</p>
			</dd>
			<dt>DEF</dt>
			<dd>
				<p id="_">=Text two</p>
			</dd>
		</dl>
	</formula>
```

### Question 1: is there any way to put the additional paragraph before "where" like this:
```asciidoc
[[case5]]
== Case study 5.

If a “where” list comes after an equation

[%unnumbered]
[latexmath]
++++
\[{\text ABC} \neq {\text DEF}\]
++++

(A short note comes between the above eq and where statement below)

where

ABC:: = Text one

DEF:: =Text two
```

to generate xml with `p` inside `formula`?
```xml
<clause id="case5" inline-header="false" obligation="normative">
	<title>Case study 5.</title>
	<p id="_">If a “where” list comes after an equation</p>
	<formula id="_" unnumbered="true">
		<stem type="MathML">
			<math xmlns="http://www.w3.org/1998/Math/MathML">
...
			</math>
		</stem>
		<p>(A short note comes between the above eq and where statement below)</p>
		<dl id="_" key="true">
			<dt>CIA</dt>
			<dd>
				<p id="_">=Text one</p>
			</dd>
			<dt>DEF</dt>
			<dd>
				<p id="_">=Text two</p>
			</dd>
		</dl>
	</formula>
```

### Question 2: is there a way to re-define the word "where" to something else? For instance, "Otherwise":
```asciidoc
[%unnumbered]
[latexmath]
++++
\[X=Y + Z\]
++++

Otherwise

X:: = X3+X2+X

```

**Comment by opoudjis** [comment]
Currently: no to both. Of course, the "where" is populated from the i18n files, but a single value is used per language. And there is no provision at all for random discursive text embedded within a function.

I see that NISO STS allows anything in a disp-formula:

https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/element/disp-formula.html

`(#PCDATA | alt-text | long-desc | email | ext-link | uri | break | bold | fixed-case | italic | monospace | num | overline | roman | sans-serif | sc | strike | underline | ruby | inline-graphic | private-char | chem-struct | inline-formula | label | non-normative-note | normative-note | non-normative-example | normative-example | notes-group | named-content | styled-content | tex-math | mml:math | alternatives | array | code | graphic | media | preformat | sub | sup)*`

I really, really don't think we should be doing this; it's just muddled. If the discursive text is to be sequestered from the mathematical expression and the definition list, it can also be moved outside of the formula + definition list. There is already provision in Metanorma for formulas to contain notes for that reason.

As for redefining "where" as needed, yes, we could specify a "where" word as a parameter, but I would need to be convinced that it is a good idea, and I have already been made very sceptical about IEEE practice.

**Comment by opoudjis** [comment]
This is a metaguide to using NISO STS. I am very far from convinced this reflects real usage.

NISO-STS has an open-ended def-head for its definition lists, which can be populated with text other than "where". In this case, they've instead used "Where". I am not inclined to introduce markup to deal with this (as a different word than what is supplied in the i18n for the flavour), unless IEEE confirm that they do allow authors to link formulas to keys with a linker other than "where". I am not convinced this is not an error.

The sect5 instance is not even a real formula, and it certainly does not confirm to what it was describing: they say to use variable-list if the where-list immediately follows the formula, but then interpose a random sentence between the formula and the where-list. And as I already said, if random text is included in a formula, its rendering will be ruined.

I don't often say this, @Intelligent2013, but I do not want to implement this. I think the usage given is bogus; and the way we would handle such extraneous text is with a note, not with random text inside a stem block. Given the ruinous markup, I'd just convert:

````
<disp-formula
><tex-math notation="LaTeX">\[{\text CIA} \neq {\text FBI}\]</tex-math
><variable-list>
<p>(A short note comes between the above eq and where statement below)</p>
<p>where</p>
<var-item>
<term>CIA</term>
<x>=</x>
<def>
<p>Central Intelligence Agency</p>
</def>
</var-item>
<var-item>
<term>FBI</term>
<x>=</x>
<def>
<p>Federal Bureau of Investigation</p>
</def>
</var-item>
</variable-list></disp-formula>
```` 

to 

````
<formula><stem type="latex">\[{\text CIA} \neq {\text FBI}\]</stem></formula>
<p>(A short note comes between the above eq and where statement below)</p>
<p>where</p>
<dl><dt>CIA</dt><dd>Central Intelligence Agency</dd>
<dt>FBI</dt><dd>Federal Bureau of Investigation</dd></dl>
````

i.e. not even attempt to fit the paragraph + definition list within the formula. This is an artificial example, and I don't think we should be breaking our rendering of formulas for an artificial example.

**Comment by opoudjis** [comment]
The equal signs are bogus for our definition lists as well. This is an artefact of rendering, it belongs in Presentation XML, not our Semantic XML. And the rendering proposed violates the IEEE Style Manual:

<img width="810" alt="Στιγμιότυπο 2022-08-10, 23 21 23" src="https://user-images.githubusercontent.com/1911039/183912061-c942b7e7-59b4-4ac7-9ee7-795fa2549de4.png">

I do not think we should be doing any of this.

**Comment by ronaldtse** [comment]
Just a note that IEEE XML is **NOT** NISO STS. I'll read the rest...

**Comment by ronaldtse** [comment]
> I don't have the real PDF document, only the source xml with such special cases: https://github.com/metanorma/mn-samples-ieee-private/blob/main/reference-docs/1127/master-1-standard.xml

@Intelligent2013 the document is now provided here: https://github.com/metanorma/mn-samples-ieee-private/tree/main/reference-docs/1127

**Comment by Intelligent2013** [comment]
> @Intelligent2013 the PDF document is now provided here: https://github.com/metanorma/mn-samples-ieee-private/tree/main/reference-docs/1127

@ronaldtse yes, it's right. BUT the xml instance `master-1-standard.xml` has an extra information at the end of `body` section after the comment `<!--20141020: the following secs are added for special cases-->`: 
```xml
<sec id="sec1.stdstaff">
<title>Case-study 1: text in color</title>
...
<sec id="sec2-pg97a">
<title>Case-study 2: From the case-study-2.pdf, pg 97</title>
...
<sec id="sec2-pg97b">
<title>Case-study 3: From the case-study-2.pdf, pg 105</title>
...
<sec id="sec2-pg135">
<title>Case-study 4: From the case-study-2.pdf, pg 135</title>
...
<sec id="case5">
<title>Case study 5: Use variable-list in the case where the initial equation is followed immediately by the &#x201c;where&#x201d; list. Note that operator symbol is tagged inside &#x201c;x&#x201d; element if needed.</title>
...
<sec id="case6">
<title>Case study 6: If the &#x201c;where&#x201d; statement does not immediately follow an equation, do not use variable-list. Just use def-list as follows. Note that the DTD does not allow variable-list outside of disp-formula. Using variable-list without a display equation is poor tagging.</title>
```

**Comment by opoudjis** [comment]
These are sample text instructions for editors on how to handle XML authoring by using templates, and it is not clear that the formulas they contain correspond to genuine usage; nor are they rendered in the PDF. We will not implement either issue, and will revisit only if this usage turns up in real documents. Ignore case study 5 and 6 for the purposes of conversion to Metanorma.

**Comment by ronaldtse** [comment]
As mentioned by @opoudjis , we found these case studies to be "template instructions" for IEEE SA editors to copy/paste in certain editing cases.

Let's skip Case Study 5 and 6 for now until we hit a real document with these needs.

**Comment by Intelligent2013** [comment]
@opoudjis @ronaldtse thanks!
