### ISSUE TITLE
Support attributes for document type: Whitepaper and ICAP

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#13]
Source: https://github.com/metanorma/metanorma-ieee/issues/9 and https://github.com/metanorma/metanorma-ieee/issues/10

Add these attributes:

- Authored by (Firstname, Lastname, Title):
![image](https://user-images.githubusercontent.com/5559926/174485295-bb2cd24a-cd07-4e9a-9741-aae7fbab7f48.png)

- Program title:
![image](https://user-images.githubusercontent.com/5559926/174485328-e8638551-c27a-44c2-9161-a11236ca6ef3.png)

**Comment by opoudjis** [comment]
> Authored by (Firstname, Lastname, Title):

These are simply the generic attributes of a personal author: 

````
:surname: X
:givenname: Y
:role: Z
:surname_2: X1
:givenname_2: Y1
:role_2: Z1
````

> Program title:

Adding this as /bibdata/ext/program, encoding as document attribute `:program:`

**Comment by opoudjis** [comment]
Document header:

````
= Paper Title
A
:no-pdf:
:doctype: whitepaper
:program: Program Title
:surname: X
:givenname: Y
:contributor-position: Z
:surname_2: X1
:givenname_2: Y1
:contributor-position_2: Z1
:reviewers: Reviewer Name1,Rev iewerName2
:isbn-pdf: ISBN 2
:isbn-print: ISBN 3
:stdid-pdf: STD 2
:stdid-print: STD 3
:issued-date: 2929
:copyright-year: 2020
:working-group: NAME OF GROUP
:program: NAME OF PROGRAM
````

is resulting in Word title page:

![Uploading Screenshot 2023-11-19 at 02.01.52.png…]()

**Comment by Intelligent2013** [comment]
@opoudjis for adoc:
```adoc
:program: Program Title
```
the Presentation XML contains `NAME OF PROGRAM` (instead of `PROGRAM TITLE`):
```xml
      <program>NAME OF PROGRAM</program>
    </ext>
  </bibdata>
```

My `Gemfile` is:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "sassc"
gem "metanorma-ieee", git: "https://github.com/metanorma/metanorma-ieee", branch: "main"
```
What did I do wrong?

**Comment by opoudjis** [comment]
@Intelligent2013 My bad: the adoc I supplied included the `:program:` document attribute twice, and Metanorma is using the later instance which overwrites the former. If you delete the latter and regenerate, you should be ok.
