### ISSUE TITLE
Use correct IEEE SA XML tag for "Acronyms and abbreviations"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#130]
There isn't one approach in the representation of `Acronyms and abbreviations`:
- in master-2-standards-distribution.xml - the element `std-def-list` is using:
```xml
<sec id="sec3.2">
	<label>3.2</label>
	<title>Acronyms and abbreviations</title>
	<std-def-list>
		<std-def-list-item>
			<term>ATE</term>
			<def>
				<p>automatic test equipment</p>
			</def>
		</std-def-list-item>
```

- in 2830-2021.xml - the element `def-list` is using:
```xml
<sec id="sec3.2">
	<label>3.2</label>
	<title>Acronyms and abbreviations</title>
	<def-list>
		<def-item>
			<term>API</term>
			<def>
				<p>application programming interface</p>
			</def>
		</def-item>
```

Currently, mnconvert uses 1st approach.

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mnconvert/issues/161#issuecomment-1213236558_

**Comment by ronaldtse** [comment]
I have sought confirmation from IEEE SA.

**Comment by ronaldtse** [comment]
From Patrick Gibbons of IEEE SA:

Always use `<def-list>` for acronyms and abbreviations.

**Comment by Intelligent2013** [comment]
@ronaldtse thank you.
I've understood why IEEE uses `std-def-list`. In the `master-2-standards-distribution.xml` there is an fragment with `editing-instruction`:
```xml
<std-def-list>
	<editing-instruction>
		<p>This instruction is for the whole list</p>
	</editing-instruction>
	<std-def-list-item>
		<editing-instruction>
			<p>This instruction is only for this item.</p>
		</editing-instruction>
		<term>ATE</term>
		<def>
			<p>automatic test equipment</p>
		</def>
	</std-def-list-item>
```
where `editing-instruction` is using at _list item_ level. The IEEE DTD doesn't support `editing-instruction` in `def-item`, so this fragment:

```xml
<def-list>
	<editing-instruction>
		<p>This instruction is for the whole list</p>
	</editing-instruction>
	<def-item>
		<editing-instruction>
			<p>This instruction is only for this item.</p>
		</editing-instruction>
		<term>ATE</term>
		<def>
			<p>automatic test equipment</p>
		</def>
	</def-item>
```
isn't valid against IEEE DTD.
Note: `editing-instruction` is allowed as child of `def-list`.

So, for 

> Always use `<def-list>` for acronyms and abbreviations.

XSLT will move the element `editing-instruction` inside `def/non-normative-note`:
```xml
<def-list>
	<editing-instruction>
		<p>This instruction is for the whole list</p>
	</editing-instruction>
	<def-item id="symbol-ATE">
		<term>ATE</term>
		<def>
			<p>automatic test equipment</p>
			<non-normative-note>
				<editing-instruction>
					<p>This instruction is only for this item.</p>
				</editing-instruction>
			</non-normative-note>
		</def>
	</def-item>
```

**Comment by Intelligent2013** [comment]
Done.
