### ISSUE TITLE
Definitions clause when to use individual numbering?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#131]
There is difference in definitions numbering between master-1-standard.pdf  (without numbering):
![image](https://user-images.githubusercontent.com/5559926/183249731-934771cf-d479-4bf3-af0d-f04fa9d7b466.png)

and master-2-standard.pdf  (with numbering):
![image](https://user-images.githubusercontent.com/5559926/183249760-160c4ff1-7ab7-45fa-acd9-319aad8b42c4.png)

Currently, mnconvert doesn't put numbers into mn semantic xml->IEEE xml conversion.

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mnconvert/issues/161#issuecomment-1207210162_

**Comment by ronaldtse** [comment]
I have sought IEEE SA for clarification.

**Comment by ronaldtse** [comment]
From Patrick Gibbons of IEEE SA:

> We don't number definitions anymore.

**Comment by Intelligent2013** [comment]
@ronaldtse thanks!

No need any changes in mnconvert.
