### ISSUE TITLE
Difference in the ICS description

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#135]
The source IEEE XML contains the description `Character sets and information coding` for ICS code `35.040`:
```xml
<ics>
  <ics-code>35.040</ics-code>
  <ics-desc>Character sets and information coding</ics-desc>
</ics>
```

but the mapping table `https://github.com/metanorma/isoics/blob/master/ics/35_040.json` contains `Information coding`. Similar to ISO website https://www.iso.org/ics/35.040/x/:
![image](https://user-images.githubusercontent.com/5559926/184669240-7e2252dd-107f-4c13-b18c-16513931ee49.png)

Looks like IEEE uses some another mapping table, for instance https://www.en-standard.eu/bs-standards/35-information-technology-office-machines/35-040-character-sets-and-information-coding/:
![image](https://user-images.githubusercontent.com/5559926/184669534-6994f2aa-f63f-423a-b4ab-7e3f08fa7aa6.png)

@ronaldtse should we do anything here?

**Comment by ronaldtse** [comment]
The reason is that our ICS codes are from Edition 7. IEEE's ICS codes are Edition 6. I found a PDF of the 6th edition: 
https://www.academia.edu/34296973/ICS_ISO_Ed_6_2005_en and it contains this:
<img width="453" alt="Screen Shot 2022-08-25 at 5 46 19 PM" src="https://user-images.githubusercontent.com/11865/186632932-9b3b2df3-79da-4b97-a63c-f85eb1156583.png">

I think we can safely use the new codes, but we may need to transcribe the 6th edition and supplement our information.

**Comment by ronaldtse** [comment]
From IEEE SA, Patrick Gibbons:

> They are not needed.

Technically we can omit the `<ics...>` elements in the IEEE SA XML output.

I'd say we just use the ICS Edition 7 codes for consistency reasons.

**Comment by Intelligent2013** [comment]
@ronaldtse thank you for the clarification.
currently, the 'ics' information is converting so:
- IEEE SA XML to Metanorma AsciiDoc: mnconvert converts ics code only,
- Metanorma XML: metanorma-ieee gem generates ics code from AsciiDoc and description (by using 'isoics' gem)
- Metanorma XML to IEEE SA XML: mnconvert converts ics code and description.

> Technically we can omit the <ics...> elements in the IEEE SA XML output.

> I'd say we just use the ICS Edition 7 codes for consistency reasons.

I see a few options:
- remove ics description only
- remove ics at all
- just add the information into IEEE SA XML vs. Metanorma XML mapping documentation that we use ICS Edition 7.

**Comment by Intelligent2013** [comment]
Currently:
> Metanorma XML to IEEE SA XML: mnconvert converts ics code and description.

Ticket will be re-opened if we need changes.
