### ISSUE TITLE
XSLT module naming

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#14]
I develop one XSLT module for all document types (standard, whitepaper, ICAP whitepaper, industry connection report, draft standard).

Which filenames for xslt modules do you expect in metanorma-ieee?

For instance, currently for ITU we have a few xslt (but really they are identical):
itu.implementers-guide.xsl
itu.in-force.xsl
itu.recommendation-annex.xsl
itu.recommendation-supplement.xsl
itu.recommendation.xsl
itu.resolution.xsl
itu.service-publication.xsl
itu.technical-paper.xsl
itu.technical-report.xsl

**Comment by opoudjis** [comment]
Actually, I haven't dug deep enough, but right now, I expect only two:

ieee.standard
ieee.amendment
