### ISSUE TITLE
Word: Introduction layout split into 3 columns

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#143]
As reported by @cperey: 
* https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/208

> I opened the Word version of the P2874 D2 (just what's generated as part of the site.zip package) and found that beginning of the text (see screenshot) it is in 3-column format. 
> 
> <img width="583" alt="Screen Shot 2022-09-14 at 1 06 44 PM" src="https://user-images.githubusercontent.com/5149991/190138608-3c9c8737-9add-4f31-b3e4-c26d1ff79ef7.png">
> 
> Can this be made single column?

This seems to be a regression, as we have encountered this before but was fixed (https://github.com/metanorma/metanorma-ieee/issues/121)

**Comment by opoudjis** [comment]
This is difficult, because of the need to put section definitions in CSS. I was relying on the preface being policed, but I'm going to try making the section numbers non-sequential.

**Comment by opoudjis** [comment]
@cperey Fixed, although you won't be able to see the result until next release (next Monday). I can mail you the new document if you like.
