### ISSUE TITLE
PDF: Formatting issues with bibliographic items

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#160]
The bibliographic items are not rendered properly:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/11865/198926812-4e59d04a-c933-4c1e-b19c-a496735984cb.png">

The relevant code is at: https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

**Comment by Intelligent2013** [comment]
IEEE XSLT updated: comma added after document identifier:
![image](https://user-images.githubusercontent.com/5559926/198984984-2f2a410c-9a85-4028-848f-b595de3de01e.png)

- the text in the brackets are hard-coded in presentation XML:
```xml
<bibitem id="dtdl">
<formattedref format="application/x-isodoc+xml">Digital Twins Definition Language (DTDL) [Digital Twins] </formattedref>
<docidentifier>Digital Twins</docidentifier>
</bibitem>
```

- the hyperlink renders without indent due missed space in the presentation XML. I'll raise the issue.
![image](https://user-images.githubusercontent.com/5559926/198985846-81f71b87-1818-4d2d-80ed-299cc421af1d.png)

```xml
<bibitem id="mozilla">
<formattedref format="application/x-isodoc+xml">Mozilla, Fundamentals of Web XR<link target="https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals"/> [Mozilla Web XR] </formattedref>
<title>Fundamentals of Web XR</title>
```

**Comment by Intelligent2013** [comment]
> - the text in the brackets are hard-coded in presentation XML:
> ```xml
> <bibitem id="dtdl">
> <formattedref format="application/x-isodoc+xml">Digital Twins Definition Language (DTDL) [Digital Twins] </formattedref>
> <docidentifier>Digital Twins</docidentifier>
> </bibitem>
> ```

@ronaldtse should we omit the text in brackets?

**Comment by ronaldtse** [comment]
@Intelligent2013 the text in brackets is a bug to be dealt with, which should have been fixed in:
* https://github.com/metanorma/metanorma-iso/issues/818

The relevant PR is:
* https://github.com/metanorma/isodoc/pull/445

@opoudjis is this fixed?

**Comment by opoudjis** [comment]
Yes.

**Comment by ronaldtse** [comment]
From @opoudjis 
> Yes, it is fixed, it was 5 days ago and therefore not in release

**Comment by Intelligent2013** [comment]
Confirm. After `gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"` in Gemfile:
![image](https://user-images.githubusercontent.com/5559926/199009428-62f95358-44bf-4c65-9e71-8575b4f9c947.png)

**Comment by Intelligent2013** [comment]
PDF rendering with latest isodoc update:

![image](https://user-images.githubusercontent.com/5559926/199097734-6b5c95ff-224f-4b01-b13b-9ae9d5f883cd.png)

**Comment by ronaldtse** [comment]
Confirmed, closing.
