### ISSUE TITLE
Word (draft): Footnote number 1 missing but 2 present

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#17]
<img width="703" alt="Screenshot 2022-06-20 at 6 54 06 AM" src="https://user-images.githubusercontent.com/11865/174501800-6ff60783-b1bf-40e2-95d5-21298d22eced.png">

**Comment by opoudjis** [comment]
Can't replicate, assume to have gone away.
<img width="826" alt="Στιγμιότυπο 2022-06-28, 21 33 56" src="https://user-images.githubusercontent.com/1911039/176168853-f75d47d0-4420-404b-afbe-913614f109f3.png">

**Comment by ronaldtse** [comment]
Confirmed fixed. Thanks! <img width="832" alt="Screenshot 2022-06-29 at 1 35 46 AM" src="https://user-images.githubusercontent.com/11865/176233463-5fd94af9-1503-43d2-af2e-2670200c0eb8.png">
