### ISSUE TITLE
Term rendering with concept mentions broken in style, instead of issuing warning of missing reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#170]
Notice how the "scene graph" term has its definition messed up. 

<img width="946" alt="Screen Shot 2022-11-11 at 5 51 29 PM" src="https://user-images.githubusercontent.com/11865/201314449-4735c97a-a8c6-456b-b258-f5d99b6c8661.png">

```adoc
==== scene graph

Encoded graph that contain information about {{scene,scenes}}, {{hyperspace asset,assets}}, {{authority,authorities}} and {{action,actions}}.


==== scene graph server

Server that contains primary and subordinate {{scene graph,scene graphs}}.

NOTE: Different servers may contain different parts of the same scene (for instance, the Earth scene, which hosts any form of augmented reality scenes, has potentially millions of scenes broken down by nested geopolitical regions or corporate environments). Unmoored scenes (such as those associated with game or simulation worlds that aren't based on real Earth location) may be similarly segmented.

related:seealso[scene graph]
```

**Comment by opoudjis** [comment]
The bug involves four cross references. You have not provided any of them. I therefore cannot debug this.

This issue will be ignored until you provide the source document. Your ongoing failure to provide sufficient information for actionable issues is going to continue to get the same response.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

Check it here.

**Comment by ronaldtse** [comment]
I forgot to mention that PDF layout works perfectly.

**Comment by opoudjis** [comment]
There is no such term as "hyperspace asset".

````
AsciiDoc Input: (XML Line 000794): Error: Term reference to `hyperspace-asset` missing: "hyperspace-asset" is not defined in document
````

**Comment by opoudjis** [comment]
We should break rendering, as with Standoc:

````
Error: Term reference to `#{target}` missing: "#{target}" is not defined in document
````

Need to establish why this isn't happening in IEEE.

**Comment by opoudjis** [comment]
This is happening because we left it open when a term is not cited in an IEEE document, that it might be cited from the IEEE online dictionary. So in fact, the rendering should not be mangled like this after all.

**Comment by opoudjis** [comment]
No, changed my mind again. Those pending definitions to external and absent terms are legit.

**Comment by opoudjis** [comment]
Removed redundant spaces from the wrong place. They are being introduced in termdefinition processing.

**Comment by opoudjis** [comment]
to_xml needs Nokogiri::XML::Node::SaveOptions::AS_XML a lot more, to prevent XML from being rendered with carriage returns between tags.

**Comment by opoudjis** [comment]
<img width="689" alt="Στιγμιότυπο 2022-11-22, 23 47 31" src="https://user-images.githubusercontent.com/1911039/203317756-e1e0e690-fc5b-4a2b-b535-5302fa33963c.png">
