### ISSUE TITLE
(URGENT) PDF: Cross-references within document not showing up in correct style (no blue link)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#177]
This is reported by @cperey -- thank you!

Given this source:
```adoc
Included in this tier are the servers hosting <<section-spatial-dns, the Spatial DNS registries>>. 
...

[[section-spatial-dns]]
== Spatial DNS
...
```

Word (correct):
<img width="440" alt="Screen Shot 2022-11-15 at 12 24 05 PM" src="https://user-images.githubusercontent.com/11865/201825921-3a65d486-696d-49cd-a954-beff75bcb416.png">

PDF (missing link style):
<img width="485" alt="Screen Shot 2022-11-15 at 12 24 31 PM" src="https://user-images.githubusercontent.com/11865/201825983-74c33b93-2711-4c25-aa35-6efcd6737bba.png">

In PDF, when I hover and click the link works. However it's just not styled properly.
<img width="565" alt="Screen Shot 2022-11-15 at 12 25 04 PM" src="https://user-images.githubusercontent.com/11865/201826073-5f82f8f1-184d-4829-bb2d-438a9c6a7181.png">

The document is:
* https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/201906730-eeed66a3-b1f9-4c60-9da7-01f5838ed8bb.png)

**Comment by ronaldtse** [comment]
Confirm fixed. Thank you @Intelligent2013 !

<img width="368" alt="image" src="https://user-images.githubusercontent.com/11865/202367394-54d08f36-9635-4d6b-9d1e-a7d9805c58c6.png">

**Comment by ronaldtse** [comment]
FYI @cperey @prasaanth-verses @ReesePlews

**Comment by cperey** [comment]
Thank you!
