### ISSUE TITLE
Word (draft): Footnotes should use "IEEEStds Footnote" style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#18]
Template:
<img width="1217" alt="Screenshot 2022-06-20 at 6 55 47 AM" src="https://user-images.githubusercontent.com/11865/174501854-c905395a-2ca0-4ce7-8f0b-e8d632ede074.png">

Generated:
<img width="1216" alt="Screenshot 2022-06-20 at 6 56 24 AM" src="https://user-images.githubusercontent.com/11865/174501868-632de128-684b-409f-9527-9a55d41ec2a9.png">

**Comment by opoudjis** [comment]
Has already been done.

Yet another prematurely lodged ticket. The micromanagement remains unwelcome.
