### ISSUE TITLE
Bibliographic references encoded with `span:date` showing as "n.d."

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#186]
Reported by @ReesePlews.

Relevant document:
https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

The syntax is correct as per documentation:
https://www.metanorma.org/author/topics/document-format/bibliography/

Example 11:
```adoc
* [[[A, B]]],
  span:surname[Wozniak], span:initials[S.] & span:givenname[Steve] span:surname[Jobs].
  span:date.issued[1991].
  span:date[1996].
  span:title[_Work_].
  In span:in_surname.editor[Gates], span:in_initials.editor[W. H] &
  span:in_organization[UNICEF],
  span:in_title[Collected Essays].
  _span:series[Bibliographers Anonymous]._
  span:docid.ISO[ISO 1234].
  span:pubplace[Geneva]:
  span:publisher[International Standardization Organization].
  span:uri.citation[http://www.example.com].
  vol. span:volume[5],
  pp. span:pages[2-21]
  span:type[inbook]
```

Relevant snippets:

```adoc
* [[[hedman,1]]],
span:initials[A.], span:surname[Hedman], span:name[et al.]
span:title[IEA EBC Annex83 Positive Energy Districts].
span:type[inproceedings]
In: span:in_title[Buildings].
vol. span:volume[11],
issue. span:issue[3],
pp. span:pages[130].
span:date[2021].
doi: span:uri.doi[10.3390/buildings11030130].
```
<img width="648" alt="Screen Shot 2022-11-29 at 10 47 32 PM" src="https://user-images.githubusercontent.com/11865/204560571-d6025175-4498-4357-9981-62456c9bcb79.png">

```adoc
* [[[iot_vocab,1]]],
span:organization[Industry IoT Consortium].
span:type[booklet]
span:title[Industry Internet of Things Vocabulary].
span:version[Version 3.00].
span:date[2022-03-22].
```

<img width="524" alt="Screen Shot 2022-11-29 at 10 47 56 PM" src="https://user-images.githubusercontent.com/11865/204560691-7796e43a-eb7d-4ff2-aff8-2d67034dca4f.png">

**Comment by opoudjis** [comment]
My bug in preprocessing dates.

**Comment by ReesePlews** [comment]
@opoudjis thank you for fixing this. it will be rendering correctly now, or in a couple of days/weeks?

**Comment by opoudjis** [comment]
Next release, so in a week

**Comment by ReesePlews** [comment]
understood, thank you @opoudjis
