### ISSUE TITLE
Rendering of W3C references should come with document type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#187]
Reported by @ReesePlews.

Relevant document:
https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

Relevant snippets:
```adoc
* [[[w3c_owl,W3C owl-time]]], W3C Time Ontology in OWL

* [[[w3c_rdf,W3C rdf-concepts]]], W3C Resource Description Framework (RDF link) (and QB4St link)

* [[[w3c_skos,W3C skos-reference]]], Simple Knowledge Organization System
```

<img width="644" alt="Screen Shot 2022-11-29 at 10 53 35 PM" src="https://user-images.githubusercontent.com/11865/204562123-3d1b7b29-8ca9-4f03-9592-37c4f01336da.png">

"W3C owl-time" should be rendered with the proper document status:
https://www.w3.org/TR/owl-time/
<img width="802" alt="Screen Shot 2022-11-29 at 10 54 44 PM" src="https://user-images.githubusercontent.com/11865/204562408-13eaa149-711e-4d18-8ef3-6288b6513546.png">

It is a "W3C Candidate Recommendation Draft 15".

While I don't have the proper citation format for W3C, it's probably reasonable to have something like this:
* "Cox, S., Little, C. _Time Ontology in OWL_. W3C Candidate Recommendation Draft 15. Available at: https://www.w3.org/TR/owl-time/"

**Comment by ronaldtse** [comment]
This issue also happens in metanorma-iso.

**Comment by ronaldtse** [comment]
This is rather problematic in ISO 19115-3:
<img width="706" alt="Screen Shot 2022-12-09 at 12 17 03 AM" src="https://user-images.githubusercontent.com/11865/206502123-1fd6591d-12d9-428d-b4de-f4d90ca55e40.png">

**Comment by opoudjis** [comment]
To implement this as requested, with these documents still treated as standards as they are now, would be inconsistent with established practice. What is the principled reason for us to add status and authors and URIs to W3C documents on bibliographies, and not ISO documents as well?

Moreover, relaton-w3c currently does not contain either authors (at all), or dates (they are merged into the document identifiers), or status (at all): work would have to be done to realise such a rendering, and I have no idea if the SPARQL endpoint we are fetching information from contains this information.

So I cannot progress this without further discussion. An indiscriminate implementation of this would compromise the rendering of ISO and IEEE standards themselves in bibliographies, and we need to work out a principled approach here (assuming W3C even publishes the information requested). There are several options:

* The cleaner option: these are not standards, and we need to mark them up in relaton-w3c as something else, e.g. techreport or booklet. If we do, though, we need a principled reason why these are not standards, which can be applied to other document classes fetched by relaton. I am having trouble seeing any such reason that doesn't also apply to IETF.
* The messier option: we continue to call these standards, but we allow different rendering for different kinds of standard: ISO standards are rendered with designator and title alone, but W3C standards must also have author and status and URI; and that information, if present in an ISO record, must be ignored. On the face of it, that is what is being asked for here. 
  * relaton-render follows ISO 690, and all known bibliographic software, in having rendering determined by bibliographic class, and this would run counter to that.
  *  And of course such an approach would on the face of it violate the formatting of standards outlined in IEEE SA Style Manual §19.2 and  ISO/IEC DIR 2 §10.3 (although the wording is more vague there)

**Comment by opoudjis** [comment]
I've come up with a third option, which is intermediate between the two, and which I am comfortable with, because it is well-motivated semantically.

SDOs like ISO have a notion of "home" standards, SDOs that they are intimately familiar with. Standards citations for home standards can be truncated to the extent of just identifier and title. Less familiar SDOs require fuller information.

My strong preference is that the home SDO for an SDO be itself. In the case of ISO, we can allow IEC along ISO, since they are joined at the hip procedurally.

That means that ISO references to ISO documents can be highly truncated, but also that ISO references to W3C are not.

But that has to be the barrier. We cannot treat IETF and W3C any differently, that is irrational. I'll go further and say, we can't treat W3C and BSI or NIST differently either, we can't make national SDOs home standards. (After all, why BSI and not ELOT or SIST?)

(Did you have to look last two those up? Good. *You've just proven my point*.)

**Comment by opoudjis** [comment]
In addition, if we are displaying status for non-home standards in ISO, we need not to display status for published standards. That means we need a cross-SDO flag for draft status of a standard, which we do not currently have in relaton.

**Comment by ReesePlews** [comment]
hello @opoudjis for these updates that have been added, where can i find the current list of bibliography span codes. i think after this update the IEEE document is not generating correctly and it may be due to some old span codes in my bibliography. i can fix those if you show me a list of the codes or point me to the documentation if that is current. thank you.

**Comment by ronaldtse** [comment]
@ReesePlews the changes have not been implemented for this ticket yet. 

@opoudjis as we have agreed, we will implement the notion of a "home entity" where if a citation is published by the same entity (or a list of designated "home entities"), an alternative format can be used (as defined in the Metanorma flavor).

In the case of W3C, we still need to provide the details. In this case, the citation of the W3C Recommendation can be:
* "W3C. Candidate Recommendation Draft 15: Time Ontology in OWL."
* (NOTE: remember that W3C decided not to provide contributor names in their machine-readable references due to privacy concerns)

**Comment by ReesePlews** [comment]
@ronaldtse thank you  for the clarification. i thought this was related to the IETF/W3C/OGC entries in the bibliography and the recent generate errors that appeared to be happening at that location. but if this has not been implemented, then it is not related  and i can then i can change them back in my test branch.  thank you for the clarification.

**Comment by opoudjis** [comment]
> "W3C. Candidate Recommendation Draft 15: Time Ontology in OWL.

Abbreviation, status: title?

That's random, and I'm not going to be doing random, unmotivatived, idiosyncratic rendering that only makes sense for one SDO. In particular, "status: title" is going to be nonsense for almost all SDOs (_Committee Draft: Time Ontology in OWL_). Do NOT be misled by the "15": this is not a series, the "15" is a snippet of the update date.

As I already said, that "Candidate Recommendation Draft" string isn't even in relaton-w3c right now:

````
<bibdata type="standard" schema-version="v1.2.1">
  <fetched>2022-12-22</fetched>
  <title format="text/plain">Time Ontology in OWL</title>
  <uri type="src">https://www.w3.org/TR/owl-time/</uri>
  <docidentifier type="W3C" primary="true">W3C owl-time</docidentifier>
  <docnumber>owl-time</docnumber>
  <language>en</language>
  <script>Latn</script>
  <status>
    <stage>recommendation</stage>
  </status>
  <relation type="hasEdition">
    <bibitem>
      <formattedref format="text/plain">W3C REC-owl-time-20171019</formattedref>
      <docidentifier type="W3C" primary="true">W3C REC-owl-time-20171019</docidentifier>
    </bibitem>
  </relation>
  <relation type="instance">
    <bibitem>
      <formattedref format="text/plain">W3C CRD-owl-time-20221115</formattedref>
      <docidentifier type="W3C" primary="true">W3C CRD-owl-time-20221115</docidentifier>
    </bibitem>
  </relation>
  <relation type="hasEdition">
    <bibitem>
      <formattedref format="text/plain">W3C WD-owl-time-20060927</formattedref>
      <docidentifier type="W3C" primary="true">W3C WD-owl-time-20060927</docidentifier>
    </bibitem>
  </relation>
  <relation type="hasEdition">
    <bibitem>
      <formattedref format="text/plain">W3C CR-owl-time-20200326</formattedref>
      <docidentifier type="W3C" primary="true">W3C CR-owl-time-20200326</docidentifier>
    </bibitem>
  </relation>
  <relation type="hasEdition">
    <bibitem>
      <formattedref format="text/plain">W3C WD-owl-time-20160712</formattedref>
      <docidentifier type="W3C" primary="true">W3C WD-owl-time-20160712</docidentifier>
    </bibitem>
  </relation>
  <series>
    <title format="text/plain">W3C REC</title>
    <number>owl-time</number>
  </series>
  <ext schema-version="v1.0.0">
    <doctype>technicalReport</doctype>
  </ext>
</bibdata>
```` 

And neither are there explicit dates extracted.

In the templates for ISO and IEEE, I am allowing for:

* Authors
* Title
* Extent
* Edition
* Date updated
* Status
* Place
* Authorizer/Publisher 
* URL

Based on what *is* in there, what you're getting for the non-home standards in ISO, based on how I've currently implemented this, is:

`<formattedref><em><span class="stddocTitle">Character Sets</span></em>. Updated July 14, 2022. Internet Assigned Numbers Authority. Available from: <span class="biburl"><link target="http://www.iana.org/assignments/character-sets">http://www.iana.org/assignments/character-sets</link></span>.</formattedref>`

`<formattedref><em><span class='stddocTitle'>Time Ontology in OWL</span></em>. Recommendation. Available from: <span class='biburl'><link target='https://www.w3.org/TR/owl-time/'>https://www.w3.org/TR/owl-time/</link></span>.</formattedref>`

`formattedref><smallcap>R. Fielding, J. Gettys, J. Mogul, H. Frystyk, L. Masinter, P. Leach, & T. Berners-Lee</smallcap>. <em><span class="stddocTitle">Hypertext Transfer Protocol — HTTP/1.1</span></em>. Fremont, CA: RFC Series. Available from: <span class="biburl"><link target="https://www.rfc-editor.org/info/rfc2616">https://www.rfc-editor.org/info/rfc2616</link></span>.</formattedref>`

I don't want to get into games of "include publisher for these standards and not for those". "Internet Assigned Numbers Authority" should indeed be spelled out for a non-home standard, and the only reason it isn't for W3C is, we don't have decent publisher/authorizer metadata in there yet.

**Comment by opoudjis** [comment]
I am adding authorizer to relaton-renderer, we will use that for standards since it can be distinct from publisher (and it will be  populated with the publisher absent a distinct authorizer)

**Comment by ReesePlews** [comment]
@opoudjis thank you for the discussion. i am really new to these things (metanorma, github ascii doc) so a lot of this information is quite beyond my understanding now. parts of the bibliography i was working on were already in place before i picked it up and from there i used the metanorma documentation to fill in the rest of the entries. the connection of relaton to metanoma and the bib entries is not so clear. none of my code looks anything like what you have shown (xml?) above.  when the generate of the document fails it is very difficult to get a clear understanding of what may be wrong and where in the file.  perhaps that is just the nature of the various languages used for development.  if you could direct me in the documentation to a complete list of options for the values of the "span" constructs that would be helpful.  thank you again for taking time to describe these issues. it will take me more time to pick up how to better work with these tools.

**Comment by opoudjis** [comment]
The full list of what is currently supported in the span notation is:

https://www.metanorma.org/author/topics/document-format/bibliography/#annotated-spans

You've actually been doing a good job of abiding by these, and this is recently implemented functionality, that we are still finding bugs in. 

The workflow for Metanorma is: Asciidoctor > Semantic Metanorma XML + Relaton XML > Presentation Metanorma XML > HTML, PDF, DOC. 

The Relaton XML is fetched from bibliographic databases for standards that match the document identifier you provide, so of course you don't see it, it happens behind the scenes. The XML I have above is what is fetched on lookup of the identifier `W3C owl-time`.

As you can see from that XML, we have the title and URI of the standard, which we retrieve from W3C, but we do not have the authors (W3C is declining to make that information retrievable from its database, I gather), and we do not have status information.

In the version of Metanorma I released yesterday, I have implemented the ability to supplement a Relaton fetched citation with bibliographic spans. So information can be added on top of an automatically fetched reference:

````
* [[[w3c_owl,W3C owl-time]]], span:surname[Cox] span:initials[S.] span:surname[Little] span:initials[C.]
````

I haven't implemented `span:status[]`, but if we determine that is necessary for standards, I can implement it.

**Comment by ReesePlews** [comment]
@opoudjis thank you for the details and the link to the information about span notation.  that will be most helpful. i will check the render when the new version is released. thank you for spending time to work on this so close to the holiday.
