### ISSUE TITLE
Word (draft): Missing Introduction "uncaptioned warning"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#19]
Template:
<img width="1149" alt="Screenshot 2022-06-20 at 6 58 02 AM" src="https://user-images.githubusercontent.com/11865/174501915-6e14b9eb-b9b1-4459-8c72-91d7bc5c8107.png">
<img width="1150" alt="Screenshot 2022-06-20 at 6 58 11 AM" src="https://user-images.githubusercontent.com/11865/174501918-f3227421-44b1-431f-9617-ef3568da738e.png">

Generated:
No Introduction?

**Comment by opoudjis** [comment]
Since

````


== Introduction

This is an introduction
````

now generates

<img width="784" alt="Στιγμιότυπο 2022-06-24, 01 26 38" src="https://user-images.githubusercontent.com/1911039/175336509-d6e1fe98-1353-4c05-b976-c674c390104d.png">

This ticket is premature, peremptory, unwelcome, redundant, and closed.
