### ISSUE TITLE
(URGENT) When outputs are broken, do not return success code

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#194]
From https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/pull/509#pullrequestreview-1208442721

This document is forked into here for our team to debug:
* https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/pull/18 

@prasaanth-verses:

> This PR is not generating the PDF, doc, and HTML outputs when I download the draft. This is usually the case when there is a syntax error. I'm not sure why things are passing and why the error isn't displayed in the pipeline.
>
> any recommendations on how to deduce why there was nothing generated?

@CAMOBAP can you please help investigate how we can force errors to show up in GitHub Actions when any error occurs?

**Comment by CAMOBAP** [comment]
@ronaldtse I suppose we prepared `--strict` mode in `metanorma-cli`.

To be on the same page:
1. Should I investigate the root of the issue (I mean why compilation fails?
2. What behavior should be there, should metanorma fail-fast by default?

**Comment by ronaldtse** [comment]
> Should I investigate the root of the issue (I mean why compilation fails?

@opoudjis is aware of this: the failures are due to content being mis-encoded. @metanorma/editors will fix those errors.

> What behavior should be there, should metanorma fail-fast by default?

In normal usage, I don't think Metanorma should fail-fast unless explicitly specified.

In GitHub Actions, there should be an option to fail-fast.

**Comment by CAMOBAP** [comment]
> In GitHub Actions, there should be an option to fail-fast.

Done https://github.com/actions-mn/site-gen/issues/1
