### ISSUE TITLE
HTML generation issue

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#198]
Source issue: https://github.com/metanorma/metanorma-ogc/issues/473

Source document: https://github.com/metanorma/mn-samples-ieee-private/tree/main/sources/p2830_d1

The metanorma docker image can't be released due the error (https://github.com/metanorma/metanorma-docker/actions/runs/3621578919/jobs/6105421888):
```
undefined method `name' for nil:NilClass

        while n.name == "p" && n["type"] == "officeorgrepmember"
               ^^^^^
/usr/local/bundle/gems/metanorma-ieee-1.0.0/lib/isodoc/ieee/html_convert.rb:58:in `affiliation_table1'
/usr/local/bundle/gems/metanorma-ieee-1.0.0/lib/isodoc/ieee/html_convert.rb:50:in `block in affiliation_table'
/usr/local/bundle/gems/nokogiri-1.13.9-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/usr/local/bundle/gems/nokogiri-1.13.9-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
/usr/local/bundle/gems/nokogiri-1.13.9-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
/usr/local/bundle/gems/metanorma-ieee-1.0.0/lib/isodoc/ieee/html_convert.rb:49:in `affiliation_table'
```

How to repeat:
```
cd mn-samples-ieee-private\sources\p2830_d1
bundle exec metanorma -t ieee -x html document.adoc 
```

**Comment by opoudjis** [comment]
Replicated. @Intelligent2013 Why did this not get picked up in previous release? Is this a  new document?

**Comment by opoudjis** [comment]
Yeah, that loop was a bit naive. Easy fix. Do you need a gem hotfix?

**Comment by Intelligent2013** [comment]
> Why did this not get picked up in previous release? Is this a new document?

Very strange. The previous release has the same error, but 'green' mark: https://github.com/metanorma/metanorma-docker/actions/runs/3514967518/jobs/5896041695

> Yeah, that loop was a bit naive. Easy fix. Do you need a gem hotfix?

I don't know how to metanorma-docker release working. ping @CAMOBAP.

**Comment by Intelligent2013** [comment]
There is a  difference between last and previous releases. The last one has additional error:
```
/usr/local/bundle/gems/relaton-ieee-1.14.0/lib/relaton_ieee/ieee_bibliographic_item.rb:70:in `to_hash': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /usr/local/bundle/gems/relaton-bib-1.14.0/lib/relaton_bib/document_relation.rb:75:in `to_hash'
	from /usr/local/bundle/gems/relaton-bib-1.14.0/lib/relaton_bib.rb:88:in `block in single_element_array'
	from /usr/local/lib/ruby/3.1.0/forwardable.rb:238:in `map'
```

**Comment by opoudjis** [comment]
@Intelligent2013 @CAMOBAP 

We have a breaking change in here of biblio-tag processing. So the alternatives are:

* Everybody waits a week until normal release
* I do a full release on Monday
* I cherry pick just this change, and release metanorma-ieee + metanorma-cli on their own

The latter is what hotfixes need. You're going to have to make a compelling case for me to do No. 3 instead of No. 1 or No. 2. And yes, I would much rather No. 1. 

The relaton error, I cannot speak to.

**Comment by opoudjis** [comment]
Can we close this ticket? @Intelligent2013 @CAMOBAP?

**Comment by CAMOBAP** [comment]
@opoudjis I think so. In the last release, this issue doesn't reproduce on CI https://github.com/metanorma/metanorma-docker/actions/runs/3736196218

**Comment by Intelligent2013** [comment]
Thanks.
