### ISSUE TITLE
Word (draft): Copyright text should be placed on the Abstract/Keyword preface page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#20]
Template:
<img width="1207" alt="Screenshot 2022-06-20 at 7 00 37 AM" src="https://user-images.githubusercontent.com/11865/174501981-0f3388fd-5150-44b1-b506-94b3c91a7767.png">

In the generated version, the copyright text is placed after the TOC.
<img width="790" alt="Screenshot 2022-06-20 at 7 01 17 AM" src="https://user-images.githubusercontent.com/11865/174501999-b94f45d5-8610-4f09-a0fd-22434b1e3e30.png">

**Comment by opoudjis** [comment]
Already implemented.

<img width="597" alt="Στιγμιότυπο 2022-06-24, 01 32 19" src="https://user-images.githubusercontent.com/1911039/175341296-61e14859-7ec7-4e6b-ba94-da0f3447db9c.png">

This took me a full day.
