### ISSUE TITLE
Word (draft): Table of contents styles needs to match template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#21]
Template:
<img width="707" alt="Screenshot 2022-06-20 at 7 03 54 AM" src="https://user-images.githubusercontent.com/11865/174502060-87fd2d55-c638-45b6-bb70-1295cd2631f5.png">

Now:
<img width="686" alt="Screenshot 2022-06-20 at 7 04 34 AM" src="https://user-images.githubusercontent.com/11865/174502076-470e1f2c-8cbc-4c5e-b5d7-4af4f95e9bb3.png">

**Comment by opoudjis** [comment]
Sigh... Introductory content is not being included in ToC, and needs to be included at level 2.

**Comment by opoudjis** [comment]
Solved in https://github.com/metanorma/metanorma-ieee/issues/30

**Comment by ronaldtse** [comment]
<img width="796" alt="Screenshot 2022-06-29 at 1 33 14 AM" src="https://user-images.githubusercontent.com/11865/176232966-e351a181-ae96-460a-92ad-84702d50d9f7.png">

1. Participants, Abstract, Introduction now shown in TOC
2. In the published standards layout, none of the preface sections show up.

<img width="504" alt="Screenshot 2022-06-29 at 1 34 32 AM" src="https://user-images.githubusercontent.com/11865/176233240-0d7775d3-5914-4817-b856-ea315609961e.png">

I think it would be better to just skip all the preface sections.

**Comment by opoudjis** [comment]
Generate a Table of contents in the Template document. What I am generating is what you get, because that is how the ToC is defined in the template document.

Rejected as invalid unless you get someone from IEEE specifically overriding their own template. And if they do, they should be reissuing their own template anyway.

**Comment by ronaldtse** [comment]
Confirm that this issue is fixed, updating TOC table will not link preface sections (as described by the IEEE editor officially, the preface sections are NOT to be shown in the TOC, it is a problem with their template).

<img width="664" alt="Screenshot 2022-07-04 at 1 13 02 PM" src="https://user-images.githubusercontent.com/11865/177080397-17265a23-39cb-473c-99da-df6491730980.png">
