### ISSUE TITLE
differences in bibliographic generation of PDFs between Dec 15th and Dec 24th, 2022

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#210]
hello @ronaldtse i am noticing some differences in the generation of bibliographic entries, mostly that entry numbers are not being generated consistently for the entries. 

i compared two versions of  an IEEE SA project base PDFs (one from 2022-12-15 and one from 2022-12-24). the differences are shown below. this seems to also happen in the HTML output but **is not** happening in the .doc files. 

i still am not sure how documents from OGC, IETR, and W3C should be created in the bibliography. it could have something to do with the present setup of those entries. for reference they are copied below. any information on correcting those entries to fix this issue is greatly appreciated.  thank you.

![generate_20221215_ieee_bib](https://user-images.githubusercontent.com/35089343/209435730-92e0ece4-45b4-4616-98a3-1b9806b45bc3.png)

Figure 1  generate_20221215_ieee_bib.png

![generate_20221224_ieee_bib](https://user-images.githubusercontent.com/35089343/209435765-7998c271-9134-4c4f-a0f1-b4a768a53477.png)

Figure 2  generate_20221224_ieee_bib.png

section of bibliography code for IETF, OGC, and W3C and ISO/IEC for contrast (below)
```
* [[[ISO_IEC_IEEE_42010_2022,ISO/IEC/IEEE 42010:2022]]]

* [[[IETF_6280,IETF RFC 6280]]], An Architecture for Location and Location Privacy in Internet Applications

* [[[ogc_sensorweb,OGC 07-165r1]]], OGC Sensor Web Enablement: Overview And High Level Architecture

* [[[ogc_citygml,OGC 20-010]]], OGC OGC City Geography Markup Language (CityGML) Part 1: Conceptual Model Standard

* [[[ogc_gml,OGC 07-036]]], OpenGIS Geography Markup Language (GML) Encoding Standard

* [[[ogc_geopose,OGC 21-056r4]]], OGC GeoPose 1.0 Data Exchange Draft Standard.

* [[[w3c_sparql,W3C sparql11-overview]]], W3C SPARQL 1.0 and SPARQL 1.1 recommendation

* [[[w3c_skos,W3C skos-reference]]], Simple Knowledge Organization System

* [[[W3C_WOT,W3C TR/wot-architecture]]], Web of Things (WoT) Architecture

* [[[w3c_rdf,W3C rdf-concepts]]], W3C Resource Description Framework (RDF link) (and QB4St link)

* [[[w3c_owl,W3C owl-time]]], W3C Time Ontology in OWL

* [[[w3c_webxr,W3C webxr]]], W3C WebXR API

```

**Comment by ronaldtse** [comment]
@ReesePlews thank you for reporting! This seems like a bug due to the recent bibliography changes. 

@opoudjis do you know why this is happening? Thanks.

**Comment by ronaldtse** [comment]
Also, the bibliographic entries seems to be entered correctly. This is a bug with generation not the input.

**Comment by ReesePlews** [comment]
@ronaldtse thank you for the reply. as i mentioned i t was only happening in the PDF and HTML, the word file for some reason seems ok, at least in that all of the entries are numbered.

if there is some detailed information on how W3C and related documents should be entries, that would be most helpful. i was adding one on a different branch and it was not being "auto-fetched" correctly.  it almost seems the URI should be included in the bib entries to help identify those documents...

**Comment by opoudjis** [comment]
The issue of missing tags has already been rectified in https://github.com/metanorma/metanorma-ieee/issues/208

The issue did not impact Word, because Word is enforcing the biblio tag as a list through its styles, rather than using content.

With that fix, and with the notion of home-standard vs external standard introduced into the bibliography rendering, the provided references now render in PDF as:


<img width="980" alt="Screen Shot 2022-12-26 at 16 34 37" src="https://user-images.githubusercontent.com/1911039/209507187-a7313729-f1b6-4cdd-b2d5-0fb56a2dc896.png">

Any issues with the W3C content need to be taken up with the relaton-w3c gem; the bibliography is reproducing the information fetched from there.

**Comment by ReesePlews** [comment]
hello @opoudjis, thank you for the message and information. the revised entries look very complete. 
if i understand correctly the current "code" i have in the bibliography will be generated as you have shown above.
i will not adjust those current entries until this new version is active next week.  thank you.

**Comment by opoudjis** [comment]
Letting you know, @reeseplews , I released the Metanorma update yesterday, but I'm going away for a week tomorrow. Happy New Year to you, and looking forward to working with you in the new year!

**Comment by ReesePlews** [comment]
@opoudjis i appreciate the notification on the forthcoming release, and the information about the span notation in the other message is most helpful. thank you very much, and please enjoy your holiday and best wishes for the new year! hope i will not cause too much extra work for you!
