### ISSUE TITLE
Order of bibliographic entries in normative references (clause 2) and bibliographies do not follow IEEE SA style manual

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#213]
the ieee style manual (clause 12.3.5) states that:

_**12.3.5 Style for standards reference entries**
Normative references shall be listed in alphanumeric order by designation, including the full title. Documents that are not standards shall include the edition or date of publication in the citation. A footnote should be inserted in the text after the first cited normative reference in order to tell the reader where the references can be obtained._

in rendered output, i am seeing a change in the order, not with all entries, but with some (w3c entry at both the start and end of the list). can this be checked? thank you.
(images of rendered output and my code are shown below).

![ieee_clause2_render_order_20230112](https://user-images.githubusercontent.com/35089343/212253089-82dcd7ba-3e65-444c-8f94-2d585ec298ef.png)

![ieee_clause2_adoc_order_20230112](https://user-images.githubusercontent.com/35089343/212253095-c4000208-bb55-4357-b4ba-96e3ba804348.png)

**Comment by ronaldtse** [comment]
Thank you @ReesePlews for reporting this! This looks like a bug, as you have clearly described the desired order specified by IEEE SA.

**Comment by ronaldtse** [comment]
As discovered by @ReesePlews the bibliography section is also showing a strange order:

* unresolved IEEE
* OGC
* other things
* IEEE
* ISO
* ...
* other things

<img width="607" alt="Screen Shot 2023-01-17 at 5 04 21 PM" src="https://user-images.githubusercontent.com/11865/212854962-a4b1f4ec-4f77-4a23-8cc6-9eb3b1234aa0.png">

**Comment by opoudjis** [comment]
The RFC reference was going to the end because it was not being prefixed with IETF during the sort.

The W3C reference for JSON-Based serialisation is failing to retrieve from relaton, and my query on docidentifer was too restrictive.

**Comment by opoudjis** [comment]
Fixed Normative References:

<img width="702" alt="Στιγμιότυπο οθόνης 2023-01-22, 01 51 26" src="https://user-images.githubusercontent.com/1911039/213872372-02da73e3-dcde-4028-a189-6b6675147419.png">

**Comment by opoudjis** [comment]
@ReesePlews checking SWF-Corpus_and_IEEEP2874-D2, I am seeing erroneous use of types that result in confusing display after sorting. In particular, type:[journal] is intended for journals (not articles), and clearly cannot apply to 

````
* [[[privacy_soft_eng,1]]],
span:initials[K.] span:surname[Blagovesta], span:initials[S.] span:surname[Gürses], span:initials[C.] span:surname[Troncoso].
span:type[journal]
span:title[Privacy Engineering Meets Software Engineering. On the Challenges of Engineering Privacy ByDesign].
span:date[2020].
doi: span:uri.doi[10.48550/arxiv.2007.08613].
````

This item is sorting correctly under B for Blagovesta; but because journals do not have authors, only the title is shown, which is confusing.

> [B4]  Barrow, H., Connectionism and Neural Networks, 1996.

> [B5]  Privacy Engineering Meets Software Engineering. On the Challenges of Engineering Privacy ByDesign. 2020.

> [B6]  Curry, E., and, Real-time Linked Dataspaces, Springer International Publishing, 2020.

**Comment by opoudjis** [comment]
Further refinements:

* Sorting needs to be case-insensitive: "oneM2M Partners" needs to sort under O.

**Comment by ReesePlews** [comment]
@opoudjis thank you for checking the bibliography entries. regarding this:

> checking SWF-Corpus_and_IEEEP2874-D2, I am seeing erroneous use of types that result in confusing display after sorting. In particular, type:[journal] is intended for journals (not articles), and clearly cannot apply to

i looked at the [bibtex entry ](https://dblp.uni-trier.de/rec/journals/corr/abs-2007-08613.html?view=bibtex)and i though it was some type of journal, but it probably makes more sense it is an article being in arxiv.  in that case is the "type" [article]?  i cannot confirm my bookmark of valid "spans" for bibliography entries. i only could find this [one](https://www.metanorma.org/author/topics/document-format/bibliography/)  is this the correct one? 

i think there are others within the bib of that document i am working on that need some update. i will check them based on the list of valid "span" types. thank you  for pointing this out and for addressing those other issues.

**Comment by opoudjis** [comment]
The available types of document are specified in https://www.relaton.org/specs/model/bibtype/  . They are inherited from Bibtex. 

There is going to be a recurring issue with bibliographic types and renderings: we take the bibliographic types at face value, and render according to the specified type strictly. So a bibtex entry may well say it's a journal, but since journals really do not meaningfully have authors, or for that matter single dates of publication, they will render quite wrong. article is indeed the proper type.

I'm sorry the documentation is all over the shop, but I'm not a technical editor :-(

**Comment by ReesePlews** [comment]
@opoudjis thank you for the link, that is helpful for the document types. i will try and go through my bibliography again and see if i can make any clarifications.  arxiv is interesting if the paper is only places there as open-access, then somewhere, the complete entry from the original source should exist.  

thank you again for fixing the display order.
