### ISSUE TITLE
some cross references from the bibliography do not contain a bib#

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#214]
in an IEEE standard being prepared, i am seeing that some bibliography references do show have the "B#" (B-number -not b-sharp) when rendered in the document. some of them do, but some do not.   i understand that if the reference is a "normative reference" then it should not have a "B#".  an example is posted below.

![PastedGraphic-5](https://user-images.githubusercontent.com/35089343/212785112-218f5f76-d55b-453f-b64c-f79942eb3164.png)

in this example the entry should be B49 and it is not used in clause 2. there are other occurrences in my document where this happens.
thank you for checking.

**Comment by ronaldtse** [comment]
As discussed with @ReesePlews , this is a problem in the source -- the `B#` identifier is overridden by this syntax:
```
<<bib_anchor,OVERRIDING_TEXT>>
```

Instead of this:
```
<<anchor>>
```

<img width="819" alt="Screen Shot 2023-01-17 at 4 59 07 PM" src="https://user-images.githubusercontent.com/11865/212853830-e9ca98b8-fed0-464b-870d-3bc6216cdf6f.png">

It means that instead of this:
```adoc
==== Artificial Intelligence

A third wave of Artificial Intelligence is currently providing unprecedented
capabilities which are relevant to cognitive computing in the Spatial Web.  An
Artificial Intelligence System is an “engineered system that generates outputs
such as content, forecasts, recommendations or decisions for a given set of
human-defined objectives <<ISO_IEC_22989_2022, ISO 22989 AI Concepts and
Terminology>>”.  AI Systems are built using differing technologies such a
Machine Learning, Natural Language Processing, Reinforcement Learning and Active
Inference.  AI Systems may explicitly or implicitly represent knowledge which is
“abstracted information about objects, events, concepts or rules, their
relationships and properties, organized for goal-oriented systematic use
(<<ISO_IEC_22989_2022, ISO 22989>>)“  Research on AI includes aspects such as
“learning, recognition and prediction”, “inference, knowledge and language” and
“discovery, search and creation”. AI Systems will be included in nodes within
the Spatial Web. 
```

```adoc
==== Artificial Intelligence

A third wave of Artificial Intelligence is currently providing unprecedented
capabilities which are relevant to cognitive computing in the Spatial Web.  An
Artificial Intelligence System is an “engineered system that generates outputs
such as content, forecasts, recommendations or decisions for a given set of
human-defined objectives <<ISO_IEC_22989_2022>>”.  AI Systems are built
using differing technologies such a
Machine Learning, Natural Language Processing, Reinforcement Learning and Active
Inference.  AI Systems may explicitly or implicitly represent knowledge which is
“abstracted information about objects, events, concepts or rules, their
relationships and properties, organized for goal-oriented systematic use
(<<ISO_IEC_22989_2022>>)“  Research on AI includes aspects such as
“learning, recognition and prediction”, “inference, knowledge and language” and
“discovery, search and creation”. AI Systems will be included in nodes within
the Spatial Web. 
```

This display syntax for bibliographic records is not in accordance with the IEEE SA Style Manual, where:

* a normative bibliographic entry shows only the doc ID (e.g. "ISO/IEC 22989:2022")
* a non-normative bibliographic entry uses only "[B#]".

The easy fix is to remove all `,OVERRIDING_TEXT` from all bibliographic citations.
