### ISSUE TITLE
Word (draft): Section numbering and order different from template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#22]
## From Template

Preface sections:

- Notice and Disclaimer of Liability Concerning the Use of IEEE Standards Documents
- Translations
- Official statements
- Comments on standards
- Laws and regulations
- Data privacy
- Copyrights
- Photocopies
- Updating of IEEE Standards documents
- Errata
- Patents
- IMPORTANT NOTICE

Clauses:

1. Overview
1.1 Scope
1.2 Purpose
1.3 Word usage

2. Normative references

3. Definitions, acronyms, and abbreviations
3.1 Definitions
3.2 Acronyms and abbreviations

4. First level header
4.1 Second level header
4.1.1 Third level header

5. First level header

Annex A (informative) Annex Heading placeholder
A.1 Annex header 1
A.1.1 Annex header 2

Annex B (informative) Bibliography

## Generated

<img width="585" alt="Screenshot 2022-06-20 at 7 07 14 AM" src="https://user-images.githubusercontent.com/11865/174502138-29c7d5c3-2074-4957-aa1d-608df16e368a.png">

## Issues

1. Overview is 1 (this went into 4)
2. Scope is 1.1 (this went into 4.1)
3. Purpose is 1.2 (this went into 4.2)
4. Word usage is 1.3 (this is to be fixed in document source but MN-IEEE needs to support the numbering)
5. Definitions is 3.1 (missing right now)

**Comment by opoudjis** [comment]
1, 1, 1.2 already fixed; 5 is still broken, will need to investigate.

**Comment by ronaldtse** [comment]
I have provided the text for testing problem 5 in https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2 , which you can test.

**Comment by opoudjis** [comment]
Issue has gone away in current doc.
