### ISSUE TITLE
Word (draft): list styling needs updating

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#23]
Generated:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/11865/174502239-9b206bf1-965a-4f4b-8863-37c5544fd0c7.png">

The challenge is that the template doesn't even provide samples for lists.

I assume these are the proper styles to use:
<img width="258" alt="Screenshot 2022-06-20 at 7 12 28 AM" src="https://user-images.githubusercontent.com/11865/174502253-cbeea25c-fe5b-4455-bac2-870a391e1537.png">
<img width="256" alt="Screenshot 2022-06-20 at 7 12 43 AM" src="https://user-images.githubusercontent.com/11865/174502267-d9cea3b2-b1ff-4c3e-a6b2-bfb52dfaf755.png">

**Comment by opoudjis** [comment]
Just done this tonight.
