### ISSUE TITLE
Word (draft): main content title should not be followed by a page break

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#24]
Template:
<img width="763" alt="Screenshot 2022-06-20 at 7 22 58 AM" src="https://user-images.githubusercontent.com/11865/174502528-39d96240-584c-47e5-a704-b7dc133601ca.png">

Now:
<img width="680" alt="Screenshot 2022-06-20 at 7 24 35 AM" src="https://user-images.githubusercontent.com/11865/174502556-1d2c85ee-7579-4f91-87fe-2a3444683a8f.png">

**Comment by opoudjis** [comment]
Once again, already fixed, premature ticket.

<img width="597" alt="Στιγμιότυπο 2022-06-24, 01 37 11" src="https://user-images.githubusercontent.com/1911039/175338754-62311f18-425f-478a-b18d-416210fee3e8.png">
 
This is not how I work.
