### ISSUE TITLE
Word (draft): support IEEE admonitions (NOTE, WARNING, CAUTION)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#25]
Unnumbered note and numbered note:
<img width="492" alt="Screenshot 2022-06-20 at 7 28 00 AM" src="https://user-images.githubusercontent.com/11865/174502642-a6578ff9-cfb1-4b28-b50a-7ad7d09dc0a7.png">

Word styles from template:
<img width="267" alt="Screenshot 2022-06-20 at 7 28 16 AM" src="https://user-images.githubusercontent.com/11865/174502649-e31fa3eb-8f3c-4e5c-8335-69495a22b73b.png">
<img width="264" alt="Screenshot 2022-06-20 at 7 28 53 AM" src="https://user-images.githubusercontent.com/11865/174502659-84ba5e1e-7339-49db-913d-bd58552914f0.png">
<img width="260" alt="Screenshot 2022-06-20 at 7 30 09 AM" src="https://user-images.githubusercontent.com/11865/174502684-e9fe7463-ab8e-4dc9-a7a7-4d5784aa2a44.png">

From Word template documentation:
<img width="541" alt="Screenshot 2022-06-20 at 7 26 55 AM" src="https://user-images.githubusercontent.com/11865/174502603-0a5d2c7b-0d7b-4e06-a2c5-456d20ccf674.png">

From style manual 2021:
<img width="500" alt="Screenshot 2022-06-20 at 7 27 13 AM" src="https://user-images.githubusercontent.com/11865/174502615-8dd89d33-9ab1-4d1f-a588-005f45c8926b.png">

**Comment by opoudjis** [comment]
Warning and Caution implemented.

**Comment by opoudjis** [comment]
Notes done.
