### ISSUE TITLE
Word: indent missing for list, list bullet style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#268]
Originally from:
* https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/710

from @Reeseplews

This appears to be a rendering difference;  Word version NOT_Correct; PDF version CORRECT;  also MS-Word file uses a), b), etc for list but PDF uses 1), 2), etc...  see Fig 2 IEEE style guide and clause 13.3

ms-word incorrect indent render:
![ieee_P2874_ms-word_4-4-7_render_difference](https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/assets/35089343/bba96688-a9a5-471f-9470-0a2c33bf0ee2)

pdf_correct indent render;
![ieee_P2874_PDF_4-4-7_render_difference](https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/assets/35089343/ea31e550-bef0-450f-aeb4-cf6c33c7e376)

**Comment by ronaldtse** [comment]
@opoudjis this is a reported blocker for IEEE draft submission. Thanks.

**Comment by opoudjis** [comment]
There are several issues.

1. The bulleted list nested two levels down is getting the same style as the bulleted list nested one level down, which is IEEStds Unordered List Level 2, instead of IEEStds Unordered List Level 3
2. IEEStds Unordered List Level 2 is defined twice in the stylesheet, once with a dash, once with a bullet.
3. The top list in a clause is numbered by letter in Word, by number in PDF.

In 3, Word behaviour is CORRECT. I'm going to check to ensure that the PDF is receiving correct information about lists from the Presentation XML, and processes it. @Intelligent2013 

2 is clearly a bug.

In 1, IEEStds Unordered List Level 3 *is not defined at all in the IEEE-generated stylesheet*. If IEEE do not define a style, I do not use it. My impression between the lines, reading 13.3 in the style guide, is that IEEE *do not want* more than two levels of unordered lists used. Since this is going to keep happening, I'm going to define Word styles for them anyway; this is a recurring requirement, and if IEEE want to block three levels of unordered lists, they should be saying it more explicitly, instead of "if you really must subdivide an unordered list..."

**Comment by ReesePlews** [comment]
@opoudjis thank you for checking this. i will wait for the update.

**Comment by opoudjis** [comment]
Moreover:

<img width="663" alt="Screenshot 2023-06-03 at 10 55 08" src="https://github.com/metanorma/metanorma-ieee/assets/1911039/7b1ea19c-4e5d-40f6-bd16-03077c3b0cad">

@ReesePlews, as this example from the IEEE style manual makes very clear, the PDF is more wrong than the Word document.

The formatting of lists in IEEE is as follows:

* Ordered and unordered interleaved lists are successively indented (Word is wrong, although IEEE are implicitly discouraging more than two levels of nested unordered lists)
* The first encountered unordered lists hierarchically get dashes at their start; deeper unordered lists get dashes (Word and PDF both wrong)
* For ordered lists, the ranking of levels is a) 1) i) (PDF is wrong)
* The spec is unclear about whether a second ordered list in the same subclause is outright forbidden, or allowed with the levels mixed:

> Only one occurrence of any level of an ordered list may be presented in any subclause to avoid confusing cross-references [e.g., it is OK to have an a) level list followed by a 1) level list, etc., but there should not be more than one a) level list in the same clause or subclause]. 

I've interpreted it as: an a) 1) i) list can be followed by an 1) i) a) list (it is meaningless for 1) to be referenced in an a) 1) i) list independently of its parent.) So a subclause may have three ordered lists, with their levels numbered a) 1) i) , 1) i) a) , i) a) 1) (PDF wrong, and I do indicate for each level in Presentation XML ordered lists what the level should be)

**Comment by Intelligent2013** [comment]
I don't see the screenshots from the initial post. And don't have the access to the original repository, only to https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

> list but PDF uses 1), 2), etc...

```xml
<clause id="section-warehouse-robot-scenario" inline-header="false" obligation="normative">
	<title depth="3">4.4.2.<tab/>Warehouse Robot</title>
	<ol id="_015ce122-7ade-f21e-4e33-718108f8a8ed" type="arabic">
		<li>
			<p id="_ec2178bb-de28-d9f5-8c45-1a7c2317a759">Summary</p>
```
`type="arabic"` and PDF renders arabic also:
![image](https://github.com/metanorma/metanorma-ieee/assets/5559926/07634090-08e6-416f-ad9c-db76c05c53ab)

Today, in the another presentation XML I've found that list type changed from `alphabet` to `alphabetic`. But XSLT process `alphabet` value only, and `arabic` by default. May be the reason in this, but in any case the value `type="arabic"` in IEEE xml....

> The first encountered unordered lists hierarchically get dashes at their start; deeper unordered lists get dashes (Word and PDF both wrong)

I.e. should we dashes at all levels, right?

**Comment by opoudjis** [comment]
Yes. I am passing you a wrong value in Presentation XML, and I need to fix it; right now HTML and PDF are wrong, because I'm only repairing the list numbering in Word output.

Sorry, I misspoke: I meant

The first encountered unordered lists hierarchically get dashes at their start; deeper unordered lists get **bullets** (Word and PDF both wrong)

**Comment by Intelligent2013** [comment]
XSLT updated for dashes in all ul levels (will be committed to metanorma-ieee soon).

**Comment by opoudjis** [comment]
The susperstructure to get Word to work (including assigning letters by list level, and resetting the list number so they don't overlap) is possibly fragile, but I think I will go with it.

**Comment by opoudjis** [comment]
<img width="465" alt="Screenshot 2023-06-03 at 18 23 45" src="https://github.com/metanorma/metanorma-ieee/assets/1911039/0df74e43-455e-4010-abe7-0db86b3de833">

**Comment by ReesePlews** [comment]
@opoudjis thank you and your colleagues for making these updates. i am not sure how the revised version is "pulled into the current IEEE project development cycle", but i will check this again later in the week. thank you.

**Comment by ReesePlews** [comment]
hello @opoudjis i have checked this update in a project document generated 20230628 however i am seeing a difference in rendering between 

PDF
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/64ebb239-3a75-4bef-a4d4-152d49af0c64)

MS-Word
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/f49d2a57-5119-408f-a244-eaf8fd7b57e2)

if there is an issue with the document not following IEEE style rules, please let me know and work to update, but a two level deep list does not seem out of place.  

please take a look at your convenience. thank you.

**Comment by opoudjis** [comment]
> IEEStds Unordered List Level 2 is defined twice in the stylesheet, once with a dash, once with a bullet.

Looks like I removed the wrong one...

**Comment by opoudjis** [comment]
Sigh.

What has happened is, I came away from the exchange of June 3 thinking deeper indented unordered lists are bulleted, and Alex came away thinking they are dashed.

It looks like I got that impression from the Word stylesheet, which left lower levels bulleted (when it didn't define them doubly). But (a) the IEEE style manual speaks only of dashed lists, not unordered lists, which implies dashes at all levels of indentation; and (b) the bullets in the Word stylesheet are likelier the result of inattention from IEEE. The IEEE style manual is certainly cavalier enough about defining unordered lists properly, to allow me to form that negative conclusion.

Accordingly, I'm removing all bullets from the Word stylesheet.

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for checking this more; i did see a change in early july or so; the issue i reported seemed to have been corrected... however, yesterday i filed another issue regarding line spacing of multi-line entries in lists; #292 ; i was noticing that on the IEEE project i am working on. i am not sure if they are related; perhaps the additional changes here will change something with that other issue?  i only checked based on MS-Word output vs the IEEE style manual PDF. i know you are busy but when you have time to check this, please let me know if they are related or not.  thank you.
