### ISSUE TITLE
Word (draft): Bibliography and Normative references should use proper styling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#27]
Template:
<img width="757" alt="Screenshot 2022-06-20 at 7 35 32 AM" src="https://user-images.githubusercontent.com/11865/174502821-15dc726b-5bea-4b50-9e53-f95c28b03d2b.png">
<img width="1309" alt="Screenshot 2022-06-20 at 7 35 46 AM" src="https://user-images.githubusercontent.com/11865/174502826-f9096553-a693-43aa-906c-4df8175ef894.png">

The "[B1]" is a list:
<img width="360" alt="Screenshot 2022-06-20 at 7 36 06 AM" src="https://user-images.githubusercontent.com/11865/174502835-9bbf675d-53fc-4f56-aadc-b753ba6bf2b4.png">

Generated:
<img width="581" alt="Screenshot 2022-06-20 at 7 36 22 AM" src="https://user-images.githubusercontent.com/11865/174502840-58040d8d-fd76-4cc9-a4df-d1b958e8c491.png">

**Comment by ronaldtse** [comment]
Normative references look like this:
<img width="506" alt="Screenshot 2022-06-20 at 7 37 58 AM" src="https://user-images.githubusercontent.com/11865/174502891-515bc410-1736-4fa7-bc6c-9f6e71e902ba.png">
<img width="480" alt="Screenshot 2022-06-20 at 7 38 27 AM" src="https://user-images.githubusercontent.com/11865/174502900-9472c0b2-76d4-4134-8378-5a27dad3b43d.png">

**Comment by ronaldtse** [comment]
Right now, the "Normative references" list is shown in the `[B1] ...` format. It should drop the `[B1]` label.

**Comment by ronaldtse** [comment]
Official Normative reference advice from IEEE:

> The normative references are simply in Body Text (regular paragraph style). Our style manual shows how they should be listed. The footnotes provide information as to where to get the sources, but the "correct" way to represent them (or even include them when absent) will be addressed during publication.
> 
> But if you are interested, the footnotes for IEEE standards are:
> 
> 1 The IEEE standards or products referred to in this clause are trademarks of The Institute of Electrical and Electronics Engineers, Inc.
> 2 IEEE publications are available from The Institute of Electrical and Electronics Engineers, 445 Hoes Lane, Piscataway, NJ 08854, USA (http://standards.ieee.org/).
> 
> You really don't need to include these footnotes unless you are aware that a source you are listing is somewhat hard to find -- we can usually find links to include.

**Comment by ronaldtse** [comment]
@opoudjis I noticed that IEEE published standards only contain these 2 footnotes for IEEE, not other publishers. The footnotes are applied to the first IEEE normative reference. I think we need to provide this.

**Comment by ronaldtse** [comment]
Actually I was incorrect:

IETF:
802-1Qcy-2019.pdf
<img width="510" alt="Screenshot 2022-06-25 at 12 11 06 PM" src="https://user-images.githubusercontent.com/11865/175756009-a4ed6a7a-c9d4-4328-baef-1f03e8d5ea01.png">
<img width="598" alt="Screenshot 2022-06-25 at 12 11 14 PM" src="https://user-images.githubusercontent.com/11865/175756011-6dc347e5-ffb5-40bf-9231-c3f39a3eb485.png">
<img width="605" alt="Screenshot 2022-06-25 at 3 57 57 PM" src="https://user-images.githubusercontent.com/11865/175762438-6574fdc9-ec1c-4a3e-ab3e-cb3849c8fff2.png">
<img width="405" alt="Screenshot 2022-06-25 at 3 58 10 PM" src="https://user-images.githubusercontent.com/11865/175762443-28d30307-98be-4278-96d0-d0ec626cc4e2.png">


802-2014.pdf
<img width="632" alt="Screenshot 2022-06-25 at 12 11 57 PM" src="https://user-images.githubusercontent.com/11865/175756036-db910318-72f6-43fd-8482-1d860fe13222.png">
<img width="813" alt="Screenshot 2022-06-25 at 12 12 23 PM" src="https://user-images.githubusercontent.com/11865/175756048-aa6362df-f51d-4103-8da1-77a74530e10a.png">


<img width="678" alt="Screenshot 2022-06-25 at 12 13 47 PM" src="https://user-images.githubusercontent.com/11865/175756069-aba806a0-c25b-4b4c-b6cf-847a66607c32.png">
<img width="611" alt="Screenshot 2022-06-25 at 12 13 54 PM" src="https://user-images.githubusercontent.com/11865/175756071-965a58ad-c304-4525-afff-ab0b24f9dffc.png">
(The "NTIS" site is no longer extant)

<img width="643" alt="Screenshot 2022-06-25 at 12 15 07 PM" src="https://user-images.githubusercontent.com/11865/175756097-d6ddf5f7-4d3c-4cfc-84a2-082bfaf1d685.png">
<img width="638" alt="Screenshot 2022-06-25 at 12 15 16 PM" src="https://user-images.githubusercontent.com/11865/175756100-053a4481-411b-425c-8ba8-bc77dcb498e1.png">


<img width="601" alt="Screenshot 2022-06-25 at 12 15 35 PM" src="https://user-images.githubusercontent.com/11865/175756109-81c1b9d7-9851-455e-a5fb-2e2fb1c58a32.png">
<img width="615" alt="Screenshot 2022-06-25 at 12 15 44 PM" src="https://user-images.githubusercontent.com/11865/175756116-7f9f9c75-91f0-441e-aeef-845492a1f35f.png">

<img width="403" alt="Screenshot 2022-06-25 at 12 16 04 PM" src="https://user-images.githubusercontent.com/11865/175756131-e74733ef-c3fe-468b-a667-56b97da44741.png">
<img width="620" alt="Screenshot 2022-06-25 at 12 16 15 PM" src="https://user-images.githubusercontent.com/11865/175756135-7c08eaee-cde7-4cec-a0ba-7169c6bf4d16.png">


<img width="639" alt="Screenshot 2022-06-25 at 12 17 23 PM" src="https://user-images.githubusercontent.com/11865/175756163-91ea92e1-edb2-4977-8512-1b26a1a0609b.png">
<img width="608" alt="Screenshot 2022-06-25 at 12 17 38 PM" src="https://user-images.githubusercontent.com/11865/175756168-ec04c048-c3a5-4e2e-bf1c-7a3ed6262951.png">


<img width="614" alt="Screenshot 2022-06-25 at 12 18 22 PM" src="https://user-images.githubusercontent.com/11865/175756186-209ef3b9-898a-4583-b516-81fa939c5fd5.png">
<img width="488" alt="Screenshot 2022-06-25 at 12 18 32 PM" src="https://user-images.githubusercontent.com/11865/175756191-7135240a-4f27-4625-b78d-a648cce7b6ff.png">


<img width="468" alt="Screenshot 2022-06-25 at 12 19 38 PM" src="https://user-images.githubusercontent.com/11865/175756220-2cf43bd7-ad60-4072-8e29-a08c2da44a80.png">
<img width="351" alt="Screenshot 2022-06-25 at 12 19 46 PM" src="https://user-images.githubusercontent.com/11865/175756222-2925cd19-06c9-4714-868e-ad5211ea98f0.png">

<img width="403" alt="Screenshot 2022-06-25 at 12 20 04 PM" src="https://user-images.githubusercontent.com/11865/175756229-1a0e00dd-cd17-4d22-a81e-6dfe81507cec.png">
<img width="384" alt="Screenshot 2022-06-25 at 12 20 18 PM" src="https://user-images.githubusercontent.com/11865/175756235-217547b3-2bc9-49ca-9593-7835fbbaf62f.png">

NIST (from 2020):
<img width="604" alt="Screenshot 2022-06-25 at 12 20 28 PM" src="https://user-images.githubusercontent.com/11865/175756242-20e3f3f0-b2d7-4833-918c-ce306db66263.png">
<img width="508" alt="Screenshot 2022-06-25 at 12 20 39 PM" src="https://user-images.githubusercontent.com/11865/175756244-dc7a42f7-2910-45dc-b2df-2071cbd81d68.png">

ASTM:
<img width="610" alt="Screenshot 2022-06-25 at 12 32 43 PM" src="https://user-images.githubusercontent.com/11865/175756593-b3d2bf9b-afe7-4ff1-8a7e-2dc70087d98b.png">
<img width="605" alt="Screenshot 2022-06-25 at 12 32 56 PM" src="https://user-images.githubusercontent.com/11865/175756598-7f8c71d3-7219-41fe-a2d9-106ab65f349b.png">

<img width="520" alt="Screenshot 2022-06-25 at 3 52 53 PM" src="https://user-images.githubusercontent.com/11865/175762239-bf8fbfa0-2d53-41f0-afed-3225484caa68.png">
<img width="495" alt="Screenshot 2022-06-25 at 3 53 00 PM" src="https://user-images.githubusercontent.com/11865/175762244-33aace0b-e156-414c-8019-2b1414f069b4.png">

<img width="617" alt="Screenshot 2022-06-25 at 3 43 31 PM" src="https://user-images.githubusercontent.com/11865/175761915-28fd59a2-8076-45df-bfbf-06722032ea7e.png">


ATIS:
<img width="609" alt="Screenshot 2022-06-25 at 3 53 27 PM" src="https://user-images.githubusercontent.com/11865/175762262-631812d8-c74a-4e51-858f-f6a7de5714f7.png">
<img width="486" alt="Screenshot 2022-06-25 at 3 53 39 PM" src="https://user-images.githubusercontent.com/11865/175762267-717d349e-5bd6-4ed2-a403-352922f6eefd.png">

IEC-CISPR:
<img width="605" alt="Screenshot 2022-06-25 at 3 53 56 PM" src="https://user-images.githubusercontent.com/11865/175762283-d0a00711-0bb8-43e6-9fcc-1125487f5b07.png">
<img width="592" alt="Screenshot 2022-06-25 at 3 54 11 PM" src="https://user-images.githubusercontent.com/11865/175762291-95fd8fc4-f3a9-4d2e-ba63-c2a925d614b9.png">

EIA and JEDEC:
<img width="512" alt="Screenshot 2022-06-25 at 3 54 22 PM" src="https://user-images.githubusercontent.com/11865/175762299-cdcc41bc-6b54-4068-b63a-e1c2134f695b.png">
<img width="586" alt="Screenshot 2022-06-25 at 3 54 33 PM" src="https://user-images.githubusercontent.com/11865/175762301-bcf259ce-7036-4a56-a1d6-7e299be5ae2b.png">




EN
<img width="612" alt="Screenshot 2022-06-25 at 12 33 04 PM" src="https://user-images.githubusercontent.com/11865/175756600-719f00c7-cad2-429d-ac20-08dfffedd843.png">
<img width="284" alt="Screenshot 2022-06-25 at 12 33 13 PM" src="https://user-images.githubusercontent.com/11865/175756605-fe4468ae-429d-4ef9-a2cf-b760d651f495.png">

Energy Star
<img width="335" alt="Screenshot 2022-06-25 at 12 33 21 PM" src="https://user-images.githubusercontent.com/11865/175756611-ce7c4f90-0a7a-4a7d-9337-62c76f36b21f.png">
<img width="516" alt="Screenshot 2022-06-25 at 12 33 36 PM" src="https://user-images.githubusercontent.com/11865/175756619-90ca84e2-7712-45e1-b1c5-b9b60049e12c.png">


EU:
<img width="607" alt="Screenshot 2022-06-25 at 3 17 46 PM" src="https://user-images.githubusercontent.com/11865/175761121-62e24096-9e89-44cf-aef6-81eb30b985b7.png">
<img width="290" alt="Screenshot 2022-06-25 at 3 17 57 PM" src="https://user-images.githubusercontent.com/11865/175761126-89b22d2e-c725-48ca-b6d8-7b3a4f6d3afa.png">

REACH:
<img width="606" alt="Screenshot 2022-06-25 at 3 18 05 PM" src="https://user-images.githubusercontent.com/11865/175761130-88ed463d-5e66-407c-a9ed-7f142fbab173.png">
<img width="592" alt="Screenshot 2022-06-25 at 3 18 13 PM" src="https://user-images.githubusercontent.com/11865/175761135-2d1eab69-7279-4cfd-bcdb-092671cfd865.png">

IEC and ISO:
<img width="504" alt="Screenshot 2022-06-25 at 3 20 26 PM" src="https://user-images.githubusercontent.com/11865/175761189-f482e354-0aa5-442e-aa0e-d63d9b460bc2.png">
<img width="596" alt="Screenshot 2022-06-25 at 3 18 40 PM" src="https://user-images.githubusercontent.com/11865/175761152-b304df21-1022-4630-b587-431876c2a14c.png">

IEC:
<img width="524" alt="Screenshot 2022-06-25 at 3 44 45 PM" src="https://user-images.githubusercontent.com/11865/175761951-c9db961b-584a-4770-9041-bdf7ce49b320.png">
<img width="599" alt="Screenshot 2022-06-25 at 3 44 53 PM" src="https://user-images.githubusercontent.com/11865/175761952-30c8bad0-ac15-4418-b356-ba547da1c6b4.png">
<img width="331" alt="Screenshot 2022-06-25 at 3 55 17 PM" src="https://user-images.githubusercontent.com/11865/175762343-398967f3-9448-4c30-ae80-a9c750b1b81f.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/11865/175762357-c3754a67-0b3b-4a1e-9d5e-e60cc94272b9.png">

ISO:
<img width="369" alt="Screenshot 2022-06-25 at 3 45 00 PM" src="https://user-images.githubusercontent.com/11865/175761959-0af4f0d8-d8eb-460d-9afe-57fa9e87aa31.png">
<img width="591" alt="Screenshot 2022-06-25 at 3 45 06 PM" src="https://user-images.githubusercontent.com/11865/175761964-6fe619cd-80ab-44ad-b6c9-61fa0d8779fe.png">

UL:
<img width="520" alt="Screenshot 2022-06-25 at 3 45 41 PM" src="https://user-images.githubusercontent.com/11865/175761982-15502c76-2133-4933-8b4f-f6c3cee88326.png">
<img width="442" alt="Screenshot 2022-06-25 at 3 45 50 PM" src="https://user-images.githubusercontent.com/11865/175761984-2e2412b2-ab6e-4445-bf2e-6aaf8fe8ef15.png">


ECMA:
<img width="494" alt="Screenshot 2022-06-25 at 3 20 52 PM" src="https://user-images.githubusercontent.com/11865/175761207-bd80b672-18ed-427f-8170-3f3df02510fa.png">
<img width="520" alt="Screenshot 2022-06-25 at 3 21 05 PM" src="https://user-images.githubusercontent.com/11865/175761217-a494a7ff-6e56-44ad-ba85-ee01ed33251b.png">

UNECE:
<img width="453" alt="Screenshot 2022-06-25 at 3 21 14 PM" src="https://user-images.githubusercontent.com/11865/175761220-9e521670-31f5-4a9c-9bd0-e1b7092b1963.png">

3GPP:
<img width="599" alt="Screenshot 2022-06-25 at 3 23 43 PM" src="https://user-images.githubusercontent.com/11865/175761283-cd8cb995-48a7-4563-9e6e-226b4798354a.png">
<img width="499" alt="Screenshot 2022-06-25 at 3 23 58 PM" src="https://user-images.githubusercontent.com/11865/175761288-c8ececee-cba6-42a6-8ae0-c0c9990b0a9f.png">

ETSI:
<img width="603" alt="Screenshot 2022-06-25 at 3 24 17 PM" src="https://user-images.githubusercontent.com/11865/175761297-b1dd9552-50b5-491d-b2f1-809e76da8c4d.png">
<img width="505" alt="Screenshot 2022-06-25 at 3 24 23 PM" src="https://user-images.githubusercontent.com/11865/175761301-3dbad453-50c7-47d5-9745-6e40a071664e.png">

<img width="596" alt="Screenshot 2022-06-25 at 3 30 02 PM" src="https://user-images.githubusercontent.com/11865/175761483-274b4abf-f42b-4370-b11a-bc8cf56f2178.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/11865/175762318-b20bbe60-7e3f-4d3c-9e40-0139e5b45dc6.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/11865/175762333-907dea5e-9b6c-4613-908f-d17261aa7733.png">


FIPS:
<img width="332" alt="Screenshot 2022-06-25 at 3 24 42 PM" src="https://user-images.githubusercontent.com/11865/175761312-c7c97f77-ec19-4951-9cc0-89d5317f2cb7.png">
<img width="492" alt="Screenshot 2022-06-25 at 3 24 54 PM" src="https://user-images.githubusercontent.com/11865/175761317-4cce4d7e-6a37-4080-95e4-539d8410ac1a.png">

ISO/IEC:
<img width="603" alt="Screenshot 2022-06-25 at 3 25 36 PM" src="https://user-images.githubusercontent.com/11865/175761350-5a1c685d-5577-4e8b-8992-bf7184195a23.png">

<img width="591" alt="Screenshot 2022-06-25 at 3 25 19 PM" src="https://user-images.githubusercontent.com/11865/175761334-7412f831-4b3d-4c18-8c65-89d81f5b4d6c.png">

<img width="606" alt="Screenshot 2022-06-25 at 3 32 59 PM" src="https://user-images.githubusercontent.com/11865/175761561-7d64c52a-9ba1-4f32-85d4-7f5d33d46850.png">

<img width="588" alt="Screenshot 2022-06-25 at 3 33 07 PM" src="https://user-images.githubusercontent.com/11865/175761571-74123e17-0ba3-4c51-a417-1533f4f1b7c2.png">


ITU:
<img width="605" alt="Screenshot 2022-06-25 at 3 25 53 PM" src="https://user-images.githubusercontent.com/11865/175761367-6abfb09c-1564-41cb-84ab-93494e7014a0.png">
<img width="464" alt="Screenshot 2022-06-25 at 3 26 04 PM" src="https://user-images.githubusercontent.com/11865/175761372-5a5f4299-b257-47fb-8337-217d2631e530.png">

This is inconsistent usage in 80221-2017.pdf where it distinguishes ITU-T vs ITU:
<img width="599" alt="Screenshot 2022-06-25 at 3 29 09 PM" src="https://user-images.githubusercontent.com/11865/175761457-d668b2f7-bb33-40a6-84d8-f52e5f7d9eac.png">
<img width="480" alt="Screenshot 2022-06-25 at 3 29 34 PM" src="https://user-images.githubusercontent.com/11865/175761469-7703e628-0cd0-4b77-9011-3a980cdaa9f9.png">

Another inconsistent usage in 802222-2012.pdf:
<img width="469" alt="Screenshot 2022-06-25 at 3 33 25 PM" src="https://user-images.githubusercontent.com/11865/175761582-fe6cba43-227e-4520-a533-ee05e76a4716.png">
<img width="235" alt="Screenshot 2022-06-25 at 3 33 41 PM" src="https://user-images.githubusercontent.com/11865/175761589-937156ce-d05d-49da-a22f-415cce6cdd4f.png">



ANSI/NEMA:
<img width="567" alt="Screenshot 2022-06-25 at 3 34 12 PM" src="https://user-images.githubusercontent.com/11865/175761604-e6322a8d-3f5f-44b5-9d14-5c10f74bbd54.png">
<img width="579" alt="Screenshot 2022-06-25 at 3 34 22 PM" src="https://user-images.githubusercontent.com/11865/175761613-03577202-d32a-4cfd-aa08-605f11c71c61.png">


NIST:
<img width="604" alt="Screenshot 2022-06-25 at 3 26 14 PM" src="https://user-images.githubusercontent.com/11865/175761379-7bf5a3e8-0ce7-483c-b889-ac298e430c62.png">

<img width="494" alt="Screenshot 2022-06-25 at 3 26 33 PM" src="https://user-images.githubusercontent.com/11865/175761385-9730e2de-cd85-444c-8de1-087f8d2949b7.png">
<img width="596" alt="Screenshot 2022-06-25 at 3 58 23 PM" src="https://user-images.githubusercontent.com/11865/175762452-b461c189-9784-44ff-b4b0-3940d1c64561.png">
<img width="499" alt="Screenshot 2022-06-25 at 3 58 29 PM" src="https://user-images.githubusercontent.com/11865/175762458-f19b6c42-d63d-4c8a-96ad-40abc28720e1.png">

OASIS:
<img width="329" alt="Screenshot 2022-06-25 at 3 58 58 PM" src="https://user-images.githubusercontent.com/11865/175762479-0c5120c2-247e-438b-a0b9-5f330e540135.png">
<img width="594" alt="Screenshot 2022-06-25 at 3 59 04 PM" src="https://user-images.githubusercontent.com/11865/175762484-40af7c9d-e05d-435a-b9ea-2e683a6db11f.png">


OMA:
<img width="452" alt="Screenshot 2022-06-25 at 3 26 46 PM" src="https://user-images.githubusercontent.com/11865/175761391-d283bf03-c1a1-4400-a6b5-84c41910ace7.png">
<img width="476" alt="Screenshot 2022-06-25 at 3 27 18 PM" src="https://user-images.githubusercontent.com/11865/175761404-2bb46ed4-69f8-4a01-9753-64ab17712e51.png">

ANSI:
<img width="279" alt="Screenshot 2022-06-25 at 3 28 18 PM" src="https://user-images.githubusercontent.com/11865/175761428-b8829d6a-ba9f-4d84-b8b2-08353489d236.png">
<img width="474" alt="Screenshot 2022-06-25 at 3 28 26 PM" src="https://user-images.githubusercontent.com/11865/175761431-b556880c-68e0-4818-b2bf-ed1b68a357fc.png">
<img width="599" alt="Screenshot 2022-06-25 at 3 51 21 PM" src="https://user-images.githubusercontent.com/11865/175762178-faff03dc-f462-4ad1-a4c1-c2860c20d328.png">
<img width="462" alt="Screenshot 2022-06-25 at 3 51 39 PM" src="https://user-images.githubusercontent.com/11865/175762189-15e1c775-3f19-4d96-aff8-f878e51a6fd4.png">

ANSI/TIA, TIA:
<img width="561" alt="Screenshot 2022-06-25 at 3 51 51 PM" src="https://user-images.githubusercontent.com/11865/175762200-b74f102d-c46e-4424-adb1-b539cf09c8bd.png">
<img width="597" alt="Screenshot 2022-06-25 at 3 52 25 PM" src="https://user-images.githubusercontent.com/11865/175762217-1ca80a7a-1d01-4b1f-aab1-d2c86e48742c.png">

<img width="602" alt="Screenshot 2022-06-25 at 3 57 09 PM" src="https://user-images.githubusercontent.com/11865/175762413-e254df94-5ca4-45c9-9dc8-9bb5046c5f91.png">
<img width="589" alt="Screenshot 2022-06-25 at 3 57 16 PM" src="https://user-images.githubusercontent.com/11865/175762416-5658b4e5-82fd-47b7-96a2-1079f8ccf8f2.png">



W3C:
<img width="556" alt="Screenshot 2022-06-25 at 3 28 49 PM" src="https://user-images.githubusercontent.com/11865/175761445-a0ae6f38-5372-47f9-90a9-61ff6761c240.png">
<img width="298" alt="Screenshot 2022-06-25 at 3 28 58 PM" src="https://user-images.githubusercontent.com/11865/175761449-2af6bfb6-c6e6-4a37-a7f0-87dbe4efa803.png">


EU Directives:
<img width="599" alt="Screenshot 2022-06-25 at 3 47 40 PM" src="https://user-images.githubusercontent.com/11865/175762048-4bac30e3-0b44-4575-8b8b-0e4a69fc96ac.png">
<img width="316" alt="Screenshot 2022-06-25 at 3 47 48 PM" src="https://user-images.githubusercontent.com/11865/175762054-c2fb178f-ae8f-454e-a93f-4d29570d4064.png">




Misc:
<img width="602" alt="Screenshot 2022-06-25 at 3 32 28 PM" src="https://user-images.githubusercontent.com/11865/175761542-0ce94d9c-d70b-4fb8-885f-a937df041d76.png">
<img width="598" alt="Screenshot 2022-06-25 at 3 32 38 PM" src="https://user-images.githubusercontent.com/11865/175761550-9c6c71c7-b9a2-4b10-a7da-1475313fd1b8.png">
<img width="602" alt="Screenshot 2022-06-25 at 3 43 48 PM" src="https://user-images.githubusercontent.com/11865/175761921-61707111-9c04-4489-bb86-cf731c610c97.png">
<img width="423" alt="Screenshot 2022-06-25 at 3 43 59 PM" src="https://user-images.githubusercontent.com/11865/175761926-8b00b21a-c26b-4ce0-b451-fec0f1ff80e7.png">

<img width="515" alt="Screenshot 2022-06-25 at 3 44 15 PM" src="https://user-images.githubusercontent.com/11865/175761935-2bb4fa79-5acf-4316-a38f-49e3765c8701.png">
<img width="285" alt="Screenshot 2022-06-25 at 3 44 23 PM" src="https://user-images.githubusercontent.com/11865/175761937-2eedae1c-412e-48ec-b0cf-5ee3d5d1960d.png">

<img width="598" alt="Screenshot 2022-06-25 at 3 45 24 PM" src="https://user-images.githubusercontent.com/11865/175761975-94e1360a-a4e7-40e6-a648-85ecf5b493c0.png">
<img width="464" alt="Screenshot 2022-06-25 at 3 45 32 PM" src="https://user-images.githubusercontent.com/11865/175761978-24b9e069-99ee-4183-b5bd-8596322a76dd.png">
<img width="453" alt="Screenshot 2022-06-25 at 3 46 11 PM" src="https://user-images.githubusercontent.com/11865/175761995-0361f1fe-b92d-4a8a-a2f0-993c65fd9519.png">

<img width="407" alt="Screenshot 2022-06-25 at 3 46 20 PM" src="https://user-images.githubusercontent.com/11865/175761998-2bcf9c5a-3da3-4f91-b886-77a3ebaa8470.png">

<img width="246" alt="Screenshot 2022-06-25 at 3 46 25 PM" src="https://user-images.githubusercontent.com/11865/175762000-55bdec41-f2ca-4ca8-aecf-97b571e16206.png">
<img width="199" alt="Screenshot 2022-06-25 at 3 46 34 PM" src="https://user-images.githubusercontent.com/11865/175762005-18b250ff-4aef-4b8a-9fcd-2a877f4f6473.png">

Custom footnotes:
<img width="355" alt="Screenshot 2022-06-25 at 3 49 32 PM" src="https://user-images.githubusercontent.com/11865/175762117-854ba6c3-952e-4c16-9dc8-651b161a266c.png">
<img width="260" alt="Screenshot 2022-06-25 at 3 50 04 PM" src="https://user-images.githubusercontent.com/11865/175762131-888075ae-5fbe-457e-a2ea-e9932ce70319.png">
<img width="287" alt="Screenshot 2022-06-25 at 3 50 19 PM" src="https://user-images.githubusercontent.com/11865/175762138-832138d9-f019-4828-8fe6-b5c4ee3aa1bb.png">
<img width="250" alt="Screenshot 2022-06-25 at 3 50 26 PM" src="https://user-images.githubusercontent.com/11865/175762144-13f8c886-86a6-4e1f-ad5f-0d57c5ba7ce7.png">

<img width="601" alt="Screenshot 2022-06-25 at 3 56 41 PM" src="https://user-images.githubusercontent.com/11865/175762399-6777124c-7558-48b2-b0c6-0dc739a0e776.png">
<img width="560" alt="Screenshot 2022-06-25 at 3 56 47 PM" src="https://user-images.githubusercontent.com/11865/175762400-877a253f-9a05-4fc6-ac6a-6a4e8d881d7e.png">
<img width="580" alt="Screenshot 2022-06-25 at 3 59 27 PM" src="https://user-images.githubusercontent.com/11865/175762498-6a7967a1-db61-4e2f-83fd-d5e87fd2abb3.png">


Withdrawn IEEE:
<img width="596" alt="Screenshot 2022-06-25 at 3 56 01 PM" src="https://user-images.githubusercontent.com/11865/175762381-fa3d4747-9f16-4c37-9488-a7e24d650aa6.png">

**Comment by opoudjis** [comment]
Formatting done. Footnotes are a separate issue.
