### ISSUE TITLE
Word output: commas between keywords missing in Word output

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#273]
on IEEE P2874 project, we received a comment that commas between keywords were not being shown.

i located the keywords in the p2874.adoc file in the github tree.
there are commas between them in the file. so i suspect the issue could be metanorma ieee template.

here are the samples from the current ([20230609](https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/5218178751)) generated version

ms-word output
![20230609_generate_ieee_p2874_ms-word_output](https://github.com/metanorma/metanorma-ieee/assets/35089343/d795bfea-94bc-42db-b9db-3e6bff01b2b5)

pdf output
![20230609_generate_ieee_p2874_pdf_output](https://github.com/metanorma/metanorma-ieee/assets/35089343/20e0bb46-37fe-44c0-b756-956b3eb80bfa)

the pdf output is right justified; i wonder if that should be removed, as the ms-word output looks more smooth?

**Comment by ronaldtse** [comment]
Thanks @ReesePlews ! IEEE has two master documents that determine the styling across the entire organization, but those documents are only available to us privately. We will have to check those to confirm. 

@opoudjis could you please help check them? Thanks!

**Comment by ReesePlews** [comment]
@ronaldtse thank you for checking into this, there are two more IEEE related issues i will be listing shortly...

**Comment by ronaldtse** [comment]
From master-1-standard:
<img width="468" alt="image" src="https://github.com/metanorma/metanorma-ieee/assets/11865/ca6c8a55-35d7-4b4e-aa14-f3f5a7d2aeca">

From master-2-standard:
<img width="407" alt="Screenshot 2023-06-09 at 7 35 59 PM" src="https://github.com/metanorma/metanorma-ieee/assets/11865/c7f899e6-3896-4ae2-881a-bf344c8b3908">

This is a bug in the Word output.

@opoudjis can you please help address this? Thanks.

**Comment by opoudjis** [comment]
Debugged HTML title page.
