### ISSUE TITLE
Draft number usage of root `.adoc` file

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#274]
in the IEEE P2874 project, i have recently discovered the p2874.adoc file

IEEE P2874 has changed to D3 (assumed this as draft 3) however the p2874.adoc file is showing the following

:draft: 2
:revdate: 2023-01-16
:copyright-year: 2022
:language: en

i wonder if this file should be updated to match D3 and a date (perhaps May 2023)?

**Comment by ronaldtse** [comment]
@ReesePlews yes I believe you should update it to:

```yaml
:draft: 3
:revdate: 2023-??-??
:copyright-year: 2023
```

With the `revdate` being the date you want to set.
