### ISSUE TITLE
duplicated text in the "Participants" section of an IEEE document

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#275]
in the IEEE P2874 project there was a comment regarding duplicated text of "Working Group" in the Participants section of the document.

this appears to be same in both the ms-word and pdf documents (as shown bellow)

ms-word
![20230609_generate_ieee_p2874_ms-word_output_participants_issue](https://github.com/metanorma/metanorma-ieee/assets/35089343/6fa2b715-7350-4931-9e5f-65b3a8203564)

pdf
![20230609_generate_ieee_p2874_pdf_output_participants_issue](https://github.com/metanorma/metanorma-ieee/assets/35089343/ddcf245d-f408-4f64-89bc-38567ca91b76)

i am thinking this issue probably comes from the p2874.adoc file..
`:working-group: Spatial Web Working Group`

current participants.adoc file:
```
== Participants


=== Working group
```

if it is as easy as editing out the duplicated text from either of the files please tell me and i will do that. in such a case, it may not be an issue, just a usage mistake with the content code.  thank you for checking this.

**Comment by ReesePlews** [comment]
in the p2874.adoc file which controls some parameters for the document project the phrase "Working Group" is repeated;

currently:
`:working-group: Spatial Web Working Group`

i think the correct value for this parameter should be:

`:working-group: Spatial Web`

i have made this change and will examine the generated document after the PR has been approved;

**Comment by ronaldtse** [comment]
Sorry @ReesePlews for missing this issue. @opoudjis can you please help with this ASAP? Thanks.

**Comment by ReesePlews** [comment]
@ronaldtse thank you for alerting @opoudjis about this; as a work around i just removed that "Working Group" text at the end, thinking that this may be more of a "function/feature" than an "issue/bug";   if it was "designed" to add the text "Working Group" on the end of what ever is the value for the ":working-group" tag, i am ok with this change; if the change is correctly interpreted in the current metanorma ieee release then perhaps question solved; if it is an "issue/bug" but is still "fixed" by the workaround, then there is less of a hurry to deal with the issue, in my opinion.

**Comment by opoudjis** [comment]
@ReesePlews You have inferred correctly; the predefined, templated text for participants reads:

````
At the time this draft {{ doctype }} was completed, the {{ working_group }} Working Group had the following membership
````

{{ working_group }} is the value given in `:working-group:`

The documentation is misleading about that (the example retains the string "Working Group"), and I am fixing it.

**Comment by ronaldtse** [comment]
> ```
> At the time this draft {{ doctype }} was completed, the {{ working_group }} Working Group had the following membership
> ```

@opoudjis I'd strongly suggest that we remove the "Working Group" assumption from the template because Working Group names do not necessary end with "Working Group".

e.g,. "Study Group".
https://standards.ieee.org/participate/

<img width="913" alt="Screenshot 2023-06-24 at 7 37 54 AM" src="https://github.com/metanorma/metanorma-ieee/assets/11865/bdb8cd85-e1c0-4a1d-8ef7-351cc9795deb">

**Comment by opoudjis** [comment]
OK then.
