### ISSUE TITLE
differences in labeling of terminological notes between PDF and MS-Word versions

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#280]
in the IEEE metanorma version (with a document generated 20230621) i am seeing differences between the labeling of notes in a terminological entry between the PDF output and an MS-Word output; as shown below...

PDF
![20230621_ieee_metanorma_pdf](https://github.com/metanorma/metanorma-ieee/assets/35089343/d0b7e01c-71f6-4118-a3a6-5697bc0afe37)

MS-Word
![20230621_ieee_metanorma_ms-word](https://github.com/metanorma/metanorma-ieee/assets/35089343/b6aa5f2e-33a3-4569-bbcf-5a3fcb82d26f)

i believe the PDF is correctly interpreting the IEEE style rules.

thank you for checking this.

**Comment by ronaldtse** [comment]
Thank you @ReesePlews for discovering this. The problem here is that term Notes are not being numbered properly (Note 2) in Word output.

@opoudjis can you please help with this ASAP? Thanks.

**Comment by opoudjis** [comment]
ΙΕΕΕ Word treats notes labels as lists. On opening the document, that particular style of list is not autonumbering, but restarting at 1 for each item; that is because the consecutive paragraphs are being assigned to separate underlying lists.

**Comment by opoudjis** [comment]
Logic error in identification of term notes sequences.
