### ISSUE TITLE
change of fonts in IEEE SA documents between sept 2023 and oct 2023 releases

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#305]
in the sept 2023 release of the IEEE template, (ms-word output) headings were in Arial bold and body text in Times New Roman. this has chnaged in the october 2023 release, looking a build of the document today, now seeing headings as Arial Black bold and body text as non-serif Claibri.

update: PDF output does not seem to have this issue. 

i think this is not correct and should be like the sept 2023 release with Arial bold and Times New Roman. could someone check this?
thank you.

Left (Sept 2023) - Right (Oct 2023)

![Screenshot (2266)](https://github.com/metanorma/metanorma-ieee/assets/35089343/e60ab14c-75eb-4bcd-b0af-63b9c77c047e)

**Comment by ronaldtse** [comment]
@ReesePlews thanks for reporting this! This is likely a regression due to the adding of the Whitepaper template.

For @opoudjis to action, thanks.

**Comment by ReesePlews** [comment]
@ronaldtse thanks for the quick follow up. i saw that @opoudjis was discussing the Whitepaper template. i am not familiar with that deliverable. we can use the PDF at this time, as it seems, perhaps the word-file has the issue. i have not checked the HTML, i dont use it so much, mostly use ms-word output. will keep a watch here for updates. appreciate that checking. thank you Nick!

**Comment by opoudjis** [comment]
Reese, I did ask you when I was working on it whether you would be using the White Paper template. The issue is specific to Word.

**Comment by ReesePlews** [comment]
hello @opoudjis sorry i did not see the earlier question. the current project is setup using the IEEE SA template, which existed for metanorma before the whitepaper template (in my understanding). at this time i do not have any need to use the whitepaper template.   when i work with output, i tend to check only the word and pdf output. i tend not to check the html output as it would not be a deliverable to the SDO; whereas word and/or pdf could.  sorry i could not answer before the close of the issue. thank you very much for fixing it, will look for that in the next release. really appreciate your work on this! thanks

**Comment by ReesePlews** [comment]
hello @opoudjis i just generated the IEEE-SA document we are working on and the font issue has not changed. was the docker image updated to reflect this change? i could only find something from 21 days ago, but i am not familiar how docker stuff works. if you could check this again it would be very helpful. thanks.

**Comment by opoudjis** [comment]
@CAMOBAP I am not familiar with docker either. Has last week's update gone live on docker yet? Last week's docker push appears to have failed: https://github.com/metanorma/metanorma-docker/actions . Am raising new ticket.

@ReesePlews For future reference: I have nothing to do with the docker process, so if a release has gone through on Github but you're not seeing it, please alert @CAMOBAP . I guess the easiest way is to compare the release number you're getting on docker with the latest in Github: as you can see from https://github.com/metanorma/metanorma-ieee , Metanorma-IEEE is on 1.1.4, and you've told me you are seeing on Docker 1.1.3. Allow a couple of days after Github release (Monday night) before reporting problems.

**Comment by CAMOBAP** [comment]
@opoudjis I can confirm that 1.8.6 available in docker hub https://hub.docker.com/r/metanorma/metanorma/tags

Update: 1.8.7 wasn't released, for some reason It reports "Could not find gem 'metanorma-cli (= 1.8.7)' in rubygems repository", the worflow did everything right, I have assumption that it happens to fast so rubygems returned Not found right after publishing, I have reported dedicated issues for this https://github.com/metanorma/metanorma-docker/issues/183

Docker release for 1.8.7 is started and will be available on Docker hub in a couple hours

@opoudjis @ReesePlews I will update you in this thread once release is available on Docker Hub

**Comment by CAMOBAP** [comment]
@ReesePlews 1.8.7 published

**Comment by ReesePlews** [comment]
hello @opoudjis and @CAMOBAP i appreciate you both following up on this. thank you. i understand also who to contact for future issues, that is helpful. 

in order to free up your time, is it possible to automate the docker hub process or are there too many manual steps involved?
i apologize for my lack of knowledge as i don't know the intricacies of doing all of the things the team does.  just thinking to make things easier for you.

i have checked the operation of the github process flow and the fonts have returned to normal so the new version is being accessed correctly.  

thank you both for taking care of this.

**Comment by CAMOBAP** [comment]
@ReesePlews actually docker release is automated (once metanorma-cli gem released, docker release will be started automatically) but from time to time we are still facing some issues in it.

For example this time docker failed because the docker release happened "too fast", i.e. after publishing metanorma-cli to rubygem.org, for some reason on docker workflow rubygems.org responded with "Gem not found". This is the first such case after dozens of successful releases

While we are still improving the release process, most of the time is pretty stable

In case of any issues, please report an issue to https://github.com/metanorma/metanorma-docker and assign to me

**Comment by ReesePlews** [comment]
thank you @CAMOBAP i appreciate the update on why things may not have been working. 
i will remember to ask you if we have a similar problem. i will not be able to assign you but i can mention you in the issue. thank you and Nick for quickly taking care of these things.
