### ISSUE TITLE
bibliography rendering differences between ms-word and pdf on entry numbers larger than 99 

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#321]
i am noticing some rendering differences between ms-word and pdf for biblographic entry numbers above 99

version information

> Metanorma 1.6.7
> Metanorma::Cli 1.8.9
> Metanorma::Standoc 2.7.0/IsoDoc 2.7.1
> Metanorma::ISO 2.6.0
> Metanorma::Iec 2.3.5
> Metanorma::IEEE 1.1.7

ms-word
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/276ddf38-077f-488b-b3a3-084387e20495)

pdf
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/01f2d42c-bb67-4994-84f8-aecc262decd2)

i am not sure why the order of the entries different. it could be another error i am not finding but that is not what i am showing in this issue.

thank you for checking this when there is time.

**Comment by opoudjis** [comment]
I cannot replicate. Compiled on latest Main branch of SWF-Corpus_and_IEEEP2874-D2

![Screenshot 2023-12-08 at 22 27 42](https://github.com/metanorma/metanorma-ieee/assets/1911039/e0c6bfa8-3f94-4c4e-b872-912f261ec976)

**Comment by ReesePlews** [comment]
@opoudjis thank you for checking this. in your image you posted, i can see the spacing problem starting at line 28 in the pdf (file on the left). there is no space between the [B100] and "Otto, B., M...."  so it looks like [B100]Otto.
whereas the PDF has a tab between the [B100] and Otto; sorry if i was unclear in the initial post.

**Comment by opoudjis** [comment]
Right, I thought you were pointing to actual discrepancies in numbering. OK, that is a PDF-specific issue, passing to @Intelligent2013 : this appears to be simply a matter of allowing a bit more space...

**Comment by Intelligent2013** [comment]
IEEE XSLT updated:
![image](https://github.com/metanorma/metanorma-ieee/assets/5559926/ae4fcd31-6c58-4630-8da5-034a4684d50a)

**Comment by ReesePlews** [comment]
@opoudjis thanks for looking into this...

> Right, I thought you were pointing to actual discrepancies in numbering. OK, that is a PDF-specific issue, passing to @Intelligent2013 : this appears to be simply a matter of allowing a bit more space...

i should have indicated the issue on the image with a mark or box. sorry for the extra work to identify the issue.

@Intelligent2013 thank you very much for fixing this. i will check in the next release.

**Comment by opoudjis** [comment]
The release should be available over the next day or so, and we were hoping to get it out before Christmas, but it's unclear now when it will be, given that new issues (yet again) have cropped up. Keep a lookout for 1.8.11 on https://github.com/metanorma/metanorma-docker/actions

**Comment by ReesePlews** [comment]
thank you @opoudjis , i will be on the lookout for it. appreciate your and the team's diligence on this issue.
