### ISSUE TITLE
(URGENT) PDF: page break should exist between "Introduction" and "Contents" (the TOC)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#33]
From the Word template:
<img width="1096" alt="Screenshot 2022-06-22 at 1 46 03 AM" src="https://user-images.githubusercontent.com/11865/174854027-b3cbc7cb-ac5d-4e81-8599-c35eec2c1488.png">

Now:
<img width="529" alt="Screenshot 2022-06-22 at 1 46 16 AM" src="https://user-images.githubusercontent.com/11865/174854062-76e5db74-9615-407f-81e5-8fe99d9916f4.png">

**Comment by Intelligent2013** [comment]
@ronaldtse could you provide the presentation xml, please? I don't see the section 'Introduction' at all in SWF-Corpus_and_IEEEP2874-D2. Thanks.
Or point me to right repo/branch.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/174878802-b341f3ca-929a-40b4-90b3-9b7d463102c9.png)

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks!
<img width="493" alt="Screenshot 2022-06-23 at 2 07 07 AM" src="https://user-images.githubusercontent.com/11865/175096639-42ad9c2c-1f5a-40ce-a3a8-d62eee2b717f.png">
