### ISSUE TITLE
Rendering of IEV term source broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#340]
Clause 3 term reference to the IEV leads to a broken rendering.

Source:
```
[.source]
<<ievterms,clause=102-03-19>>, Note 1 has been modified. Note 2 has been added.
```

Rendered as:
![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/3b42a945-9a46-4e93-89a8-12dad419eb61)

It should probably render as "([B1], 102-03-19, modified...)"

_Originally posted by @ReesePlews in https://github.com/metanorma/metanorma-ieee/issues/337#issuecomment-1935871185_

**Comment by opoudjis** [comment]
Markup error.

By default, `<<ref,clause=1-2>>` is interpreted as the range clause 1 to 2. To prevent such an interpretation, the clause designation needs to be put in quotes, so it is interpreted as a unitary entity: `<<ref,clause="1-2">>` 

Most examples in documentation put the clause in quotes, but I'm seeing that one or two don't; and an expression with two hyphens cannot reasonably be interpreted as a range anyway. I am going to fix the examples and  add a note that the quotes are needed; but I'm also going to emend input  to treat a clause reference of type a-b-c as not a range anyway.
