### ISSUE TITLE
IEV bibliographic entry out of order in bibliography

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#341]
The bibliography entry of IEV is out of order and renders like this:

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/c227ee9a-1626-439b-957d-0b36baee5a09)

_Originally posted by @ReesePlews in https://github.com/metanorma/metanorma-ieee/issues/337#issuecomment-1935871185_

**Comment by opoudjis** [comment]
Already fixed in https://github.com/metanorma/metanorma-ieee/issues/338
