### ISSUE TITLE
PDF failure in mn-samples-ieee-private blocking Metanorma release

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ieee#347]
https://github.com/metanorma/metanorma-cli/actions/runs/7960148464/job/21734108792

https://github.com/metanorma/mn-samples-ieee-private

samples/sources/1127/document.adoc
samples/sources/2830/document.adoc
samples/sources/p2830_d1/document.adoc

**Comment by Intelligent2013** [comment]
I can't generate the presentation XML.

```
git clone https://github.com/metanorma/mn-samples-ieee-private
cd mn-samples-ieee-private
bundle update
cd sources/1127
```
```
bundle exec metanorma -t ieee -x presentation document.adoc 
```

```
Style: (ID _23a9e27a-2c32-bcbc-1e8d-0df8d834c9e6): no space before percent sign: 0.5%
Style: (): Expected title to start as: Guide
Style: (): Title contains uncapitalised word other than preposition
Style: (ID NESC): Normative reference NESC is not dated.
Style: (ID _magnetic_field_measurements): More than 1 ordered list in a numbered clause
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.2.2/lib/isodoc/ieee/presentation_ref.rb:75:in `bibliography_bibitem_number1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_function/refs.rb:89:in `block in bibliography_bibitem_number'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_function/refs.rb:88:in `bibliography_bibitem_number'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_function/refs.rb:4:in `references'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_xml_convert.rb:51:in `section'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.2.2/lib/isodoc/ieee/presentation_xml_convert.rb:124:in `section'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_xml_convert.rb:42:in `conversions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_xml_convert.rb:25:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/convert.rb:155:in `convert'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.2.2/lib/metanorma/ieee/processor.rb:49:in `output'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:170:in `process_output_unthreaded'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:156:in `process_exts1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:130:in `process_ext'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:112:in `block in process_exts_run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:111:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:111:in `process_exts_run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:106:in `process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:36:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/compiler.rb:30:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/compiler.rb:35:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:244:in `compile_document'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:48:in `block in compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:48:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:48:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli.rb:34:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/exe/metanorma:25:in `block in <top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/exe/metanorma:43:in `<top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<main>'
undefined method `previous=' for nil:NilClass
bibitem.at(ns(".//docidentifier")).previous =
^^^^^^^^^^^
```


I'll try to omit the bibliography sections.

**Comment by Intelligent2013** [comment]
The presentation XML generated successfully without
```
// include::sections/02-norm-refs.adoc[]
...
// include::sections/aa-bibliography.adoc[]
```


and PDF renders ok:
![image](https://github.com/metanorma/metanorma-ieee/assets/5559926/0e962c1f-f254-44c0-9346-34d4f6700aaf)

**Comment by Intelligent2013** [comment]
1127 generation also stops at XML generation in https://github.com/metanorma/metanorma-cli/actions/runs/7960148464/job/21734108792

Will try with 2830.

**Comment by Intelligent2013** [comment]
I have the same error:
```
Error while rendering page 16. Reason: java.lang.RuntimeException: org.apache.fop.render.intermediate.IFException: I/O error flushing the PDF document
java.lang.RuntimeException: org.apache.fop.render.intermediate.IFException: I/O error flushing the PDF document
	at org.apache.fop.render.intermediate.IFRenderer.handleIFException(IFRenderer.java:195)
	at org.apache.fop.render.intermediate.IFRenderer.drawImage(IFRenderer.java:1304)
	at org.apache.fop.render.intermediate.IFRenderer.renderImage(IFRenderer.java:1288)

```

I didn't see it before.

**Comment by Intelligent2013** [comment]
Something wrong in the Figure 1:
```xml
<figure id="fig1">
					<name>Figure 1—TEE-based SML Architecture framework</name>
					<image src="data:image/png;base64,iVBORw0KGgo...
```
Base64 to PNG renders ok in XnView:
![image](https://github.com/metanorma/metanorma-ieee/assets/5559926/1ffb4b3c-b085-4909-9177-c409ca3b9a41)

I've found the `document.pdf.err` generated in December, 2022, and it contains another warning:
```
Image warning. Reason: Image data:image/png;base64,iVBORw0KGgoAAA/... has an incompatible color profile. The color profile will be ignored.
Color model of loaded bitmap: ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@7fa817ba transparency = 1 has alpha = false isAlphaPre = false
Color model of color profile: ColorModel: #pixelBits = 32 numComponents = 4 color space = java.awt.color.ICC_ColorSpace@1251cdec transparency = 1 has alpha = false isAlphaPre = false (No context info available)
```
May be it showed on the previous versions of Apache FOP...

I'll try to re-save the png.

**Comment by opoudjis** [comment]
> I can't generate the presentation XML.
> 
> ```
> git clone https://github.com/metanorma/mn-samples-ieee-private
> cd mn-samples-ieee-private
> bundle update
> cd sources/1127
> ```
> 
>  ```
> bundle exec metanorma -t ieee -x presentation document.adoc 
> ```
> 
>  ```
> Style: (ID _23a9e27a-2c32-bcbc-1e8d-0df8d834c9e6): no space before percent sign: 0.5%
> Style: (): Expected title to start as: Guide
> Style: (): Title contains uncapitalised word other than preposition
> Style: (ID NESC): Normative reference NESC is not dated.
> Style: (ID _magnetic_field_measurements): More than 1 ordered list in a numbered clause
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.2.2/lib/isodoc/ieee/presentation_ref.rb:75:in `bibliography_bibitem_number1'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_function/refs.rb:89:in `block in bibliography_bibitem_number'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_function/refs.rb:88:in `bibliography_bibitem_number'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_function/refs.rb:4:in `references'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_xml_convert.rb:51:in `section'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.2.2/lib/isodoc/ieee/presentation_xml_convert.rb:124:in `section'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_xml_convert.rb:42:in `conversions'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/presentation_xml_convert.rb:25:in `convert1'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.8.4/lib/isodoc/convert.rb:155:in `convert'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.2.2/lib/metanorma/ieee/processor.rb:49:in `output'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:170:in `process_output_unthreaded'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:156:in `process_exts1'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:130:in `process_ext'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:112:in `block in process_exts_run'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:111:in `each'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:111:in `process_exts_run'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:106:in `process_exts'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.7.1/lib/metanorma/compile.rb:36:in `compile'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/compiler.rb:30:in `compile'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/compiler.rb:35:in `compile'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:244:in `compile_document'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:48:in `block in compile'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:48:in `each'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli/command.rb:48:in `compile'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/lib/metanorma/cli.rb:34:in `start'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/exe/metanorma:25:in `block in <top (required)>'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.9.1/exe/metanorma:43:in `<top (required)>'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `load'
> C:/tools/ruby31/lib/ruby/gems/3.1.0/bin/metanorma:25:in `<main>'
> undefined method `previous=' for nil:NilClass
> bibitem.at(ns(".//docidentifier")).previous =
> ^^^^^^^^^^^
> ```
> 
> I'll try to omit the bibliography sections.

I've done  a push to metanorma-ieee main branch that works around that issue.

**Comment by Intelligent2013** [comment]
Two years ago version Apache FOP just outputs this warning and generates the PDF:
```
Image warning. Reason: Image data:image/png;base64,iVBORw0KGgoAAA/... has an incompatible color profile. The color profile will be ignored.
```
but the latest crashes:
```
Error while rendering page 16. Reason: java.lang.RuntimeException: org.apache.fop.render.intermediate.IFException: I/O error flushing the PDF document
java.lang.RuntimeException: org.apache.fop.render.intermediate.IFException: I/O error flushing the PDF documen
```

I've tried to re-save Figure 1 png and PDF generates successfully now.
Checking another png...

**Comment by Intelligent2013** [comment]
@opoudjis I've fixed the images in the repository https://github.com/metanorma/mn-samples-ieee-private.
