### ISSUE TITLE
Word: remove antiquated styles: IEEEStds Sans-Serif, IEEEStds InstrCallout, IEEEStds Para8.5, IEEEStds Para8.5 Indent

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#36]
Remove antiquated styles: 
* IEEEStds Sans-Serif
* IEEEStds InstrCallout
* IEEEStds Para8.5
* IEEEStds Para8.5 Indent

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ieee/issues/34#issuecomment-1163835289_

**Comment by opoudjis** [comment]
Already done.
