### ISSUE TITLE
Bibliographic item rendering of "Available at..." should not appear in inline links

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#366]
Source:
https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/1460

**Comment by ReesePlews** [comment]
see updates to  https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/1460

**Comment by opoudjis** [comment]
I'm confused by this ticket, it appears to have been overtaken by events...

**Comment by ReesePlews** [comment]
we discussed the contents in the "span" statements and making some changes to those, indeed changed the styling of the entries. i dont know what is best, to close or keep this issue. its up to you.

**Comment by opoudjis** [comment]
I'm closing it.
