### ISSUE TITLE
IEEE editorial review: undated normative references?

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#367]
i am trying to add undated normative reference in an IEEE-SA document, but i am having difficulty finding much information about the notation for normative references. does the IEEE-SA flavor support undated normative references and/or undated bibliographic references.

mostly these are for ISO, IEC or IEEE references within an IEEE standard. 

thank you

**Comment by ronaldtse** [comment]
Background: IEEE editorial has stated that some IEEE standards in the normative references should be undated. 

Problem: Metanorma / Relaton does not seem to allow the dated / undated reference differentiation as we have in ISO / IEC standards.

@andrew2net could you help check how we should do that?

**Comment by andrew2net** [comment]
@ReesePlews we are working on the IEEE references' notation. For now, it's possible to omit a date at the end of a reference. For example, you can use `IEEE 1003.13` to refer document `IEEE 1003.13-1998`.

**Comment by ReesePlews** [comment]
@andrew2net thank you for the info, i will try this workaround and let you know the result.

**Comment by ReesePlews** [comment]
thank you @andrew2net this did seem to work correctly on ISO/IEC entries. i did not try on the other ones. i will close the ticket. thanks again for your help!
