### ISSUE TITLE
Word: Apply "IEEEStds Sponsor (body text)" style to the Society name on the title page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#37]
Apply "IEEEStds Sponsor (body text)" style to the Society name on the title page.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ieee/issues/34#issuecomment-1163835289_

**Comment by opoudjis** [comment]
The template does NOT use this style. But then, I am no longer surprised.

**Comment by ronaldtse** [comment]
It really does not seem this style applies here.

<img width="1184" alt="Screenshot 2022-06-28 at 1 21 22 AM" src="https://user-images.githubusercontent.com/11865/175988552-d7f78c31-b289-462e-ade9-fd3319093572.png">
