### ISSUE TITLE
differences in line spacing in clauses (x, x.1) between PDF and MS-Word versions

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#371]
hello @opoudjis and @ronaldtse 

i am seeing the following differences between clause/subclause (x, x.1) line spacing the in the current IEEE template.

pdf left, ms-word right

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/41c3bf1f-b5e4-4915-b205-cfef2fcd785e)

mn code details are:

```
Run metanorma --version
Metanorma 1.7.7
Metanorma::Cli 1.9.8
Metanorma::Standoc 2.8.9/IsoDoc 2.10.2
Metanorma::ISO 2.7.8
Metanorma::Iec 2.4.7
Metanorma::IEEE 1.2.8
...
```

if you need the files please let me know. thank you for checking this.

**Comment by opoudjis** [comment]
... Which one is the right one?

**Comment by ReesePlews** [comment]
i would say the example on the right (the ms-word render) is the correct render, the spacing looks more appropriate then the PDF on the left.

**Comment by opoudjis** [comment]
@Intelligent2013 Over to you :)

**Comment by Intelligent2013** [comment]
The XSLT for the PDF generation developed based on the sample from the ticket https://github.com/metanorma/metanorma-ieee/issues/11.
Currently, the line spacing in the rendered PDF (by Metanorma) is the same as in the sample [IEEE%20P802.1DF:D0.0.pdf](https://github.com/metanorma/ieee-ref-docs/blob/main/standards/IEEE%20P802.1DF:D0.0.pdf).

Left pane - generated PDF by Metanorma, right pane - original sample PDF:

![image](https://github.com/metanorma/metanorma-ieee/assets/5559926/b3a82855-a4e5-435e-a145-e78c85f4365f)

@ReesePlews @ronaldtse  after all, should I decrease the line spacing in the PDF?

**Comment by ReesePlews** [comment]
hi @Intelligent2013 thank you for checking this. i understand better now, why it is set this way however i think the two sample standards you may  be using are old. please try and find a newer standard.

this is an example of an IEEE standard from 2020

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/d80f2365-389b-4518-b45b-3448ec62794f)

this is an example of an IEEE standard from 2022

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/60b05272-e20b-40ee-b2d6-76cb7ae46ac7)

i believe there are some open IEEE standards available at:
https://ieeexplore.ieee.org/browse/standards/get-program/page

**Comment by ronaldtse** [comment]
The PDF layout and Word masters are officially from IEEE master documents. We should not change anything until we have official IEEE notice that they have changed masters.

**Comment by Intelligent2013** [comment]
Ok, then close the ticket.

**Comment by ReesePlews** [comment]
see related https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/1549
could not be confirmed as to what was correct or not.
