### ISSUE TITLE
Review compatibility with 2024 IEEE Word template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#372]
This task is to review compatibility with the 2024 IEEE Word template.

[wordtemp.zip](https://github.com/user-attachments/files/15521102/wordtemp.zip)

You will want to check the DOCX files under: `DOCX_NO_MACROS/`.

**Comment by opoudjis** [comment]
Boilerplate updated. The stylesheets turn out to be identical, which is consistent with the report from IEEE that they've been unable to update their macros in Word, implying that they are not updating their stylesheet.
