### ISSUE TITLE
question: update to 1.10.0 gives error on github during generate

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#376]
hello @opoudjis @ronaldtse 

in checking the generate logs in the IEEE project on github, an error is not happening after the update to mn 1.10.0

for the past week the IEEE project switched bake to the "latest" version in the generate workflow file. since then, i am quite sure the project team did not make any changes to workflow files. 

however, within the last 10 hours or so, generate processes using the following versions:

```
Run metanorma --version
Metanorma 2.0.0
Metanorma::Cli 1.10.0
Metanorma::Standoc 2.8.10/IsoDoc 2.10.3
Metanorma::ISO 2.7.9
Metanorma::Iec 2.4.8
Metanorma::IEEE 1.2.9
Metanorma::Ietf 3.3.7
Metanorma::Generic 2.6.4
Metanorma::BIPM 2.4.8
Metanorma::CC 2.4.8
Metanorma::Csa 2.4.8
Metanorma::IHO 0.9.8
Metanorma::JIS 0.2.9
Metanorma::UN 0.12.10
Metanorma::Ogc 2.5.9
Metanorma::ITU 2.4.8
```

are now giving the following error:

```
...
/bin/tar -xf /__w/_temp/f71f0199-4d83-452f-be1b-5d8c8e6a3dfa/cache.tgz -P -C /__w/SWF-Corpus_and_IEEEP2874-D2/SWF-Corpus_and_IEEEP2874-D2 -z
Received 54177986 of 54177986 (100.0%), 25.8 MBs/sec
Cache restored successfully
Cache restored from key: metanorma-fontist
Run actions/cache@v3
/usr/bin/docker exec  006f367ad2c00d6768a4aa97aae7244dfcda570a5f3eadb2f236d677c03472b5 sh -c "cat /etc/*release | grep ^ID"
Cache not found for input keys: metanorma-ietf-workgroup-cache, metanorma-ietf-workgroup-cache
Run actions-mn/site-gen@v1
Run cd .
ERROR: "metanorma site generate" was called with arguments [".", "--no-no-install-fonts"]
Usage: "metanorma site generate [SOURCE_PATH]"
Error: Process completed with exit code 1.
```

i do notice the "--no-no-install-fonts"  argument... it looks a bit strange with the "double negative" there.

i have added a couple of comments on [this PR](https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/1610). 

if this is something we can take care of please let me know how to fix this, or if we should drop back to mn 1.9.8. 

thank you.

**Comment by ReesePlews** [comment]
hi @opoudjis i see this message in the [metanorma release discussion](https://github.com/orgs/metanorma/discussions/6#discussioncomment-9656689)

```
Compilation
    Change --no-prefix, --no-install-fonts flags to --prefix, --install-fonts
```

i guess this could be the issue?  but i am not seeing this in the workflow file. perhaps it is somewhere else?

**Comment by CAMOBAP** [comment]
Long story short:
- for metanorma < 1.10.0 we should use `@v1` version of actions.
- for metanorma >= 1.10.0 we should use `@v2` or `@main` version of actions

Fixed for:
- [x] `build-and-publish`
- [x] `site-gen`
- [ ] `compile` _in progress_
- [ ] `cli` _in progress_

Tested on:
 - https://github.com/metanorma/iso-19135/actions/runs/9377121970/job/25821510235
 - https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

**Comment by ReesePlews** [comment]
thank you @CAMOBAP and after the two in progress jobs are completed, do i need to update anything in my repos or will it just work if i generate the document?

**Comment by CAMOBAP** [comment]
> thank you @CAMOBAP and after the two in progress jobs are completed, do i need to update anything in my repos or will it just work if i generate the document?

@ReesePlews  It depends on which version is specified in your workflow file.

If it's `@v1` you definitely have to modify it to `v2`.
If it's `@main` you can simply re-run your workflow and it should be fixed

**Comment by ReesePlews** [comment]
question, why would the generate files be different in each repo?  would it not be better to change everything to `@main` for this statement?

**Comment by CAMOBAP** [comment]
> question, why would the generate files be different in each repo?

Some of our client updates may decide to stay on an old version (because of flavor support). This is why we should have this flexibility

For the repo that is managed by `metanorma` Github Organisation we usually preferred `@main`. But for clients, it actually depends as I noted above.

If you are always using latest version `@main` is probably a better option for you.

**Comment by CAMOBAP** [comment]
@ReesePlews you are welcome.

Also regardless of this failure. Sticking to a specific version is generally considered as a more stable approach (especially in the case when metanorma version being freezed/stable)

**Comment by ReesePlews** [comment]
hello @CAMOBAP i made a PR to change the IEEE project (shown above) to use v2 and it seems ok, no tool issues.  thank you for telling me how to change this. i am sure a lot of people may not know why there are issues all of a sudden. i am ok for you to close this ticket unless you want to add anything here. thanks again!

**Comment by CAMOBAP** [comment]
Fixed in all actions
