### ISSUE TITLE
word "Abstract" missing in word file, but present in PDF

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#379]
hello @opoudjis in the front matter of the document, there is the Abstract and at the start of that the word "**Abstract**:" is in bold.  however in the ms-word file, that word is missing.

the current version of metanorma was used in the generation of this file between the June 3 and June 10.

details are shown here:  https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874/issues/1616

if you can check into this at your convenience that would be helpful. thanks

**Comment by opoudjis** [comment]
Was inserting "Abstract:" header when the document scope was being presented as the abstract, but not when a discrete abstract was included. Not seeing a good reason for the distinction, getting rid of it.
