### ISSUE TITLE
question: landscape page orinetation for a single page in all document outputs

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#381]
hello @opoudjis i have a question about landscape page mode for a single page with a large figure, and wondering if that is now working in all document output types, such as PDF or possibly HTML. the link below says that MS-Word output is possible.

https://www.metanorma.org/author/topics/document-format/page-flow/

we have a large figure that is landscape mode and would like to rotate the page the figure is on.  IEEE style manual appears to support landscape orientation.  would you advise rotating the page or rotating the image?

**Comment by ReesePlews** [comment]
@ronaldtse at your convenience, can you take a look at this and advise on how to handle it. i am currently leaning to a rotation of the image, rather than the page. thanks

**Comment by ronaldtse** [comment]
Metanorma does not support image rotation, so the easiest way to rotate an image is to do it in the image itself.

**Comment by ReesePlews** [comment]
thank you @ronaldtse i was planning to rotate the image outside of metanorma. i should have specified that in my earlier post. thank you for the confirmation.

**Comment by opoudjis** [comment]
@ReesePlews @ronaldtse Is this query still open?

**Comment by ReesePlews** [comment]
sorry for not following up on this issue. @opoudjis lets close this now. the PR was closed and if we felt landscape mode on one or more pages was needed, then we should examine that in a new issue and discuss more. at this time, the issue with the strange image was solved. closing this.
