### ISSUE TITLE
(URGENT) Word and PDF support of linked terms in IEEE as "See:" relationship

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#39]
In the IEEE 2021 style manual, linked terms are shown in bold as a "See:" relationship:

<img width="529" alt="Screenshot 2022-06-27 at 10 39 28 AM" src="https://user-images.githubusercontent.com/11865/175844628-2112b62f-7369-43a8-b8e0-1f77f79dfd53.png">

In Metanorma, the linked terms are in italics and provide a text "[term defined in XXX]", but this additional text should not be shown.

PDF:
<img width="478" alt="Screenshot 2022-06-27 at 10 40 11 AM" src="https://user-images.githubusercontent.com/11865/175844675-0b01991f-1249-4b78-ab4e-87f1426aa34d.png">

Word:
<img width="666" alt="Screenshot 2022-06-27 at 10 42 53 AM" src="https://user-images.githubusercontent.com/11865/175844920-2b736526-a92b-4d42-a42d-1ec72c846441.png">

I believe this is a Metanorma Presentational XML (and downstream) issue?

**Comment by Intelligent2013** [comment]
> I believe this is a Metanorma Presentational XML (and downstream) issue?

@ronaldtse yes, the term enclosed in `em` and there is a text ` [term defined in `:
presentation xml:
```xml
<term id="term-activity">
	<p>
		<strong>activity</strong>: strictly defined series of 
  <em>actions</em> 
  [term defined in <xref target="term-action">3.1.1</xref>]
 to be performed by a 
  <em>Spatial Web Domain</em> 
  [term defined in <xref target="term-Spatial-Web-Domain">3.1.43</xref>]
</p>
...
```

**Comment by opoudjis** [comment]
Stepping back: we will:

* Support both related  terms and concepts in Metanorma
* Indicate which flavours support one to the exclusion of the other
* Mark up in this instance both concepts and related terms; IEEE will only support the latter (and ISO only the former)

**Comment by opoudjis** [comment]
But note that Alt and Deprecated are in fact Related terms: we will support Alt and Deprecated in ISO, but no other relations: https://github.com/metanorma/metanorma-standoc/issues/642

**Comment by opoudjis** [comment]
So initial step: concept links are NOT supported in IEEE. Related terms are NOT supported in ISO and inheritors, other than equivalent/alt and deprecates/deprecated.

**Comment by ronaldtse** [comment]
I think we should have a concept relationship support compatibility table on the metanorma.org site, like they do with https://caniuse.com as for HTML, https://caniuse.com/css-container-query-units 
<img width="1174" alt="Screenshot 2022-07-04 at 10 16 21 PM" src="https://user-images.githubusercontent.com/11865/177162634-3e7e24e9-ac0f-4efe-8a32-f53587beab7c.png">

**Comment by opoudjis** [comment]
And:

````
Note that concept relations are NOT supported in ISO, or flavours derived from ISO (IEC, BSI).
However, admitted and deprecated designations are supported in ISO.
````
