### ISSUE TITLE
Word: line height incorrect in unordered lists compared with body text

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#396]
in a recent document using the IEEE template, i am noticing this difference in the line height.  is this correct line height spacing for body paragraphs and unordered lists? @opoudjis @ronaldtse please check at your convenience. thank you

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/204c328d-50e6-4c59-9af5-c3da7ce623fb)

**Comment by ReesePlews** [comment]
with a bit more checking... generate "main" on 2024-07-03 with mn versions:

```
Run metanorma --version
Metanorma 2.0.1
Metanorma::Cli 1.10.1
Metanorma::Standoc 2.8.11/IsoDoc 2.10.4
Metanorma::ISO 2.7.10
Metanorma::Iec 2.4.9
Metanorma::IEEE 1.2.10
```

as shown below, the PDF output seems ok, but the MS-Word output does not. 

**PDF output**

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/74412141-cfb2-4c12-8b61-0ceefcaef3be)

**MS-Word output (appears to still have an issue)**

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/84582369-bab1-4f38-8efe-0b91778811fd)

**Comment by ronaldtse** [comment]
Thanks @ReesePlews . We still need to investigate the changes in the latest 2024 template (#372), in addition to this. 

@opoudjis is on holiday and this will be fixed possibly next week.

**Comment by opoudjis** [comment]
The Word list style is EXACTLY how the style IEEEStds Unordered List is defined in IEESTD-WORDTEMPLATE_v1_2022.doc. The IEEE Numbered List Level n styles are also defined to have that line spacing.

The 2021 Style Manual does not have those line spacings. But I am not going to overrule the Word template provided by IEEE. And those are the only styles in the Word Template that support the dash bullets and letter-first numbered lists of IEEE.

This line spacing also applies to the 2024 template.

I will not be changing the line spacing of lists in the template without EXPLICIT instruction from IEEE editorial staff. That is how their official supplied Word template styles lists. If they have not fixed this issue in the past five years, I will not do so preemptively.

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for checking and explaining this.  @ronaldtse has been communicating with IEEE for other/additional samples.  the document i am working on has just finished ballot and will go to the revision committee to handle the comments. after that IEEE/SA will, i assume, handle any final style issues. i will keep you and Ron informed of the status.  thank you.

**Comment by opoudjis** [comment]
I will say, it is very strange that both the 2022 and the 2024 template have this spacing, but the sample documents do not. But I can't change the template without instruction: this was done by IEEE deliberately.

The 2024 template does not include a list, which may be why they have not noticed this. But surely they receive any number of submissions with the spaced lists...

**Comment by ronaldtse** [comment]
I have inquired IEEE Patrick Gibbons directly about this issue. We should not change IEEE's Word template without their confirmation.

**Comment by opoudjis** [comment]
Response was to leave this alone; they routinely fix this at the end of editing internally, and they don't have access to a developer to fix their template.
