### ISSUE TITLE
(URGENT) Word and PDF: "NOTE" format in Definitions clause not according to 2021 Style Manual

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#40]
In the 2021 Style Manual, a term "NOTE" looks like this:

<img width="427" alt="Screenshot 2022-06-27 at 10 41 23 AM" src="https://user-images.githubusercontent.com/11865/175844788-d05057ce-d122-4f6e-b83b-55d58187d1d9.png">

Generated PDF:
<img width="488" alt="Screenshot 2022-06-27 at 10 41 37 AM" src="https://user-images.githubusercontent.com/11865/175844812-af707425-f878-47ea-9725-73baa3779a82.png">

Generated Word:
<img width="718" alt="Screenshot 2022-06-27 at 10 42 10 AM" src="https://user-images.githubusercontent.com/11865/175844863-7630cf65-9f51-424f-90db-ea5376336ab8.png">

**Comment by Intelligent2013** [comment]
IEEE xslt updated:
![image](https://user-images.githubusercontent.com/5559926/175925348-395f9dc8-9fcd-46c7-ba77-a556e2af6c09.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by ronaldtse** [comment]
<img width="845" alt="Screenshot 2022-06-29 at 3 05 57 PM" src="https://user-images.githubusercontent.com/11865/176363427-d9c7cfa8-2f75-468c-847a-09cc9b3d0869.png">

Confirm fixed in Word. Thanks @opoudjis !
