### ISSUE TITLE
list of figures and list of tables are not generating or updating correctly in the MS-Word output 

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#404]
hi @ronaldtse can you check about list of figures and tables generated for the document. i see this notation in the p2874.adoc file:

```
:toc-figures: true
:toc-tables: true
```

however when try to update the list of figures and tables in the generated MS-Word file, they do not update correctly. i think they were updating a few months back, but not now.  

they are generating correctly in the PDF, so i dont think it is the notation above, but more likely the MS-Word file. the table of contents in the word file generates correctly when updating in MS-Word.

if someone can have a look at this, it would be helpful.  thank you

**Comment by ReesePlews** [comment]
hello @opoudjis sorry to bother you with this, but if you can check this issue and see what may be the cause it would be very helpful. thank you

**Comment by ReesePlews** [comment]
hi @opoudjis thanks for checking into this. it is a "show stopper" issue and requires finalizing the document in ms-word, redoing the list of tables and list of figures by hand which is very time consuming. we did not have problems to generate directly from the metanorma output a couple releases back... the issue is still present in the current release (2024-08-07  - 1.10.4 & 1.10.5) ; will watch for an update. if you have questions, please let me know. thank you.

**Comment by opoudjis** [comment]
I've had a lot on, including the hotfix for 1.10.5. Looking at this now.

**Comment by opoudjis** [comment]
Confirmed.

That's surprising. Will investigate today.

**Comment by opoudjis** [comment]
I've found what it is, and I'm surprised we haven't found it before now.

Table and Figure ToCs are built based on CSS style. The CSS style is being specified with the style's machine readable name, IEEEStdsRegularTableCaption. It needs to be specified with its human readable name instead, "IEEEStds Regular Table Caption".

There's also some issue with tab and dash showing up unexpectedly when I do the update, which may mean rearranging the caption contents.

**Comment by opoudjis** [comment]
I will get to this tonight. @ReesePlews are you able to work with code pulled from GitHub? I can compile the document for you if not.

**Comment by ReesePlews** [comment]
hello @opoudjis appreciate you checking on this. i can do a local generate, if that is what you mean in your last comment. when we try to "update" those lists using ms-word a popup is given and the list is not generated. 

![image](https://github.com/user-attachments/assets/2c1d63e0-2559-43a7-bbed-830f1f67cee3)

if you need more info let me know.  with the .doc the first thing i do is save it as a .docx. when i do a "save as" in ms-word it always seems to default as an .mhtml file. after the doc is in .docx format i try to generate the list of tables and lists of figures.

i am not sure if this is happening on the iso flavor, i am typically not using list of tables or list of figures in those documents.

i will keep a watch on any updates.  thanks again!

**Comment by opoudjis** [comment]
My question was, whether you can get the updates to Metanorma in between releases; I'm not intending on doing another release until August 19. That's OK, I'll send you the generated Word document when I implement the fix.

**Comment by ReesePlews** [comment]
hi Nick, i understand. we were not thinking an off-schedule release. i can generate locally if you can get it fixed. the document is in a post ballot revision stage right now. if this issue can be fixed and added to the regularly scheduled release on Aug 19th that would great. we appreciate all the work you are doing on this template for the IEEE project.  thank you!

**Comment by opoudjis** [comment]
The issue is resolved, it was a simple matter of using the human-readable name, but I'm now seeing that the refreshed ToC changes "Table 1—Blah Blah Blah" to "Table 1[tab]—Blah Blah Blah". If I can't stop the tab inserting, then I will need to get rid of the em-dash.

**Comment by opoudjis** [comment]
I've spent an hour on this, and I can't get rid of the tab. I can't replicate it on  the one IEEE Word document I have access to, P2830. It is not the default behaviour for Word Tables of Figures; in fact, in order to get a tab, you have to jump through a whole set of hoops, involving adding hidden fields specifically for the table of contents to the caption, and indexing on those. And I can see nothing in the HTML exports of P2830 and P2874 to explain this difference in behaviour.


![Screenshot 2024-08-08 at 22 01 25](https://github.com/user-attachments/assets/10b78821-93a0-4a40-9730-d03f062d7292)



Given the overall low level of technical support within IEEE, that was uncovered in recent work with the updated template, I'm reasonably sure that this is going to be a recurring issue internal to them, and that they just manually remove the tabs. I'm unable to address this additional issue, and given how minor it is, I'm deciding not to.

**Comment by opoudjis** [comment]
@ReesePlews Pls find attached the compiled document you wanted.

[p2874.doc.zip](https://github.com/user-attachments/files/16546390/p2874.doc.zip)

**Comment by ReesePlews** [comment]
thank you @opoudjis ! appreciate the additional time you took. the tabs are a minor thing. nothing to worry about there. thank you for generating the document.

**Comment by ReesePlews** [comment]
@opoudjis i have made the download, perhaps that link should be removed. thank you.
