### ISSUE TITLE
(URGENT) XML: Entries in Bibliography all missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#41]
IEEE 2021 Style Manual supports a Bibliography as the first Annex.

Currently, Metanorma is not generating the contents of the Bibliography at all:
<img width="449" alt="Screenshot 2022-06-27 at 10 44 58 AM" src="https://user-images.githubusercontent.com/11865/175845081-4c55b5f2-64fa-45b6-83e2-3e259d4dd44e.png">

This can be seen at https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2

This may be a Metanorma XML problem.

**Comment by Intelligent2013** [comment]
In the presentation xml there aren't bibliographic entries:
```xml
<annex id="_" obligation="" language="" script="" displayorder="9">
	<title>
		<strong>Annex A</strong>
		<br/>(informative)</title>
	<references id="_bibliography" normative="false" obligation="informative">
		<p id="_">Bibliographical references are resources that provide additional or helpful material but do not need to be understood or used to implement this standard. Reference to these resources is made for informational use only.</p>
	</references>
</annex>
```

Also there is another issue - a redundant page break:
![image](https://user-images.githubusercontent.com/5559926/175916255-3637da96-b58f-4ce3-b093-1540a23daff1.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 thanks for the investigation.

**Comment by Intelligent2013** [comment]
'Page break' issue fixed:
![image](https://user-images.githubusercontent.com/5559926/175925458-dd02b8ca-a911-40c3-b369-3b0d63c10a3a.png)
