### ISSUE TITLE
(URGENT) Word: Annex numbered wrongly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#42]
In Word, all Annexes are missing.

The TOC shows them with "Annex X":
<img width="397" alt="Screenshot 2022-06-27 at 10 46 47 AM" src="https://user-images.githubusercontent.com/11865/175845214-24226967-13b0-4e5c-aec4-fb3c31fbc001.png">

But the content shows them with heading "N.N Annex X":
<img width="762" alt="Screenshot 2022-06-27 at 10 47 15 AM" src="https://user-images.githubusercontent.com/11865/175845252-ba5e2596-cae3-420b-bccb-18e60f69d176.png">

These Annexes cannot be accessed through the TOC due to title mismatches.

**Comment by opoudjis** [comment]
Did not have latest fixes to source.
