### ISSUE TITLE
Support references to Withdrawn IEEE standards

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#47]
Follow up from #46.

IEEE withdrawn standards:

* Footnote: IEEE Std 802.1F-1993 has been withdrawn; however, copies can be obtained from Global Engineering, 15 Inverness Way East, Englewood, CO 80112-5704, USA, tel. (303) 792-2181 (http://global.ihs.com/).

<img width="596" alt="Screenshot 2022-06-25 at 3 56 01 PM" src="https://user-images.githubusercontent.com/11865/175762381-fa3d4747-9f16-4c37-9488-a7e24d650aa6.png">

**Comment by opoudjis** [comment]
IEEE Std 802.1F-1993 is not retrievable by relaton-ieee, but IEEE Std 181-1977 does indeed return ext/standard_status = Inactive, ext/standard_modified = Withdrawn. I'm limiting this footnote to ext/standard_modified = Withdrawn where known to be the case.
