### ISSUE TITLE
(URGENT) Word: Use draft title format specified by 2021 Style Manual

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#48]
Instead of this:
![image](https://user-images.githubusercontent.com/5559926/175920333-12c77f9b-3f5e-459f-ad8f-28911abecadc.png)

We should do this according to the 2021 Style Manual:
<img width="719" alt="Screenshot 2022-06-27 at 8 17 27 PM" src="https://user-images.githubusercontent.com/11865/175929576-84467a03-54ed-4de2-9c69-44041546f76e.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ieee/issues/45#issuecomment-1167225265_

**Comment by opoudjis** [comment]
<img width="633" alt="Στιγμιότυπο 2022-06-28, 11 11 19" src="https://user-images.githubusercontent.com/1911039/176065562-4d4476af-d4aa-4518-84ed-79c081a1ad7a.png">

**Comment by ronaldtse** [comment]
@opoudjis you are mistaken here.

It should be "Draft Standard" (fully spelled). See the 2021 Style Manual quoted in the OP.
