### ISSUE TITLE
PDF: Table layout needed for membership of: working group, balloting group and Standards Board

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#54]
From the Word layout:

<img width="785" alt="Screenshot 2022-06-28 at 9 31 33 PM" src="https://user-images.githubusercontent.com/11865/176179100-a4515c93-9222-4cc9-8458-e202725dc1e8.png">

Current PDF layout:
<img width="502" alt="Screenshot 2022-06-28 at 9 32 34 PM" src="https://user-images.githubusercontent.com/11865/176179275-daa2f680-58bb-43d6-afb9-618443fab0fe.png">

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/176235206-a35493e5-e2cb-4105-a691-39096f2500f5.png)

But I can't set line numbers for each membership.

Updated IEEE xslt will be available in 25min in the metanorma-ieee repository.

**Comment by ronaldtse** [comment]
@Intelligent2013 I don't think we need the line numbers there. Thanks!

**Comment by ronaldtse** [comment]
Confirm fixed:
<img width="569" alt="Screenshot 2022-06-29 at 1 04 29 PM" src="https://user-images.githubusercontent.com/11865/176349080-8c0acbe1-574f-4922-b54c-10d75fb8e464.png">
