### ISSUE TITLE
Implement IEEE concept relationships

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#55]
From the 2021 Style Manual.

Cross-references should occur after the definition and may consist of the following classes, in the order shown: Contrast:, Syn:, See:, and See also:. 

* Contrast: refers to a term with an opposite or substantially different meaning. 
* Syn: refers to a synonymous term. 
* See: refers to a term where the desired definition can be found. 
* See also: refers to a related term. 

NOTE: "See also:" is not an existing Metanorma concept relationship.

<img width="619" alt="Screenshot 2022-06-28 at 9 42 11 PM" src="https://user-images.githubusercontent.com/11865/176181133-493072cb-92a6-42ec-bdda-feecacc3d550.png">
<img width="617" alt="Screenshot 2022-06-28 at 9 42 22 PM" src="https://user-images.githubusercontent.com/11865/176181162-ef82c440-a6d1-4379-a729-a0d9889e4ddc.png">

In the discussion with @opoudjis , "See:" is apparently the reverse of a synonym encoded in another concept. i.e. define it as an `alt:[]` or a `preferred:[]`, and the concept line with "See:" should be automatically generated.

This feature for "See:" also means that the terms will have to be sorted automatically.

**Comment by opoudjis** [comment]
seealso has been added.

**Comment by ronaldtse** [comment]
Thank you @opoudjis , I can confirm that `seealso` is available.

Given that we now have:
```
related:see[...]
related:seealso[...]
related:contrast[...]
```

Are we using:
```
related:equivalent[...]
```
(or add "syn" as an alias to equivalent?)

For Syn.? Even though we can use `preferred:[...]` for synonyms.

**Comment by opoudjis** [comment]
There is a logical distinction between multiple preferred terms, and preferred and multiple admitted terms: the multiple admitted terms are not preferred.

I am planning on doing away behind the scenes with admitted and deprecated as a cleanup. My intention, now that I think of it, is indeed to treat alt: as related:equivalent, and to leave preferred as is. The synonyms in IEEE are clearly admitted rather than fully preferred, since they don't get definitions of their own.

**Comment by ronaldtse** [comment]
I think we are conflating two issues:
1. Treatment of acronyms/abbreviated terms
2. Treatment of synonyms (alt, preferred)

## Treatment of acronyms/abbreviated terms

In IEEE, the acronym/abbreviated term is to be shown in "term (acronym/abbreviation)".
<img width="621" alt="Screenshot 2022-07-06 at 1 46 57 PM" src="https://user-images.githubusercontent.com/11865/177470753-d35bf5eb-ede0-4c2a-a53b-8b8f8044d558.png">

The only way to enter acronyms/abbreviated terms in Metanorma is through a combination of "synonym" (`preferred` or `alt`) with `abbreviation-type`.

## Treatment of synonyms (alt, preferred)

In IEEE, synonyms (`preferred` and `alt`) are entered as individual entries. They are NOT to be included in parentheses.

<img width="571" alt="Screenshot 2022-07-06 at 1 51 45 PM" src="https://user-images.githubusercontent.com/11865/177471315-d2d5b506-5e16-4ee1-9f61-9f906fde1d50.png">

In Metanorma there are two ways to enter a synonym indicating different levels of usage preference. In the sample shown above, the term that includes a definition is the preferred one.

This can be encoded as (if no change is made to Metanorma):
```adoc
==== code set
related:see[coded character set]

==== coded character set
related:equivalent[code set]

A set of characters.
```

Or just this (when Metanorma becomes smart):
```adoc
==== coded character set
alt:[code set]

A set of characters.
```

Notice however we need to differentiate whether a term is from the current document, or from the IEEE Dictionary.

The IEEE dictionary can be a potential new termbase. Note that an item in the IEEE dictionary can be referred by a `termId` as in:
https://ieeexplore.ieee.org/browse/standards/dictionary?queryText=adjust:&termId=16864714935346904198

But it's not easy to find this `termId`.


## Moving ahead:

1. `admitted:[]` is equivalent to `alt:[]`. This was already requested by OGC a while ago.
2. Synonyms that are `preferred:[]` will be shown as "Syn:".
3. Synonyms that are abbreviations will be rendered in parentheses after the concept, and there is no "Syn:" built for those.

**Comment by opoudjis** [comment]
> admitted:[] is equivalent to alt:[]. This was already requested by OGC a while ago.

admitted and alt have been treated the same since January. https://github.com/metanorma/metanorma-ogc/issues/339

**Comment by opoudjis** [comment]
Current documentation:

````
The notation for subdefinitions and cross-references in Metanorma is:

[source,asciidoc]
----
=== widget

alt:[doovywhack] // Syn:

related:contrast[thing] // Contrast:

related:seealso[whatsit] // See also:

[.definition]
--
device performing an unspecified function.
--

[.definition]
--
general metasyntactic variable.
--
----

which renders as:

____

*widget*: *(A)* device performing an unspecified function. *(B)* general metasyntactic variable. _Contrast:_ thing.
_Syn:_ doovywhack. _See also:_ whatsit.
____

Do NOT insert markup for _See:_ terms. _See:_ terms are the opposite relations to "Syn:" relations; Metanorma will
automatically generate an entry for the synonymous term, pointing back to the original entry:

___

*doovywhack*: _See:_ widget.
___

Do use `+alt:[...]+` for synonyms, rather than `related:equivalent[]`: the latter is intended to cross-reference
pre-existing term definitions, and that is not how IEEE treats _Syn:_ entries. 

Do use `+alt:[...]+` instead of `+preferred[...]+` for _Syn:_ entries. The `+preferred[...]+` syntax is intended for 
names that are fully equivalent in preference, such as acronyms.

TODO: acronyms
````
