### ISSUE TITLE
(URGENT) PDF: Normative references should not be tagged with "[B1] ... [Bn]"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#57]
From the 2021 Style Manual:
<img width="733" alt="Screenshot 2022-06-29 at 1 02 51 PM" src="https://user-images.githubusercontent.com/11865/176348904-24802227-a9e4-4a6a-9c5b-8f6e746e4f10.png">

From the document:
<img width="925" alt="Screenshot 2022-06-29 at 1 02 05 PM" src="https://user-images.githubusercontent.com/11865/176348830-1e7a0fc1-c274-447c-b29e-81975d467771.png">

We should use whatever reference tag is supplied by Metanorma Presentational XML instead of numbering them in XSLT.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/176362755-91d167f2-5df2-4f22-bd84-acc082f4cfca.png)

Also line-height changed to fit template.

**Comment by ronaldtse** [comment]
Confirm fixed:
<img width="708" alt="Screenshot 2022-06-29 at 3 24 17 PM" src="https://user-images.githubusercontent.com/11865/176366121-b6a6a8a5-7b11-48d4-b6aa-dbe669664558.png">
