### ISSUE TITLE
(URGENT) Word and PDF: definitions clause not showing bibliographic sources

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#58]
PDF:

<img width="664" alt="Screenshot 2022-06-29 at 2 04 50 PM" src="https://user-images.githubusercontent.com/11865/176355816-452ff66e-7077-4f33-8194-be3160fd6bba.png">

Word:
<img width="812" alt="Screenshot 2022-06-29 at 2 05 58 PM" src="https://user-images.githubusercontent.com/11865/176355963-502ca63f-2b6b-4c69-bf39-5cce9f92fb7c.png">

**Comment by Intelligent2013** [comment]
Empty `origin` in presentation xml:
```xml
 <p><strong>interoperability</strong>: ability of two or more systems or applications to exchange information and to mutually use the information that has been exchanged

(<origin bibitemid="ISO-IEC_27729" type="inline" citeas=""/>)</p>
```

In aa-bibliography.adoc there are items:
```adoc

[appendix,obligation=informative]
== Bibliography

...
* [[[ISO-IEC_27729,ISO/IEC 27729]]]
...
```

but non-normative references section in xml is empty:
```xml
<annex ...
<references id="_bibliography" normative="false" obligation="informative">
<p id="_">Bibliographical references are resources that provide additional or helpful material but do not need to be understood or used to implement this standard. Reference to these resources is made for informational use only.</p>
</references>
</annex>
```
I assume that issue in the bibliography in annex processing.

**Comment by ronaldtse** [comment]
As pointed out by @opoudjis , the issue is the following:

Original encoding:
```adoc
[bibliography]
== Bibliography

* [[[ISO-IEC-TR_23188,ISO/IEC TR 23188:2020]]]

* [[[ISO-IEC_17788,ISO/IEC 17788:2014]]]
```

Fixed encoding:
```adoc
[appendix,obligation=informative]
== Bibliography

[bibliography]
=== Bibliography

* [[[ISO-IEC-TR_23188,ISO/IEC TR 23188:2020]]]

* [[[ISO-IEC_17788,ISO/IEC 17788:2014]]]
```

For reasons in the AsciiDoc parser, the "appendix" cannot be a "bibliography", so we need to provide the "Bibliography" section twice for the bibliography section recognised.

**Comment by ronaldtse** [comment]
Confirm fixed:
Word:
<img width="802" alt="Screenshot 2022-06-29 at 3 02 32 PM" src="https://user-images.githubusercontent.com/11865/176362917-bc524805-81bb-479b-96b4-b242091fe945.png">

PDF:
<img width="643" alt="Screenshot 2022-06-29 at 3 02 08 PM" src="https://user-images.githubusercontent.com/11865/176362868-6db60575-7ca5-4843-ae13-9f2d32730f63.png">
