### ISSUE TITLE
(URGENT) "EXAMPLE" in terms clause looks awkward amongst other text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#60]
<img width="818" alt="Screenshot 2022-06-29 at 2 43 51 PM" src="https://user-images.githubusercontent.com/11865/176360496-bef24a98-d2e7-4308-9073-c480256ff37b.png">

According to the 2021 Style Manual, 10.2 provides samples of Examples (can't find samples in 19.2):
<img width="668" alt="Screenshot 2022-06-29 at 2 47 26 PM" src="https://user-images.githubusercontent.com/11865/176360954-d722fb74-5aa9-4851-b5c1-42afb1fdce70.png">

10.2:
<img width="670" alt="Screenshot 2022-06-29 at 2 46 52 PM" src="https://user-images.githubusercontent.com/11865/176360884-65a2283f-e718-4991-b4d0-f958bf4f2366.png">

**Comment by ronaldtse** [comment]
PDF looks reasonable, but "EXAMPLE" needs to be in sentence case ("Example:"):

<img width="663" alt="image" src="https://user-images.githubusercontent.com/11865/176362214-3fa642df-eacc-4779-aafe-b3995630f065.png">

**Comment by Intelligent2013** [comment]
> PDF looks reasonable, but "EXAMPLE" needs to be in sentence case ("Example:"):

ping @opoudjis :
```xml
<termexample id="_">
  <name>EXAMPLE</name>
  <p id="_">Gateways, routers, switches, multiplexers, and a variety of other access devices.</p>
```

**Comment by opoudjis** [comment]
An *italic* example title?! Ugh.

**Comment by Intelligent2013** [comment]
Now PDF renders so:
![image](https://user-images.githubusercontent.com/5559926/176456549-af3082ce-1cb5-48bd-8e3b-2ad5c266acc4.png)
