### ISSUE TITLE
(URGENT) Word: next term too close to previous term's last NOTE

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#61]
The Word layout places the next term too close to the last NOTE of the previous term.
<img width="796" alt="Screenshot 2022-06-29 at 2 55 54 PM" src="https://user-images.githubusercontent.com/11865/176362087-e0764c9b-5864-4c8b-9c6c-206d7833a728.png">

The PDF looks reasonable:
<img width="664" alt="Screenshot 2022-06-29 at 2 58 18 PM" src="https://user-images.githubusercontent.com/11865/176362396-cc7a5c2b-65af-4a19-82ff-11237b6b2d4c.png">

**Comment by ronaldtse** [comment]
1. Can we add the same amount of space after the last NOTE as with a new term?
2. Can we slightly reduce the margin between the term definition and the first NOTE?

<img width="798" alt="Screenshot 2022-06-30 at 12 03 43 AM" src="https://user-images.githubusercontent.com/11865/176470192-7b7097e8-6efb-4cc3-a5fb-0c85bfed84ca.png">

**Comment by opoudjis** [comment]
No, and no. I am not mucking around with the styles defined in the IEEE template. That's they styles they've published, that's what we use. Closing ticket as vexatious.
