### ISSUE TITLE
PDF: double [B1] number in Bibliography

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#63]
![image](https://user-images.githubusercontent.com/5559926/176365887-69899958-51f6-4024-a5ab-22fea93b2f3f.png)

**Comment by Intelligent2013** [comment]
Xml:
```xml
<bibitem id="EVANS_DDD">
	<formattedref format="application/x-isodoc+xml">Eric EVANS. <em>Domain-Driven Design: Tackling Complexity in Software</em>. Addison-Wesley: 2004.</formattedref>
	<docidentifier type="metanorma">[B1]</docidentifier>
</bibitem>
<bibitem id="ISO-IEC_17788" type="standard">
	<formattedref>Information technology — Cloud computing — Overview and vocabulary.</formattedref>
...
	<docidentifier type="metanorma-ordinal">[B1]</docidentifier>
...
</bibitem>
<bibitem id="ISO-IEC_18039" type="standard">
	<formattedref>Information technology — Computer graphics, image processing and environmental data representation — Mixed and augmented reality (MAR) reference model.</formattedref>
...
	<docidentifier type="metanorma-ordinal">[B2]</docidentifier>
...
</bibitem>
```

**Comment by Intelligent2013** [comment]
adoc:
```
* [[[EVANS_DDD,1]]], Eric EVANS. _Domain-Driven Design: Tackling Complexity in Software_. Addison-Wesley: 2004.
```

**Comment by Intelligent2013** [comment]
@opoudjis could you check please, is this normal behavior when first bibitem has:
`<docidentifier type="metanorma">[B1]</docidentifier>` and 
second one has `<docidentifier type="metanorma-ordinal">[B1]</docidentifier>`?

**Comment by opoudjis** [comment]
Ugh, no.  They are meant to renumber consecutively. I understand why this has happened, will fix.

**Comment by Intelligent2013** [comment]
@opoudjis thanks!

Fixed:
![image](https://user-images.githubusercontent.com/5559926/176391404-e277315d-59d8-4f61-b263-2cffecc48ac2.png)

**Comment by ronaldtse** [comment]
Confirmed PDF, thanks @Intelligent2013 !

<img width="684" alt="Screenshot 2022-06-29 at 7 41 55 PM" src="https://user-images.githubusercontent.com/11865/176417848-12513ee3-254a-4d9b-9f77-837b1a052546.png">
