### ISSUE TITLE
PDF published layout: Front cover and inner cover with wrong information

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#66]
Originally from #45.

Encoding:

```adoc
= Spatial Web Protocol, Architecture and Governance
:docnumber: 2874
:doctype: standard
:docstage: published
```

The cover page and inner cover page of the published layout should have the cover and inner cover with correct information.

<img width="603" alt="Screenshot 2022-06-30 at 1 53 16 AM" src="https://user-images.githubusercontent.com/11865/176493107-b667b1ab-a6bc-4fdc-8104-2f76d2161126.png">
<img width="605" alt="Screenshot 2022-06-30 at 1 55 39 AM" src="https://user-images.githubusercontent.com/11865/176493412-042865c9-0fa5-46dc-ad8c-f761662411b2.png">

**Comment by Intelligent2013** [comment]
XML tags from https://github.com/metanorma/metanorma-ieee/issues/12:

> `isbn-pdf`:: The ISBN of the PDF document.
> `isbn-print`:: The ISBN of the print document.
> 
> `stdid-pdf`:: The final standard identifier of the PDF document.
> `stdid-print`:: The final standard identifier of the print document.
> 
> realised as:
> 
> ````
>            <docidentifier type='IEEE' scope='PDF'>GHI</docidentifier>
>            <docidentifier type='IEEE' scope='print'>JKL</docidentifier>
>            <docidentifier type='ISBN' scope='PDF'>ABC</docidentifier>
>            <docidentifier type='ISBN' scope='print'>DEF</docidentifier>
> ````
> 
> I've modelled the Developed By and its Parent as committee and society:
> 
> ````
> `society`:: The IEEE society responsible for the document. Do not include the "IEEE" prefix.
> `committee`:: The committee responsible for the document.
> `working-group`:: The working group responsible for the document.
> `balloting-group`:: The Standards Association balloting group responsible for the document.
> ````
> 
> Rendered as:
> 
> ````
>             <ext>
>               <doctype>standard</doctype>
>               <editorialgroup>
>                 <society>SECRETARIAT</society>
>                 <balloting-group>SC</balloting-group>
>                 <working-group>WG</working-group>
>                 <working-group>WG1</working-group>
>                 <committee>TC</committee>
>                 <committee>TC1</committee>
>               </editorialgroup>
> ````
> 
> Approved date and Approved By are:
> 
> `confirmed-date`:: The date on which the document was approved.
> 
> i.e. `<date type="confirmed">`
> 
> Currently, the Approved By is static text: "IEEE SA Standards Board". 
> 
> 
> The "Revision of" points to the document this document updates; so, `:updates:`.
> 
> The "Incorporates" could be one of:
> 
> > includes
> > document A includes document B, through a well-defined relation outlined in [Host item](https://www.relaton.org/specs /model/relations/#host-item), and with distinct metadata (including authorship) and bibliographic record (e.g. Chapter in Edited > Work, Illustration) (includedIn)
> > 
> > hasPart
> > document A includes document B, with no distinct metadata (other than extent) or bibliographic record, and all items in document B share the same authorship or corporate authorship (e.g. Chapter, Section, Part, Volume, Issue, Track) (partOf)
> > 
> > merges
> > document A results from a merger of earlier documents B1, B2, B3…​ (mergedInto)
> 
> "Includes" is article and journal or paper and collected volume; it does not apply here, because the content is seamlessly  integrated into the present content. "hasPart" also doesn't apply, because the prior documents are not distinct parts of this document. Therefore, this is `:merges:`.
> 
> The results in bibdata are:
> 
> ````
>     <relation type='merges'>
>       <bibitem>
>         <title>--</title>
>         <docidentifier>BCD</docidentifier>
>       </bibitem>
>     </relation>
>     <relation type='merges'>
>       <bibitem>
>         <title>--</title>
>         <docidentifier>EFG</docidentifier>
>       </bibitem>
>     </relation>
>     <relation type='updates'>
>       <bibitem>
>         <title>--</title>
>         <docidentifier>ABC</docidentifier>
>       </bibitem>
>     </relation>
> ````
