### ISSUE TITLE
How to encode "Participants" and "Members"

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#67]
What would be the correct attribute(s) to encode participants and members?

![capture4](https://user-images.githubusercontent.com/33627611/176586416-0797e1bf-1e6c-4443-a932-58e59738e58d.PNG)

**Comment by opoudjis** [comment]
See the IEEE PR in github.com/metanorma/metanorma.Org

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma.org/pull/611/files

**Comment by opoudjis** [comment]
`society`:: The IEEE society responsible for the document. Do not include the "IEEE" prefix.
 `committee`:: The committee responsible for the document.
 `working-group`:: The working group responsible for the document.
 `balloting-group`:: The Standards Association balloting group responsible for the document.
IEEE requires listing the full membership of the working group, balloting group, and
 standards board responsible for the document. The current membership of the balloting group and
 standards board is normally provided by IEEE during editing; if the information is not provided in
 the document, dummy values will be provided to match those in the IEEE templates.
 This information is provided as follows; all names are given inline as full names.

 `wg_chair`:: The working group chair
 `wg_vicechair`:: The working group vice-chair
 `wg_secretary`:: The working group secretary
 `wg_members`:: The working group members, semicolon-delimited

 `balloting_group_members`:: The balloting group members, semicolon-delimited
 `std_board_chair`:: The standards board chair
 `std_board_vicechair`:: The standards board vice-chair
 `std_board_pastchair`:: The standards board past chair
 `std_board_secretary`:: The standards board secretary
 `std_board_members`:: The standards board members, semicolon-delimited. Any emeritus members should be given with an asterisk at the end of their names
