### ISSUE TITLE
Encoding "Line heading" and "Subheading" in a table

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#68]
The formatting of a table in IEEE document includes a "Line heading" and "Subheading":

![capture5](https://user-images.githubusercontent.com/33627611/176587001-17b1aa28-2fc0-4915-9cb9-c9be86308b35.PNG)

From the image above, it can be seen that the "Subheading" has a certain indentation respect "Line heading".

Another example:

![capture6](https://user-images.githubusercontent.com/33627611/176587488-2e3c3ac5-1e81-457e-85da-5d5dd4c70434.PNG)

Do we have any special markup to encode this?

**Comment by opoudjis** [comment]
So *that's* what that means.

Treat them as header cells, `h|High pressure`. I don't have a markup convention yet, but assume for now second paragraph in the header cell:

h| Low pressure
Gas-filled

And I'll see if it works

**Comment by opoudjis** [comment]
It doesn't work: you can't make a cell be both a| and h|, and I was assuming two paragraphs in the markup, which requires a|.

I think I'll get away with this: mark it up as a line break:

````
h|Low pressure +
Gas-filled | ...
````
