### ISSUE TITLE
PDF: IEEE Standard template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#7]
Please follow https://github.com/metanorma/ieee-ref-docs/blob/main/standards/8021X-2020.pdf

**Comment by Intelligent2013** [comment]
Used fonts:
- Arial (2nd page, titles, header/footer)
- Calibri (cover, back pages)
- Calibri Light
- Courier New (source code)
- ~Helvetica~
- Montserrat-ExtraBold (vertical `STANDARDS` on the cover page, and `RAISING THE WORLD’S STANDARDS ` on back page)
- Symbol
- Times New Roman (main font)
- Wingdings
- Wingdings3

**Comment by ronaldtse** [comment]
I am unable to find the Word template for this. 

Do we know where Symbol/Wingdings/Wingdings3 is used? We want to minimise the font set.

**Comment by Intelligent2013** [comment]
- Symbol - can't find
- Wingdings - in the figure:
![image](https://user-images.githubusercontent.com/5559926/173797836-dc877387-f7bd-463b-ad35-8080d1d1a2b8.png)
- Wingdings3 - arrow glyph:
![image](https://user-images.githubusercontent.com/5559926/173798681-f1e95b68-c06e-4249-a005-91489b961c4c.png)

So no need to use Wingdings fonts.

**Comment by ronaldtse** [comment]
Thanks, so these are only needed in the sample content. They are not used in the layout and we don't need them.

**Comment by Intelligent2013** [comment]
@ronaldtse which languages should we support? If English only, then we can rasterize vertical `STANDARDS` on the cover page, and `RAISING THE WORLD’S STANDARDS` on back page to remove the font `Montserrat-ExtraBold` from the font set.

**Comment by ronaldtse** [comment]
@Intelligent2013 English only -- but we do not want to rasterise due to scaling. We could potentially convert those to outlines and SVGs for embedding. Montserrat is a freely licensed font, so including it is also fine. I think including the font is the easiest to do for now.

**Comment by ronaldtse** [comment]
@Intelligent2013 just in case can you also strike-out the "Wingdings" and "Wingdings3" fonts from above? Thanks.

**Comment by Intelligent2013** [comment]
Source code `font-size` is 8pt:
![image](https://user-images.githubusercontent.com/5559926/176625443-bf462b4c-bf23-4718-ac78-120e1ab62d7d.png)


Mono-spaced text (`tt`) `font-size` is 10pt (as main text):
![image](https://user-images.githubusercontent.com/5559926/176625623-f13fe51b-ca1d-4371-9ec2-43baa3ed4e57.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 I believe the source code font size should be identical. I don't think we need to especially handle this.

**Comment by Intelligent2013** [comment]
XSLT updated for 'Standard' template.
Xslt render it by `doctype='standard'` and `stage='published'`.

**Comment by Intelligent2013** [comment]
Done.
