### ISSUE TITLE
Include the "adapted from" text in definition sources

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#73]
In relation to https://github.com/metanorma/mn-samples-ieee/issues/1 and https://github.com/metanorma/mn-samples-ieee/pull/4

Some references from *Terms and definitions* clause are prefixed with the text "adapted from":

![issue1](https://user-images.githubusercontent.com/33627611/176809127-a7afa178-4d42-4f8e-a780-9fb80e8170f7.PNG)

Is there a way to include this text by markup?

Currently this part is encoded like this:
````
==== drift rate

The slope at a stated time of...

[.source]
<<iso-iec_9945-1>>
````

**Comment by opoudjis** [comment]
As with BSI, do this as:

````
[source,asciidoc]
----
[.source%adapted]
<<reference>>
----
````

**Comment by ronaldtse** [comment]
And we will need to document this.

**Comment by manuelfuenmayor** [comment]
@opoudjis, by using your implementation I get this:

![capture1](https://user-images.githubusercontent.com/33627611/177392669-43a141f3-b6a7-4516-b6c6-2ff827998e3d.PNG)

(no "adapted from" text)

**Comment by opoudjis** [comment]
Works here:

````

[.source%adapted]
<<iso>>

[bibliography]
== Bibliography
* [[[iso,ISO 639]]]
````

<img width="692" alt="Στιγμιότυπο 2022-07-06, 13 28 38" src="https://user-images.githubusercontent.com/1911039/177462101-9cf50eb7-0ab3-4a3f-9045-62dd6c80381c.png">

Make sure you pull from github, and that you do bundle update, did a release on Monday night.

**Comment by manuelfuenmayor** [comment]
You're right! Confirmed fixed. Thanks!
