### ISSUE TITLE
"Acknowledgements" clause encoding

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#76]
Accoding to the [documentation](https://github.com/metanorma/metanorma.org/pull/611/files#diff-e7160534c607a83e4cdf30c6e42c963f2f947b1938ebd8844aac3f40bd0b4afaR19):

*'The permissions of the document are marked up as a clause with the title "Acknowledgements".'*

But, on one hand, @ronaldtse [says](https://github.com/metanorma/mn-samples-ieee/pull/4#discussion_r912343100) that this clause should be automatically generated.

On the other hand, if this clause is to be marked up, it needs to be prefixed with `[.preface]` 
in order to place it at prefatory area.

I.e:
````
[.preface]
== Acknowledgments

Permissions have been granted as follows:
````

**Comment by opoudjis** [comment]
That should not be necessary, Acknowledgements should be recognised by title. Will investigate.

**Comment by ronaldtse** [comment]
> this clause should be automatically generated

This is correct.

**Comment by opoudjis** [comment]
The following in rspec of metanorma-ieee is processed correctly:

````
      [abstract]
      == Abstract

      Text

      == Introduction

      === Introduction Subsection

      == Acknowledgements

````

with the acknowledgements in  the right place. @manuelfuenmayor where is a document where this is failing?

**Comment by opoudjis** [comment]
Acknowledgements vs Acknowledgments: I'll recognise both.
