### ISSUE TITLE
PDF: IEEE Industry connection report template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#8]
https://github.com/metanorma/ieee-ref-docs/blob/main/industry-connection-report/XR_Business_Finance_Economics.pdf

**Comment by Intelligent2013** [comment]
Used fonts:
- Arial-Black (titles on the cover page,  titles)
- Arial (signature text under Abstract)
- Calibri (main text)
- Calibri Light (`Authored by ...` on the cover page, preface sections text)
- Montserrat-ExtraBold (vertical title on the cover page)
- Symbol
- Winddings

**Comment by ronaldtse** [comment]
Word template:
[IC_Activity_White_Paper_Template.docx](https://github.com/metanorma/metanorma-ieee/files/8904468/IC_Activity_White_Paper_Template.docx)

Related to #5

**Comment by Intelligent2013** [comment]
For memory: xslt currently choose IEEE Industry connection report template by `bibdata/ext/ doctype = 'industry-connection-report'` (set in the text xml manually for development purpose). This condition should be changed to the real value of doctype after metanorma-ieee update for whitepaper.

**Comment by Intelligent2013** [comment]
Done.
