### ISSUE TITLE
PDF: presence of attribute title-main-en causes title to render twice

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#80]
Presence of attribute `title-main-en` causes title to render twice.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/11865/177392814-516f9621-0283-495b-a6a5-47db2c0512d1.png">

```adoc
= Draft Recommended Practice for Preparing an IEEE Standards Draft
...
:title-main-en: Draft Recommended Practice for Preparing an IEEE Standards Draft
```
_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-ieee/pull/4#discussion_r914083728_

**Comment by Intelligent2013** [comment]
`= Draft Recommended Practice for Preparing an IEEE Standards Draft`
converts to:
```xml
<title language="en" format="text/plain">Draft Recommended Practice for Preparing an IEEE Standards Draft</title>
```

`:title-main-en: Draft Recommended Practice for Preparing an IEEE Standards Draft`
converts to
```xml
<title language="main-en" format="text/plain">Draft Recommended Practice for Preparing an IEEE Standards Draft</title>
```

For draft doctype, xslt should render only 1st `title`.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/177401216-a154b90f-fdb1-406b-b48b-8ea5bbcd488d.png)

Updated IEEE xslt will be available in metanorma-ieee in ~20min.
