### ISSUE TITLE
Treatment of acronyms

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ieee#81]
From https://github.com/metanorma/metanorma-ieee/issues/55
 

## Treatment of acronyms/abbreviated terms

In IEEE, the acronym/abbreviated term is to be shown in "term (acronym/abbreviation)".
<img width="621" alt="Screenshot 2022-07-06 at 1 46 57 PM" src="https://user-images.githubusercontent.com/11865/177470753-d35bf5eb-ede0-4c2a-a53b-8b8f8044d558.png">

The only way to enter acronyms/abbreviated terms in Metanorma is through a combination of "synonym" (`preferred` or `alt`) with `abbreviation-type`.

## Moving ahead:

3. Synonyms that are abbreviations will be rendered in parentheses after the concept, and there is no "Syn:" built for those.

**Comment by opoudjis** [comment]
In Metanorma, terms (designations) are allowed to be indicated as an abbreviation through the `abbreviation-type` attribute. The `abbreviation-type` attribute can be set to various values including: `acronym`, `symbol` and `initialism`.

When encountering a designation with such attribute, the abbreviation should be rendered in parenthesis after the main designation:
* `*my term (abbreviation 1, abbreviation 2, ...)*: ... my definition`

For example:

```adoc
==== trusted execution environment
[%metadata]
language:: eng
abbreviation-type:: initialism

preferred:[TEE]

A secure area within a processor that runs in parallel with the operating system
in an isolated environment and that ensures that the code and data running in it
are protected with respect to privacy and integrity.
```

This should be rendered as:
<img width="772" alt="Screenshot 2022-07-04 at 11 30 56 AM" src="https://user-images.githubusercontent.com/11865/177071317-d3a04d3b-9544-4d64-890c-10c0e5e9694c.png">

**Comment by opoudjis** [comment]
I am proposing to loosen the condition so that we don't need to mark this up as an abbreviation:

* `admitted:[]` is rendered as _Syn:_
* `preferred:[]` is rendered in parentheses

In truth, these are behaving the way that a preferred vs admitted distinction would, so I think this is acceptable as a workaround.

**Comment by ronaldtse** [comment]
@opoudjis the IEEE Style Manual only has a provision for using parentheses for abbreviations:
<img width="579" alt="Screenshot 2022-07-15 at 9 09 54 PM" src="https://user-images.githubusercontent.com/11865/179220182-f08e7013-6d0a-4b23-bef0-29de5972cf13.png">

Moreover, given this description:

<img width="575" alt="Screenshot 2022-07-15 at 9 22 31 PM" src="https://user-images.githubusercontent.com/11865/179222061-6d7daf8a-4bc8-4fb7-acae-c7d7ab00e84b.png">

I would think that all synonyms (admitted or preferred) should use the "Syn:" and "See:" pair?

**Comment by opoudjis** [comment]
Conceded.

So preferred and admitted are treated the same. Abbreviations are indicated by following the preferred or admitted designation with an abbreviation type:

````
==== trusted execution environment

preferred:[TEE]

[%metadata]
abbreviation-type:: initialism
````

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by opoudjis** [comment]
Grrrrr
