### ISSUE TITLE
updates in bibdata

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ieee#85]
Refactoring of bibdata, from https://github.com/metanorma/metanorma-ieee/issues/52

//bibdata/ext/doctype has values standard, guide, recommended-practice

//bibdata/ext/subdoctype has values amendment, corrigendum, erratum

//bibdata/ext/trial-use has values true, false, default false (it was formerly a value of subdoctype)

`//bibdata/date[@type = 'feedback-ended-date']` and `//bibdata/date[@type = 'obsoleted-date']` need to be displayed in the front page of any Trial Use documents. 

Legal values of //bibdata/status/stage are Developing, Active, Inactive

**Comment by Intelligent2013** [comment]
Currently, IEEE xslt for PDF generation supports:
- Draft standard (doctype = 'standard' and stage < 60 or = 'draft'),
- Standard (doctype = 'standard' and stage >= 60 or 'published')
- Whitepaper (doctype = 'whitepaper', preliminary value)
- ICAP Whitepaper (doctype = 'icap-whitepaper', preliminary value)
- Industry connection report  (doctype = 'industry-connection-report', preliminary value)

To do:
- [ ] expand the condition for Draft standard to
doctype = ('standard' or 'guide' or 'recommended-practice') and stage < 60 or = 'draft'

- [ ] update IEEE xslt to support amendment, corrigendum, erratum for Draft standards (see IEEESTD-WORDTEMPLATE_Amendments-Corri-v7-2022.docx )

- [ ] update IEEE xslt for 'Trial-use'.
From style manual:
![image](https://user-images.githubusercontent.com/5559926/178143895-5e958ab1-b999-4517-ad9e-2c51c6d15c85.png)
 and display dates `//bibdata/date[@type = 'feedback-ended-date']` and `//bibdata/date[@type = 'obsoleted-date']`

**Comment by Intelligent2013** [comment]
@opoudjis is there xml element for Amendment/Corrigenda number (`#` on the screenshot)?
![image](https://user-images.githubusercontent.com/5559926/178159420-6efff252-6616-4b73-b0bf-9d9283f3d4b8.png)

**Comment by Intelligent2013** [comment]
Looks like no need to put the number instead of `#`. From Style manual (page 61):
![image](https://user-images.githubusercontent.com/5559926/178286379-3dc52c73-83f7-4edd-bedb-22a4f2bfe103.png)

**Comment by Intelligent2013** [comment]
Example of the resulted PDF for Trial-Use:
![image](https://user-images.githubusercontent.com/5559926/178475771-fd83c9f1-c089-465d-853f-8721b525aa4e.png)

**Comment by Intelligent2013** [comment]
Done.
