### ISSUE TITLE
PDF: Whitepaper template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#9]
https://github.com/metanorma/ieee-ref-docs/blob/main/whitepaper/IEEE%20Std%202030.5.pdf

**Comment by Intelligent2013** [comment]
Used fonts:
- Arial
- Calibri (main font)
- Calibri Light (`Authored by ...`)
- Cambria (text under `Trademarks and Disclaimers `)
- FranklinGothic-Heavy
- MicrosoftSansSerif
- Montserrat-ExtraBold (titles on the cover page)
- Symbol
- Times New Roman (title on the back page)
- Wingdings

**Comment by ronaldtse** [comment]
@Intelligent2013 word file template also here:
[IEEE-SA_White_Paper_Template.docx](https://github.com/metanorma/metanorma-ieee/files/8904456/IEEE-SA_White_Paper_Template.docx)
 
This is related to #4.

**Comment by ronaldtse** [comment]
Do we know where FranklinGothic-Heavy and MicrosoftSansSerif are used? We want to minimise the font set. Thanks!

**Comment by Intelligent2013** [comment]
> Do we know where FranklinGothic-Heavy and MicrosoftSansSerif are used? We want to minimise the font set. Thanks!

- FranklinGothic-Heavy - can't find.
- MicrosoftSansSerif - one footnote reference:
![image](https://user-images.githubusercontent.com/5559926/173806964-596925ed-e666-4e81-87e3-c65b2972e4b8.png)

**Comment by Intelligent2013** [comment]
@ronaldtse there are differences in the styles between https://github.com/metanorma/ieee-ref-docs/blob/main/whitepaper/IEEE%20Std%202030.5.pdf and https://github.com/metanorma/metanorma-ieee/files/8904456/IEEE-SA_White_Paper_Template.docx. Which styles are preferable - from PDF or docx?


Examples:

- additional page in the PDF:
![image](https://user-images.githubusercontent.com/5559926/174443294-8d7b3fe3-ad23-4c6a-bfc2-69a34fc7f276.png)

- difference in 2nd page:
Doc:
![image](https://user-images.githubusercontent.com/5559926/174443551-f8898d53-b74d-441d-8b49-381ea36f03e9.png)

PDF:
![image](https://user-images.githubusercontent.com/5559926/174443342-5ae8da1c-afde-482e-8ab3-0f5d860549f4.png)

- difference in 3rd page:
Doc:
![image](https://user-images.githubusercontent.com/5559926/174443381-fe3b83ba-984a-42b2-9740-46f49259c56f.png)


PDF:
![image](https://user-images.githubusercontent.com/5559926/174443364-71b96f80-4ba3-42f6-acc8-1619b7c7818d.png)


- ToC:
Doc:
![image](https://user-images.githubusercontent.com/5559926/174443409-ef63c3b7-8715-4bc2-b25f-c1b1ed4d2e71.png)

PDF:
![image](https://user-images.githubusercontent.com/5559926/174443400-cde87051-fdf7-407d-ae98-018bdb8ecab0.png)

- Footer:
Doc:
![image](https://user-images.githubusercontent.com/5559926/174443443-33bd5a8a-0f0d-4dde-ae07-21819be11c8c.png)

PDF:
![image](https://user-images.githubusercontent.com/5559926/174443458-05247e94-cdc9-46a3-a02a-21b0b2075b5a.png)

- there are another differences in the styles

**Comment by ronaldtse** [comment]
@Intelligent2013 for now, we only encode the Template designs because they are 2022. The other styles are from previous years.

The better solution is probably to add template styles for the same flavor in the future (e.g. OGC we have "old branding" vs "new branding", for ISO Word output we have "Simple Template" vs "Edited DIS Template").

**Comment by Intelligent2013** [comment]
Updated fonts list:

- used fonts in 2022 template design (https://github.com/metanorma/metanorma-ieee/files/8901412/IEEE-SA_White_Paper_Template.docx):
  - Calibri (main font)
  - Calibri Light (`Authored by ...`, preface text)
  - Arial Black (cover page, back page, new 2022 style)
  - Arial (footer, copyright text)

- used fonts in the previous template (example [IEEE Std 2030.5.pdf](https://github.com/metanorma/ieee-ref-docs/blob/main/whitepaper/IEEE%20Std%202030.5.pdf)):
  - ~Arial~ (white-spaces)
  - Calibri (main font)
  - Calibri Light (`Authored by ...`)
  - Cambria (text under `Trademarks and Disclaimers `)
  - ~FranklinGothic-Heavy~ (can't find)
  - ~MicrosoftSansSerif~
  - Montserrat-ExtraBold (titles on the cover page)
  - ~Symbol~ (can't find)
  - Times New Roman (title on the back page)
  - ~Wingdings~ (dot label for unordered list item)

**Comment by Intelligent2013** [comment]
There are discrepancies between Style Manual (https://github.com/metanorma/metanorma-ieee/files/8901439/IEEE-SA-Non_Standard_Projects_Style_Manual.pdf) and Word template (https://github.com/metanorma/metanorma-ieee/files/8901412/IEEE-SA_White_Paper_Template.docx):

### 1. `Lists of tables and figures are not included in the table of contents.`
![image](https://user-images.githubusercontent.com/5559926/176360402-5ec6f746-b092-4f4b-ac9a-51e0aac8fc66.png)

But Table of Contents contains `FIGURE x` and `TABLE x` items:
![image](https://user-images.githubusercontent.com/5559926/176360577-6a3494db-c83b-4b08-8e8b-2e581d083ac3.png)

Should be omit figures and table in ToC at all, or `Lists of tables and figures are not included in the table of contents.` means "don't include lists of tables/figures under the standalone titles 'Lists of tables' and 'Lists of figure'"?

### 2. `“Table” and the table number, followed by an em dash and the table title, all on one line, centered above the top border of the table, as follows: “Table 1—Title”.`

![image](https://user-images.githubusercontent.com/5559926/176361297-1ad5091d-17b3-4a96-b7d5-739b743457ed.png)

but the example in Word template has uppercased 'TABLE' without dash:
![image](https://user-images.githubusercontent.com/5559926/176361593-edafcb1a-5c78-4a7c-9a9f-05cae29b7586.png)

Which style is preferable - from Style Manual or word template?
The same question relates to the figures.

**Comment by Intelligent2013** [comment]
Just for memory, xslt currently choose IEEE Whitepaper template by `bibdata/ext/ doctype = 'whitepaper'` (set in the text xml manually for development purpose). This condition should be changed to the real value of doctype after metanorma-ieee update for whitepaper.

**Comment by Intelligent2013** [comment]
Done.
