### ISSUE TITLE
From IEEE: 1.3 Word usage, unindent the first list item

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#91]
2022-02-04 template:
<img width="476" alt="Screenshot 2022-07-12 at 8 35 18 PM" src="https://user-images.githubusercontent.com/11865/178480995-704223cb-f4f7-4753-86cd-f571b8491315.png">

2022-06-16 template:
<img width="472" alt="Screenshot 2022-07-12 at 8 35 44 PM" src="https://user-images.githubusercontent.com/11865/178481063-2983b41d-e5a3-4e4a-b351-56e9d6c48e1a.png">

IEEE clarified that the old template was wrong. We need to update our Word/PDF output.

**Comment by opoudjis** [comment]
I do not currently populate this text. I will, since it is mandatory anyway.

**Comment by opoudjis** [comment]
Proceeding: Overview is a reserved title, so we will find it.

**Comment by ronaldtse** [comment]
It seems that the section title is currently missing for 1.3. The content is there, but not the title (in the case of Word, the title is set to "1.3")

PDF:
<img width="475" alt="Screenshot 2022-07-13 at 12 30 10 AM" src="https://user-images.githubusercontent.com/11865/178527851-08b7299c-aadd-40bf-b008-54b34a6c6c0e.png">

Word:
<img width="829" alt="Screenshot 2022-07-13 at 12 30 31 AM" src="https://user-images.githubusercontent.com/11865/178527908-b01eabb7-cd98-4d71-8757-ccb0f2afe296.png">
