### ISSUE TITLE
Encoding nonvoting members

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-ieee#94]
"Participants" in IEEE STL document include additional roles which aren't yet supported by Metanorma. Those are yellow highlighted below.

![image](https://user-images.githubusercontent.com/55683568/178573641-c671d966-5640-4a54-b1be-d657f2a83fc1.png)

**Comment by ronaldtse** [comment]
From https://github.com/metanorma/mn-samples-ieee-private/pull/8#issuecomment-1184247997:

It looks like that there are two types of non-voting participants.

The external liaisons (first group below) and then the IEEE internal roles.

<img width="442" alt="Screenshot 2022-07-14 at 6 56 37 PM" src="https://user-images.githubusercontent.com/11865/178956384-ca63b05e-8d6b-4059-a951-185fb9cfab34.png">

For those two types in this image, I propose we do:
```
:ieee-sasb-liaison-name: DeBlasio, Richard
:ieee-sasb-liaison-role: DOE Representative
:ieee-sasb-liaison-name_2: Janezic, Michael
:ieee-sasb-liaison-role_2: NIST Representative
```

And:

```
:ieee-internal-name: Messina, Don
:ieee-internal-role: IEEE Standards Program Manager, Document Development
:ieee-internal-name_2: Spiewak, Erin
:ieee-internal-role_2: IEEE Standards Program Manager, Technical Program Development
```

What do you think ?

**Comment by opoudjis** [comment]
I am going to instead propose that we have three subclauses in a Participants clause, which I fold into boilerplate in post-processing. There will be default text that gets put at the start of each subclause, but the list of participants, and trailing acknowledgments and further lists, will need to be supplied by the author.

The lists of participants will be ordered lists or unordered lists. If roles are specified, they will be definition lists. If affiliations are specified, they will be definition lists. Utter self-indulgent nonsense in formatting, such as the subject of this ticket (some office holders have two lines, some have one, some have their memberships implicit in the previous paragraph) I'm either not going to attempt to emulate at all, or I'll make some arbitrary rule involving field length.

Trying to impose order on the participants boilerplate has been a waste of time. IEEE do not treat their own boilerplate like templated text, and we can't if they won't.

**Comment by ronaldtse** [comment]
Agree with using a list type input for participants, it is unwieldy to use document attributes to house so many participant entries.

**Comment by opoudjis** [comment]
Following what I have implemented, that additional content is to be marked up as:

````
== Participants
=== Standards Board

...

Also included are the following nonvoting IEEE-SA Standards Board liaisons:

item::
name::: Richard DeBlasio
role::: DOE Representative
item::
name::: Michael Janezic
role::: NIST Representative

//-

item::
name::: Don Messina
role::: IEEE Standards Program Manager, Document Development
item::
name::: Erin Spiewak
role::: IEEE Standards Program Manager, Technical Program Development
````

**Comment by opoudjis** [comment]
Leave the ticket open, I have not done the fine detail yet of whether to render roles on the same line or a separate line. In my opinion, I shouldn't need to...

**Comment by opoudjis** [comment]
I'm going to do only partial realisation of the ad hoc rules:

* No boldface after initial listing of officeholders
* New line for role if role is longer than 30 characters
