### ISSUE TITLE
PDF: Automatic generation of IEEE boilerplate

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-ieee#96]
Boilerplate doesn't get automatically generated in PDF.

From www.metanorma.org:
> The templated material ("boilerplate") of the document front matter is all automatically provided by Metanorma:
> * Front page: Copyright statement, license statement
> * Second page: Contact statement, ISBNs
> * Important Notices and Disclaimers Concerning IEEE Standards Documents
> * Participants statement (the membership of the various committees is provided as document attributes)
> * The note before the overview in amendments, indicating how formatting is to be interpreted

**Comment by Intelligent2013** [comment]
IEEE xslt updated in the branch (feature/xslt-update' (https://github.com/metanorma/metanorma-ieee/tree/feature/xslt-update)
Now PDF renders with the preface pages:
![image](https://user-images.githubusercontent.com/5559926/178718762-1356e965-2ecc-4576-9da5-352438091bb9.png)

![image](https://user-images.githubusercontent.com/5559926/178718713-732c33a2-6e60-44f5-a648-57c17fdce151.png)

**Comment by anermina** [comment]
Thanks @Intelligent2013 !
Can you just check why the list of keywords ends after the first one?

Keywords are encoded as follows (comma-delimited):
````
:keywords: A-weighted sound level, commercial zone, community involvement, hazardous material, IEEE 1127(TM), industrial zone, noise, permitting process, residential zone, wetlands
````

**Comment by Intelligent2013** [comment]
> Can you just check why the list of keywords ends after the first one?

@anermina it is the xslt issue. In one previous example the keywords encoded wrong with semicolon in the one xml element, and I thought that 'keyword' element contains pre-rendered value.

**Comment by Intelligent2013** [comment]
Closing, fixed a while ago.
