### ISSUE TITLE
Word: In Participants, provide semantic styles for names, roles and entities

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#97]
## WG members

Given names:
<img width="1130" alt="Screenshot 2022-07-14 at 8 27 14 PM" src="https://user-images.githubusercontent.com/11865/178972938-d303fe3e-8146-434e-99f6-262a6443d15f.png">

Surname:
<img width="1131" alt="Screenshot 2022-07-14 at 8 27 21 PM" src="https://user-images.githubusercontent.com/11865/178972970-c7d17acf-28c1-4b0c-b982-7b5b195c3291.png">

Role:
<img width="1126" alt="Screenshot 2022-07-14 at 8 27 27 PM" src="https://user-images.githubusercontent.com/11865/178973053-9ff0bec5-f349-4c95-872e-72d034f0f7db.png">

Entity names:
<img width="1181" alt="Screenshot 2022-07-14 at 8 27 38 PM" src="https://user-images.githubusercontent.com/11865/178973084-8b94f18d-3940-41e2-b034-24a170e85ae4.png">

## Standards participants
<img width="1144" alt="Screenshot 2022-07-14 at 8 27 44 PM" src="https://user-images.githubusercontent.com/11865/178973117-c9b8cf67-628a-4599-bd21-37753fdbe790.png">

<img width="1144" alt="Screenshot 2022-07-14 at 8 27 44 PM" src="https://user-images.githubusercontent.com/11865/178973289-bf06cd50-7bb3-406e-bc0d-6d04753a477e.png">

<img width="1161" alt="Screenshot 2022-07-14 at 8 27 54 PM" src="https://user-images.githubusercontent.com/11865/178973272-3bbf2158-0be7-4900-877d-b2eebc9b930b.png">

## Balloting

<img width="1178" alt="Screenshot 2022-07-14 at 8 28 02 PM" src="https://user-images.githubusercontent.com/11865/178973330-765a317a-cbe1-4ab9-bb4d-837c7926884e.png">

## SASB members
<img width="682" alt="Screenshot 2022-07-14 at 8 28 19 PM" src="https://user-images.githubusercontent.com/11865/178973349-6ef019c4-93a3-4361-be7d-6bddd40d5234.png">

Member emeritus:
<img width="1173" alt="Screenshot 2022-07-14 at 8 28 30 PM" src="https://user-images.githubusercontent.com/11865/178973363-2d3e0865-9f2a-48cf-8909-4f9c81154da6.png">

**Comment by opoudjis** [comment]
In order to get semantic markup of forenames and surnames, we will require semantic markup in the Asciidoc source: `span:surname[...]`, `span:forename[...]`, span:organization[...]`.

**Comment by opoudjis** [comment]
Finding some needed debugging of participants processing.

**Comment by opoudjis** [comment]
The style "IEEE Stds Entities Participants" is not present in the 2022 tempalte. I am introducing the markup `<span class="organization">` when I detect an entity, but I am not at this time going to do anything at all with it, unless I can see a current IEEE Word document with a corresponding style definition.
