### ISSUE TITLE
Word: Standards references should be semantically tagged

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#98]
Publisher:
<img width="1151" alt="Screenshot 2022-07-14 at 8 28 38 PM" src="https://user-images.githubusercontent.com/11865/178973514-ad06a864-22e5-411d-ab7b-56cadc3c3f1a.png">

Document type:
<img width="1129" alt="Screenshot 2022-07-14 at 8 28 43 PM" src="https://user-images.githubusercontent.com/11865/178973557-3bc3e065-32c5-4bb0-989d-f083bf88e2cd.png">

Document number:
<img width="1134" alt="Screenshot 2022-07-14 at 8 28 48 PM" src="https://user-images.githubusercontent.com/11865/178973565-de4e40ef-059a-445b-8e8e-47ab13b1d00b.png">

Year:
<img width="1138" alt="Screenshot 2022-07-14 at 8 28 52 PM" src="https://user-images.githubusercontent.com/11865/178973577-2ae268ba-cc1a-464f-85e7-489a54cc71d0.png">

**Comment by opoudjis** [comment]
Apply maximum length = 20 criterion for doc identifier non-breaking spaces before it is annotated with nbsp
